from ..models import Group
from ..constants import *
from ...work.y2015 import hinsen2015a

approach = Group(
    hinsen2015a,
    _category = "Unrelated", # It is a packaging approach that does not collect provenance by itself
    display="Active Papers", # Python edition
    approach_name="Active Papers",
    _cite=False,

    _meta=[dict(
        binary=NO,
        languages=[PYTHON],

        goal=REPRODUCIBILITY,
        supports=[REPRODUCIBILITY, MANAGEMENT],
        categories=[REPRODUCIBILITY, MANAGEMENT, PACKAGE],

        mode=USER_LEVEL,

        tools=[],
        
        annotations=[EXECUTABLE, EXTERNAL, INCLUSIVE],
        execution=[],
        deployment=[SNAPSHOT],
        definition=[ASKS, READING],

        execution_granularity=[],
        deployment_granularity=[MODULES],
        definition_granularity=[CONTENT, SOURCE],

        cache=NO,
        replay=YES,
        evolution=NO,
        pipeline=NO,
        summarization=[],

        distribution=[PACKAGE.such_as(["HDF5"])],
        storage=[PACKAGE.such_as(["HDF5"])],
        visualization=[], 
        query=[COMMAND],
        integration=[],
        
        granularity=[MODULES, CONTENT, SOURCE],
        granularity_text="Modules, Datasets, Source",
        thread=YES,
        diff=NO,
                    
        limitations=[],
    )],
    _about="""
        <p>
            ActivePapers - Python edition (<a href="#hinsen2015a">hinsen2015a</a>) is an approach that produces <span class="storage">HDF5 packages</span> with Python programs, datasets, and modules.
            It requires users to specify which files should go into these packages for reproducibility and it supports the definition of dummy files that can be generated by the execution of programs in the packages.
            It also records alls versions of Python modules and support module extensions (C modules) outside the environment.
        </p>
        <p class="distribution storage">
            An ActivePaper is associated with a DOI and it supports referring to other ActivePapers by their DOI to access their data or programs
        </p>
    """,
)