# coding: utf-8
from snowballing.models import *
from snowballing import dbindex
dbindex.last_citation_file = dbindex.this_file(__file__)

from ..work.y2006 import langtangen2006a
from ..work.y2007 import perez2007a
from ..work.y2008 import freire2008a
from ..work.y2008 import bochner2008a
from ..work.y2010 import angelino2010a
from ..work.y2012 import davison2012a
from ..work.y2012 import mckinney2012a
from ..work.y2012 import tariq2012a
from ..work.y2013 import chirigati2013a
from ..work.y2013 import stevens2013a
from ..work.y2014 import murta2014a
from ..work.y2014 import shen2014a
from ..work.y2014 import stamatogiannakis2014a
from ..work.y2014 import wibisono2014a
from ..work.y2015 import pimentel2015a
from ..work.y2016 import thavasimani2016a
from ..work.y2016 import ma2016a


DB(Citation(
    pimentel2015a, angelino2010a, ref="[1]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, bochner2008a, ref="[2]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, chirigati2013a, ref="[3]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, davison2012a, ref="[4]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, freire2008a, ref="[5]",
    contexts=[
        "rovenance can help scientists to interpret ex-periments’ results, check if the experiments were executed as ex-pected, understand the sequence of operations that lead to the re-sults, and enable reproducibility [5].",
        
    ],
))

DB(Citation(
    pimentel2015a, langtangen2006a, ref="[6]",
    contexts=[
        "Since IPython runs on top of Python, it keeps all advantages of using Python scripts for computational science, such as a clean and simple syntax, the simplicity to integrate external tools, and to run simulations [6]",
        
    ],
))

DB(Citation(
    pimentel2015a, mckinney2012a, ref="[7]",
    contexts=[
        "Weforeseetheintegration of noWorkﬂow with Pandas [7] to improve provenance analysis.",
        
    ],
))

DB(Citation(
    pimentel2015a, murta2014a, ref="[8]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        "We propose an approach that addresses this limitation and al-lows transparent provenance capture directly from the notebook. Inprevious work, we introduced noWorkflow [8], a tool that transpar-ently captures provenance from Python scripts and provides mech-anisms that allows users to explore this information",
        "noWorkﬂow (not only Workﬂow) [8] is an approach that automatically captures provenance from Python scripts without requiring any modiﬁcations to the script",
        "Architecture of noWorkﬂow [8]",
        "This line magic supports all arguments that the default now run command supports (see [8] for details on those commands).",
        "This magic also loads Prolog rules that are automatically generated by noWorkﬂow (see [8]).",
        
    ],
))

DB(Citation(
    pimentel2015a, perez2007a, ref="[9]",
    contexts=[
        "Python Notebook originated from IPython [9], a Python shellthat  provides  powerful  features  for  interactive  scientific  computing",
        
    ],
))

DB(Citation(
    pimentel2015a, shen2014a, ref="[10]",
    contexts=[
        "Notebooks are being widely used: the traffic tothe IPython Notebook Web site suggests that more than 500,000people actively use it [10].",
        "While it helps scientists to explore, share, and keep track oftheir experiments interactively [10], provenance support in IPythonNotebook is limited.",
        
    ],
))

DB(Citation(
    pimentel2015a, stamatogiannakis2014a, ref="[11]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, stevens2013a, ref="[12]",
    contexts=[
        "Lancet [12], on the other hand, allows scientists to perform exploratory research on IPython Notebook by capturing provenance and visualizing results",
        
    ],
))

DB(Citation(
    pimentel2015a, tariq2012a, ref="[13]",
    contexts=[
        "If  a  scientist  wants  to  capturemore provenance about an experiment, she must export or rewriteher experiment into an external script and run an external tool tocapture and analyze provenance from the script [1–4, 8, 11, 13].",
        
    ],
))

DB(Citation(
    pimentel2015a, wibisono2014a, ref="[14]",
    contexts=[
        "Ducktape[14]generatesIPython notebooks with visualizations for provenance captured from external experiments",
        
    ],
))

DB(Citation(
    thavasimani2016a, pimentel2015a, ref="",
    contexts=[

    ],
))

DB(Citation(
    ma2016a, pimentel2015a, ref="",
    contexts=[

    ],
))
