# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


abadi1999a = DB(WorkUnrelated(
    1999, "A core calculus of dependency",
    due="Unrelated to scripts, unrelated to provenance. May be used as a technique to obtain provenance",
    may_be_related_to=["program slicing"],
    display="abadi",
    authors="Abadi, Martín and Banerjee, Anindya and Heintze, Nevin and Riecke, Jon G",
    summary="Proposes Dependency Core Calculus (DCC) as a centro notion of dependency for many applications that need to track dependencies",
    place=POPL,
    file="Abadi1999a.pdf",
    pp="147--160",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=944648359989853597&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="944648359989853597",
    organization="ACM",
    scholar_ok=True,
))

baeza1999a = DB(WorkUnrelated(
    1999, "Modern information retrieval",
    due="Unrelated to scripts. Unrelated to provenance",
    display="baeza",
    authors="Baeza-Yates, Ricardo and Ribeiro-Neto, Berthier and others",
    place=Book,
    link="http://www2.dcc.ufmg.br/livros/irbook/",
    publisher="Addison-Wesley Reading",
    file="Baeza1999a.pdf",
    entrytype="book",
    cluster_id="17157916999812790334",
    volume="463",
    scholar="http://scholar.google.com/scholar?cites=17157916999812790334&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

burnett1999a = DB(WorkUnrelated(
    1999, "Visual programming",
    due="Unrelated to provenance",
    display="burnett",
    authors="Burnett, Margaret M",
    place=Book,
    file="Burnett1999a.pdf",
    collection="Encyclopedia of Electrical and Electronics Engineering",
    publisher="Wiley Online Library",
    editors="J. G. Webster",
    entrytype="book",
    cluster_id="3001800007669957495",
    scholar="http://scholar.google.com/scholar?cites=3001800007669957495&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

dubois1999a = DB(WorkUnrelated(
    1999, "Ten good practices in scientific programming",
    due="Unrelated to provenance",
    star2="importance of python for applications in science and engineering. script como ligação",
    display="dubois",
    authors="Dubois, Paul F",
    summary="1-get ready for changes; 2-use scripts instead of compiled code; 3-VCS; 4-Design by contract; 5-Fortran 95 (don't use 77); 6-steer compiled code through scripts; 7-use multiple languages; 8-C++ instead of C; 9-templates at C++; 10-brace your inner programmer",
    place=CiSE,
    file="Dubois1999a.pdf",
    volume="1",
    number="1",
    pp="7--11",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11342059295424704509&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="AIP Publishing",
    cluster_id="11342059295424704509",
    scholar_ok=True,
))

golub1999a = DB(WorkUnrelated(
    1999, "Molecular Classification of Cancer: Class Discovery and Class Prediction by Gene Expression Monitoring",
    due="Unrelated to scripts. Unrelated to provenance",
    display="golub",
    authors="Golub, Todd R and Slonim, Donna K and Tamayo, Pablo and Huard, Christine and Gaasenbeek, Michelle and Mesirov, Jill P and Coller, Hilary and Loh, Mignon L and Downing, James R and Caligiuri, Mark A and others",
    place=Science,
    volume="286",
    number="5439",
    pp="531--537",
    file="Golub1999a.pdf",
    entrytype="article",
    cluster_id="11689410846973970080",
    publisher="American Association for the Advancement of Science",
    scholar="http://scholar.google.com/scholar?cites=11689410846973970080&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

gyimothy1999a = DB(WorkUnrelated(
    1999, "An efficient relevant slicing method for debugging",
    due="Unrelated to provenance. Can be used to capture provenance of selected variables though",
    may_be_related_to=["slicing"],
    display="gyimóthy",
    authors="Gyimóthy, Tibor and Beszédes, Árpád and Forgács, István",
    summary="Proposes a slicing technique for debugging that not only identifies statements that influenced a variable, but also statements that could potentially influentiate it",
    place=ESEC_FSE,
    file="Gyimothy1999a.pdf",
    pp="303--321",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6343383400246246765&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6343383400246246765",
    organization="Springer",
    scholar_ok=True,
))

halpin1999a = DB(WorkUnrelated(
    1999, "Data modeling in UML and ORM: a comparison",
    due="Unrelated to provenance",
    display="halpin",
    authors="Halpin, Terry and Bloesch, Anthony",
    place=JDM,
    file="Halpin1999a.pdf",
    volume="10",
    number="4",
    pp="4--13",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11936293164884830264&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="IGI Global",
    cluster_id="11936293164884830264",
    scholar_ok=True,
))

horvitz1999a = DB(WorkUnrelated(
    1999, "Principles of mixed-initiative user interfaces",
    due="Unrelated to scripts. Unrelated to provenance",
    display="horvitz",
    authors="Horvitz, Eric",
    place=CHI,
    file="Horvitz1999a.pdf",
    pp="159--166",
    entrytype="inproceedings",
    cluster_id="11362710211563919707",
    scholar="http://scholar.google.com/scholar?cites=11362710211563919707&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

myers1999a = DB(WorkUnrelated(
    1999, "JFlow: Practical mostly-static information flow control",
    due="Unrelated to provenance, unrelated to scripts. Deals with security of data",
    display="myers",
    authors="Myers, Andrew C",
    summary="Proposes a language bases on Java with privacy and integrity protection through static analysis",
    place=POPL,
    file="Myers1999a.pdf",
    pp="228--241",
    local="New York, NY, USA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=3012104675867545340&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="3012104675867545340",
    organization="ACM",
    scholar_ok=True,
))

mylopoulos1999a = DB(WorkUnrelated(
    1999, "From object-oriented to goal-oriented requirements analysis",
    due="Unrelated to provenance",
    display="mylopoulos",
    authors="Mylopoulos, John and Chung, Lawrence and Yu, Eric",
    place=CACM,
    file="Mylopoulos1999a.pdf",
    volume="42",
    number="1",
    pp="31--37",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=6864417891477329076&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="6864417891477329076",
    scholar_ok=True,
))

nost1999a = DB(WorkUnrelated(
    1999, "Definition of the flexible image transport system (FITS)",
    due="Standard. Unrelated to provenance",
    display="nost",
    authors="Nost",
    place=Standard,
    file="Nost1999a.pdf",
    entrytype="article",
    scholar_ok="impossible",
))

nrc1999a = DB(WorkUnrelated(
    1999, "Global Environmental Change: Research Pathways for the Next Decade",
    due="Unrelated to provenance, unrelated to scripts",
    display="nrc",
    authors="National Research Council",
    summary="Defines pathways for reasearch of global environment change",
    place=Book,
    file="Nrc1999a.pdf",
    local="Washington, DC",
    publisher="National Academy Press",
    entrytype="book",
    scholar_ok="impossible",
))

olson1999a = DB(WorkUnrelated(
    1999, "Berkeley DB",
    due="Unrelated to provenane, unrelated to scripts",
    may_be_related_to=["database"],
    display="olson",
    authors="Olson, Michael A and Bostic, Keith and Seltzer, Margo I",
    summary="Describes the design and technical features of Berkeley DB",
    place=ATC,
    file="Olson1999a.pdf",
    track="FREENIX",
    local="Monterey, CA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7369655594680737909&as_sdt=2005&sciodt=0,5&hl=en",
    pp="183--191",
    cluster_id="7369655594680737909",
    scholar_ok=True,
    publisher="USENIX Association",
))

rekimoto1999a = DB(WorkUnrelated(
    1999, "Time-machine computing: a time-centric approach for the information environment",
    due="Unrelated to scripts",
    display="rekimoto",
    authors="Rekimoto, Jun",
    place=UIST,
    file="Rekimoto1999a.pdf",
    publisher="ACM",
    local="New York, NY, USA",
    entrytype="inproceedings",
    cluster_id="3143517752318750560",
    scholar="http://scholar.google.com/scholar?cites=3143517752318750560&as_sdt=2005&sciodt=0,5&hl=en",
    pp="45--54",
    organization="ACM",
    scholar_ok=True,
))

romeu1999a = DB(WorkUnrelated(
    1999, "Data quality and pedigree",
    due="Unrelated to scripts",
    display="romeu",
    authors="Romeu, Jorge Luis",
    place=AMPTIAC_News,
    number="1",
    volume="3",
    file="Romeu1999a.pdf",
    entrytype="article",
    cluster_id="7293130237676121451",
    scholar="http://scholar.google.com/scholar?cites=7293130237676121451&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

ronsse1999a = DB(WorkUnrelated(
    1999, "RecPlay: a fully integrated practical record/replay system",
    due="Unrelated to provenance. May beu sed as technique for collection",
    display="ronsse",
    authors="Ronsse, Michiel and De Bosschere, Koen",
    place=TOCS,
    file="Ronsse1999a.pdf",
    volume="17",
    number="2",
    pp="133--152",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=12840250462779713633&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="12840250462779713633",
    scholar_ok=True,
))

santry1999a = DB(WorkUnrelated(
    1999, "Deciding when to forget in the Elephant file system",
    due="Unrelated to provenance",
    display="santry",
    authors="Santry, Douglas S and Feeley, Michael J and Hutchinson, Norman C and Veitch, Alistair C and Carton, Ross W and Ofir, Jacob",
    place=OSR,
    file="Santry1999a.pdf",
    volume="33",
    number="5",
    pp="110--123",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=600573507466988529&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="600573507466988529",
    organization="ACM",
    scholar_ok=True,
    local="New York, NY, USA",
    publisher="ACM",
))

walters1999a = DB(WorkUnrelated(
    1999, "VMware virtual platform",
    due="Unrelated to provenance",
    display="walters",
    authors="Walters, Brian",
    place=LinuxJournal,
    link="http://www.linuxjournal.com/article/3458",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=4417088760702141046&as_sdt=2005&sciodt=0,5&hl=en",
    number="63es",
    volume="1999",
    pp="6",
    publisher="Belltown Media",
    cluster_id="4417088760702141046",
    scholar_ok=True,
))

zadok1999a = DB(WorkUnrelated(
    1999, "Extending File Systems Using Stackable Templates",
    due="Unrelated to provenance, unrelated to scripts",
    display="zadok",
    authors="Zadok, Erez and Badulescu, Ion and Shender, Alex",
    summary="Proposes a stackable template file system (Wrapfs)",
    place=ATC,
    file="Zadok1999a.pdf",
    local="Monterey, CA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=8121991598646094589&as_sdt=2005&sciodt=0,5&hl=en",
    pp="57--70",
    cluster_id="8121991598646094589",
    scholar_ok=True,
))
