# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


agrawal2006a = DB(WorkUnrelated(
    2006, "Trio: A system for data, uncertainty, and lineage",
    due="Unrelated to scripts",
    display="agrawal",
    authors="Agrawal, Parag and Benjelloun, Omar and Sarma, Anish Das and Hayworth, Chris and Nabar, Shubha and Sugihara, Tomoe and Widom, Jennifer",
    place=VLDB,
    pp="1151--1154",
    file="Agrawal2006a.pdf",
    entrytype="inproceedings",
    cluster_id="11941670788708435920",
    publisher="Springer",
    scholar="http://scholar.google.com/scholar?cites=11941670788708435920&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok="check all versions",
))

altintas2006a = DB(WorkUnrelated(
    2006, "Provenance collection support in the kepler scientific workflow system",
    due="Unrelated to scripts. Provenance suppport for workflow system",
    may_be_related_to=["workflow"],
    display="altintas",
    authors="Altintas, Ilkay and Barney, Oscar and Jaeger-Frank, Efrat",
    summary="Presents provenance collection in Kepler. Defines workflow, captures provenance from workflow, stores workflow separetely, tracks evolution",
    place=IPAW,
    file="Altintas2006a.pdf",
    pp="118--132",
    proceedings="LNCS 4145",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=10200865700598986854&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="10200865700598986854",
    scholar_ok=True,
    publisher="Springer",
    local="Chicago, IL, USA",
))

barga2006a = DB(WorkUnrelated(
    2006, "Automatic generation of workflow provenance",
    due="Unrelated to scripts",
    display="barga",
    authors="Barga, Roger S and Digiampietri, Luciano A",
    place=IPAW,
    pp="1--9",
    proceedings="LNCS 4145",
    publisher="Springer",
    file="Barga2006a.pdf",
    entrytype="inproceedings",
    cluster_id="7455886154129422939",
    scholar="http://scholar.google.com/scholar?cites=7455886154129422939&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

becker2006a = DB(WorkUnrelated(
    2006, "The C++ Standard Library Extensions: a Tutorial and Reference",
    due="Unrelated to scripts. Unrelated to provenance",
    display="becker",
    authors="Becker, Pete",
    place=Book,
    local="Reading, MA",
    link="http://www.petebecker.com/tr1book/tr1book.html",
    publisher="Addison-Wesley",
    file="Becker2006a.pdf",
    entrytype="book",
    cluster_id="3130581465564059111",
    scholar="http://scholar.google.com/scholar?cites=3130581465564059111&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

benjelloun2006a = DB(WorkUnrelated(
    2006, "ULDBs: Databases with uncertainty and lineage",
    due="Unrelated to script. Provenance is part of data",
    may_be_related_to=["database"],
    display="benjelloun",
    authors="Benjelloun, Omar and Sarma, Anish Das and Halevy, Alon and Widom, Jennifer",
    summary="Proposes a DB system that supports provenance and uncertainty",
    place=VLDB,
    file="Benjelloun2006a.pdf",
    pp="953--964",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12760427008417327956&as_sdt=2005&sciodt=0,5&hl=en",
    organization="VLDB Endowment",
    cluster_id="12760427008417327956",
    scholar_ok=True,
))

bex2006a = DB(WorkUnrelated(
    2006, "Inference of concise DTDs from XML data",
    due="Unrelated to provenance. Unrelated to scripts",
    display="bex",
    authors="Bex, Geert Jan and Neven, Frank and Schwentick, Thomas and Tuyls, Karl",
    place=VLDB,
    file="Bex2006a.pdf",
    pp="115--126",
    publisher="VLDB Endowment",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12686164247043775645&as_sdt=2005&sciodt=0,5&hl=en",
    organization="VLDB Endowment",
    cluster_id="12686164247043775645",
    scholar_ok=True,
))

bishop2006a = DB(WorkUnrelated(
    2006, "Pattern Recognition and Machine Learning",
    due="Unrelated to scripts. Unrelated to provenance",
    display="bishop",
    authors="Bishop, Christopher M",
    place=Book,
    publisher="Springer Science+Business Media LLC",
    file="Bishop2006a.pdf",
    entrytype="book",
    cluster_id="6918077279019606730",
    volume="128",
    scholar="http://scholar.google.com/scholar?cites=6918077279019606730&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1--58",
    scholar_ok=True,
))

bowers2006a = DB(WorkUnrelated(
    2006, "A model for user-oriented data provenance in pipelined scientific workflows",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="kepler",
    authors="Bowers, Shawn and McPhillips, Timothy and Ludäscher, Bertram and Cohen, Shirley and Davidson, Susan B",
    place=IPAW,
    file="Bowers2006a.pdf",
    pp="133--147",
    local="Chicago, IL",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7642085223488918682&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="7642085223488918682",
    scholar_ok=True,
))

braun2006a = DB(WorkUnrelated(
    2006, "A security model for provenance",
    due="Excluding Tech Reports",
    may_be_related_to=["security"],
    display="braun",
    authors="Braun, Uri and Shinnar, Avi",
    summary="Proposes a security model for provenance that consists on two non-interfering models: one protects the prospective provenance and the other specifies which attributes are accessible to which users",
    place=TechReport,
    file="Braun2006a.pdf",
    number="TR-04-06",
    institution="Harvard University",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2157927810924092304&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="2157927810924092304",
    scholar_ok=True,
))

braun2006b = DB(WorkUnrelated(
    2006, "Issues in automatic provenance collection",
    star="[collection][x] Define observed/disclosed provenance concepts. Discusses challenges on automatic collaction",
    due="Unrelated to scripts",
    display="braun",
    authors="Braun, Uri and Garfinkel, Simson and Holland, David A and Muniswamy-Reddy, Kiran-Kumar and Seltzer, Margo I",
    define={
        "observed provenance system": "observe execution and collect provenance",
        "disclosed provenance system": "user specify what she wants to capture",
    },
    place=IPAW,
    file="Braun2006b.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=13357038926248676725&as_sdt=2005&sciodt=0,5&hl=en",
    pp="171--183",
    organization="Springer",
    cluster_id="13357038926248676725",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

braun2006c = DB(WorkUnrelated(
    2006, "Coping with cycles in provenance",
    due="Excluding TechReports",
    display="braun",
    authors="Braun, Uri and Holland, David A and Muniswamy-Reddy, Kiran-Kumar and Seltzer, Margo I",
    place=TechReport,
    file="Braun2006c.pdf",
    entrytype="techreport",
    cluster_id="16500066416567653258",
    scholar="http://scholar.google.com/scholar?cites=16500066416567653258&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

buneman2006a = DB(WorkUnrelated(
    2006, "Provenance management in curated databases",
    due="Unrelated to scripts. Provenance is stored in the Database",
    may_be_related_to=["database"],
    display="buneman",
    authors="Buneman, Peter and Chapman, Adriane and Cheney, James",
    summary="Investigates general-purpose techniques for recording provenance for data that is copied among databases",
    place=SIGMOD,
    file="Buneman2006a.pdf",
    pp="539--550",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=863611360081918963&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="863611360081918963",
    scholar_ok=True,
))

callahan2006a = DB(WorkUnrelated(
    2006, "Using provenance to streamline data exploration through visualization",
    due="Excluding TechReports",
    display="callahan a",
    authors="Callahan, Steven P and Freire, Juliana and Santos, Emanuele and Scheidegger, Carlos E and Silva, Cláudio T and Vo, Huy T",
    place=TechReport,
    file="Callahan2006a.pdf",
    local="SCI Institute",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2177009271108530555&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Citeseer",
    cluster_id="2177009271108530555",
    scholar_ok=True,
))

callahan2006b = DB(WorkUnrelated(
    2006, "VisTrails: visualization meets data management",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="callahan b",
    authors="Callahan, Steven P and Freire, Juliana and Santos, Emanuele and Scheidegger, Carlos E and Silva, Cláudio T and Vo, Huy T",
    place=SIGMOD,
    file="Callahan2006b.pdf",
    local="New York, NY, USA",
    pp="745--747",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=17964346563016288608&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="17964346563016288608",
    scholar_ok=True,
    publisher="ACM",
))


callahan2006c = DB(WorkUnrelated(
    2006, "Managing the Evolution of Dataflows with VisTrails",
    due="Unrelated to scripts",
    may_be_related_to=["evolution"],
    display="callahan",
    authors="Callahan, Steven P and Freire, Juliana and Santos, Emanuele and Scheidegger, Carlos Eduardo and Silva, Claudio T and Vo, Huy T",
    doi="10.1109/ICDEW.2006.75",
    pp="71--71",
    place=ICDE,
    file="Callahan2006c.pdf",
    entrytype="inproceedings",
    local="Atlanta, USA",
    publisher="IEEE",
    cluster_id="2654237949456305319",
    scholar="http://scholar.google.com/scholar?cites=2654237949456305319&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    scholar_ok=True,
))

carnevale2006a = DB(WorkUnrelated(
    2006, "The NEURON Book",
    due="Unrelated to scripts. Unrelated to provenance",
    display="carnevale",
    authors="Carnevale, Nicholas T and Hines, Michael L",
    place=Book,
    publisher="Cambridge University Press",
    local="New York, NY",
    file="Carnevale2006a.pdf",
    entrytype="book",
    cluster_id="16748305503022696562",
    scholar="http://scholar.google.com/scholar?cites=16748305503022696562&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

cederqvist2006a = DB(WorkUnrelated(
    2006, "Version Management with CVS",
    due="Unrelated to scripts. Unrelated to provenance",
    display="cederqvist",
    authors="Cederqvist, Per and Pesch, Roland and others",
    place=Book,
    file="Cederqvist2006a.pdf",
    publisher="Network Theory Ltd.",
    entrytype="book",
    cluster_id="6347506209129980205",
    scholar="http://scholar.google.com/scholar?cites=6347506209129980205&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

chang2006a = DB(WorkUnrelated(
    2006, "Bigtable: a distributed storage system for structured data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="chang",
    authors="Chang, Fay and Dean, Jeffrey and Ghemawat, Sanjay and Hsieh, Wilson C and Wallach, Deborah A and Burrows, Mike and Chandra, Tushar and Fikes, Andrew and Gruber, Robert E",
    place=OSDI,
    file="Chang2006a.pdf",
    pp="205--218",
    publisher="ACM",
    entrytype="inproceedings",
    cluster_id="535416719812038974",
    scholar="http://scholar.google.com/scholar?cites=535416719812038974&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok="check all versions",
))

chen2006a = DB(WorkUnrelated(
    2006, "On the use of semantic annotations for supporting provenance in grids",
    due="Unrelated to scripts",
    display="chen",
    authors="Chen, Liming and Jiao, Zhuoan and Cox, Simon J",
    place=EuroPar,
    entrytype="inproceedings",
    file="Chen2006a.pdf",
    cluster_id="16384813053739113396",
    scholar="http://scholar.google.com/scholar?cites=16384813053739113396&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    ID="chen2006use",
    pp="371--380",
    scholar_ok=True,
))

cohen2006a = DB(WorkUnrelated(
    2006, "Towards a model of provenance and user views in scientific workflows",
    due="Unrelated to scripts. It focus on workflow systems",
    may_be_related_to=["workflow"],
    star="[analysis][x] Talks about different forms of abstractions of provenance. In this paper, the abstracts are for users (user views)",
    display="cohen",
    authors="Cohen, Shirley and Cohen-Boulakia, Sarah and Davidson, Susan",
    summary="Proposes a formal and general model of provenance for scientific workflows that takes into accouunt chained and nested structure and supports different levels of abstractions",
    place=DILS,
    file="Cohen2006a.pdf",
    proceedings="LNCS 4075",
    pp="264--279",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=613704909338988446&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="613704909338988446",
    scholar_ok=True,
))

cosmo2006a = DB(WorkUnrelated(
    2006, "Maintaining large software distributions: new challenges from the FOSS era",
    due="Unrelated to provenance",
    display="cosmo",
    authors="Di Cosmo, Roberto and Durak, Berke and Leroy, Xavier and Mancinelli, Fabio and Vouillon, Jérôme",
    place=FRCSS,
    file="Cosmo2006a.pdf",
    pp="7--20",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=9177498787390730432&as_sdt=2005&sciodt=0,5&hl=en",
    organization="EASST",
    cluster_id="9177498787390730432",
    scholar_ok=True,
))

dufour2006a = DB(WorkUnrelated(
    2006, "Shed skin: An optimizing python-to-c++ compiler",
    due="Unrelated to provenance",
    display="dufour",
    authors="Dufour, Mark",
    place=Thesis,
    file="Dufour2006a.pdf",
    local="Delft University of Technology",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=12623914625877330907&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="12623914625877330907",
    scholar_ok=True,
))

foster2006a = DB(WorkUnrelated(
    2006, "Proceedings of the 2006 International Provenance and Annotation Workshop (IPAW 2006)",
    due="Proceedings of a conference", 
    display="foster",
    authors="Foster, Ian and Moreau, Luc",
    link="http://www.ipaw.info/ipaw06/",
    place=LNCS,
    scholar="http://scholar.google.com/scholar?cites=15304138123809826011&as_sdt=2005&sciodt=0,5&hl=en",
    volume="4145",
    publisher="Springer",
    cluster_id="15304138123809826011",
    scholar_ok=True,
))

freire2006a = DB(WorkUnrelated(
    2006, "Managing rapidly-evolving scientific workflows",
    due="Unrelated to scripts. Tracks the evolution of workflows",
    may_be_related_to=["evolution", "workflow"],
    display="vistrails",
    authors="Freire, Juliana and Silva, Cláudio T and Callahan, Steven P and Santos, Emanuele and Scheidegger, Carlos E and Vo, Huy T",
    summary="Presents VisTrails as an approach that captures both the data provenance of trials and the provenance of the workflow (its evolution)",
    place=IPAW,
    file="Freire2006a.pdf",
    proceedings="LNCS 4145",
    pp="10--18",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6466157981083338322&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="6466157981083338322",
    scholar_ok=True,
    publisher="Springer",
    local="Chicago, IL, USA",
))

futrelle2006a = DB(WorkUnrelated(
    2006, "Harvesting RDF triples",
    due="Unrelated to scripts",
    display="futrelle",
    authors="Futrelle, Joe",
    place=IPAW,
    pp="64--72",
    proceedings="LNCS 4145",
    publisher="Springer",
    file="Futrelle2006a.pdf",
    entrytype="inproceedings",
    cluster_id="18381410181118779784",
    scholar="http://scholar.google.com/scholar?cites=18381410181118779784&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

gabor2006a = DB(WorkUnrelated(
    2006, "Exp-WF: Workflow support for laboratory information systems",
    due="Unrelated to provenance, Unrelated to scripts",
    display="gabor",
    authors="Gabor, Brian and Kemme, Bettina",
    place=ICDE,
    entrytype="inproceedings",
    file="Gabor2006a.pdf",
    cluster_id="13979392850385567257",
    scholar="http://scholar.google.com/scholar?cites=13979392850385567257&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    ID="gabor2006exp",
    pp="69--69",
    scholar_ok=True,
))

geerts2006a = DB(WorkUnrelated(
    2006, "Mondrian: Annotating and querying databases through colors and blocks",
    due="Unrelated to scripts. Tracks provenance of annotation on DB",
    may_be_related_to=["database"],
    display="geerts",
    authors="Geerts, Floris and Kementsietsidis, Anastasios and Milano, Diego",
    summary="Introduces an annotation-oriented data model for the manipulation and querying of both data and annotations",
    place=ICDE,
    file="Geerts2006a.pdf",
    pp="82--82",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=3673279137772593745&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="3673279137772593745",
    scholar_ok=True,
))

groth2006a = DB(WorkUnrelated(
    2006, "An architecture for provenance systems",
    due="excluding tech report",
    display="groth a",
    authors="Groth, Paul and Jiang, Sheng and Miles, Simon and Munroe, Steve and Tan, Victor and Tsasakou, Sofia and Moreau, Luc",
    categories=["architecture"],
    summary="Proposes an architecture for provenance systems",
    place=TechReport,
    file="Groth2006a.pdf",
    local="University of Southampton",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=15611805550743381076&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="University of Southampton",
    cluster_id="15611805550743381076",
    scholar_ok=True,
))

groth2006b = DB(WorkUnrelated(
    2006, "Process Documentation Recording Protocol",
    due="excluding tech report",
    display="groth b",
    authors="Groth, Paul and Munroe, S and Tan, Victor and Jiang, Sheng and Miles, Simon and Moreau, Luc",
    categories=["storage"],
    summary="Defines a storage protocol for provenance through a web service",
    storage="Stores XML in a server",
    place=TechReport,
    file="Groth2006b.pdf",
    local="University of Southampton",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=4411100811501563795&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="University of Southampton",
    cluster_id="4411100811501563795",
    scholar_ok=True,
))

halevy2006a = DB(WorkUnrelated(
    2006, "Data integration: the teenage years",
    due="Unrelated to scripts. Unrelated to provenance",
    display="halevy",
    authors="Halevy, Alon and Rajaraman, Anand and Ordille, Joann",
    place=VLDB,
    file="Halevy2006a.pdf",
    pp="9--16",
    publisher="VLDB Endowment",
    entrytype="inproceedings",
    cluster_id="1613944391729481107",
    scholar="http://scholar.google.com/scholar?cites=1613944391729481107&as_sdt=2005&sciodt=0,5&hl=en",
    organization="VLDB Endowment",
    scholar_ok=True,
))

hart2006a = DB(WorkUnrelated(
    2006, "Optimization of multiple continuous queries over streaming satellite data",
    display="hart",
    authors="Hart, Quinn and Gertz, Michael",
    scholar="http://scholar.google.com/scholar?cites=4503358144157609485&as_sdt=2005&sciodt=0,5&hl=en",
    ID="hart2006optimization",
    organization="ACM",
    file="Hart2006a.pdf",
    entrytype="inproceedings",
    place=SIGSPATIAL,
    due="Unrelated to provenance, unrelated to scripts",
    pp="243--250",
    cluster_id="4503358144157609485",
    scholar_ok=True,
))

hegewald2006a = DB(WorkUnrelated(
    2006, "XStruct: Efficient schema extraction from multiple and large XML documents",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hegewald",
    authors="Hegewald, Jan and Naumann, Felix and Weis, Melanie",
    place=ICDE,
    file="Hegewald2006a.pdf",
    pp="81--81",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=2720725646025724339&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="2720725646025724339",
    scholar_ok=True,
))

hull2006a = DB(WorkUnrelated(
    2006, "Taverna: a tool for building and running workflows of services",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="taverna",
    authors="Hull, Duncan and Wolstencroft, Katy and Stevens, Robert and Goble, Carole and Pocock, Mathew R and Li, Peter and Oinn, Tom",
    place=NARHAD,
    link="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1538887/",
    file="Hull2006a.pdf",
    volume="34",
    pp="W729--W732",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=7852989647567763755&as_sdt=2005&sciodt=0,5&hl=en",
    number="suppl 2",
    publisher="Oxford Univ Press",
    cluster_id="7852989647567763755",
    scholar_ok=True,
))

ipaw2006a = DB(WorkUnrelated(
    2006, "Provenance and Annotation of Data",
    due="It is a conference",
    display="ipaw",
    authors="ipaw",
    place=IPAW,
    proceedings="LNCS 4145",
    link="http://www.ipaw.info/ipaw06/",
    editors="Luc Moreau and Ian Foster",
    scholar_ok="impossible",
    local="Chicago, IL, USA",
    publisher="Springer",
))

jacovi2006a = DB(WorkUnrelated(
    2006, "The chasms of CSCW: a citation graph analysis of the CSCW conference",
    due="Unrelated to scripts. Unrelated to provenance",
    display="jacovi",
    authors="Jacovi, Michal and Soroka, Vladimir and Gilboa-Freedman, Gail and Ur, Sigalit and Shahar, Elad and Marmasse, Natalia",
    place=CSCW,
    file="Jacovi2006a.pdf",
    pp="289--298",
    publisher="ACM",
    local="New York, NY, USA",
    entrytype="inproceedings",
    cluster_id="18156025911545730537",
    scholar="http://scholar.google.com/scholar?cites=18156025911545730537&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

jiang2006a = DB(WorkUnrelated(
    2006, "An architecture for provenance systems",
    due="excluding tech report",
    display="jiang",
    authors="Groth, Paul and Jiang, Sheng and Miles, Simon and Munroe, Steve and Tan, Victor and Tsasakou, Sofia and Moreau, Luc",
    place=TechReport,
    file="Jiang2006a.pdf",
    local="University of Southampton",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=15611805550743381076&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="University of Southampton",
    cluster_id="15611805550743381076",
    scholar_ok=True,
))

konish2006a = DB(WorkUnrelated(
    2006, "The Linux implementation of a log-structured file system",
    due="Unrelated to provenance, unrelated to scripts. May be used to capture provenance of files",
    may_be_related_to=["evolution"],
    display="konish",
    authors="Konishi, Ryusuke and Amagai, Yoshiji and Sato, Koji and Hifumi, Hisashi and Kihara, Seiji and Moriai, Satoshi",
    summary="Proposes a log-structured file system (NIFLS) that is able to preserve all versions of files",
    place=OSR,
    file="Konish2006a.pdf",
    volume="40",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=7345068540120051551&as_sdt=2005&sciodt=0,5&hl=en",
    number="3",
    pp="102--107",
    publisher="ACM",
    cluster_id="7345068540120051551",
    scholar_ok=True,
    month="July",
))

langtangen2006a = DB(WorkUnrelated(
    2006, "Python scripting for computational science",
    alias=(2009, "Python Scripting for Computational Science"),
    due="Unrelated to provenance",
    star2="popularity of scripts has been growing due their simple syntax, easiness to visualize results and easiness to combine different tools",
    authors="Langtangen, Hans Petter",
    place=Book,
    file="Langtangen2006a.pdf",
    publisher="Springer",
    local="Berlin, Heidelberg and New York",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=15298161440096723046&as_sdt=2005&sciodt=0,5&hl=en",
    volume="3",
    cluster_id="15298161440096723046",
    scholar_ok=True,
    edition="3rd",
))

leoni2006a = DB(WorkUnrelated(
    2006, "On workflow equivalence and formal modeling by using π -calculus",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="leoni",
    authors="M. de Leoni",
    place=TechReport,
    local="Universita di Roma La Sapienza",
    file="Leoni2006a.pdf",
    entrytype="article",
    scholar="https://scholar.google.com.br/scholar?cites=8306869932728963098&as_sdt=2005&sciodt=0,5&hl=pt-BR",
    cluster_id="8306869932728963098",
    scholar_ok=True,

))

liu2006a = DB(WorkUnrelated(
    2006, "GPLAG: detection of software plagiarism by program dependence graph analysis",
    due="Unrelated to provenance. Program dependence graphs could be used",
    may_be_related_to=["plagiarism detection"],
    display="liu",
    authors="Liu, Chao and Chen, Chen and Han, Jiawei and Yu, Philip S",
    place=KDD,
    file="Liu2006a.pdf",
    pp="872--881",
    publisher="ACM Press",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=13966938348376734037&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="13966938348376734037",
    scholar_ok=True,
))

ludascher2006a = DB(WorkUnrelated(
    2006, "Scientific workflow management and the Kepler system",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="kepler",
    authors="Ludäscher, Bertram and Altintas, Ilkay and Berkley, Chad and Higgins, Dan and Jaeger, Efrat and Jones, Matthew and Lee, Edward A and Tao, Jing and Zhao, Yang",
    place=CCPE,
    file="Ludascher2006a.pdf",
    volume="18",
    number="10",
    pp="1039--1065",
    doi="10.1002/cpe.994",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=12184448208352068070&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Wiley Online Library",
    cluster_id="12184448208352068070",
    scholar_ok=True,
))

malhotra2006a = DB(WorkUnrelated(
    2006, "XQuery 1.0 and XPath 2.0 functions and operators",
    due="Unrelated to provenance, unrelated to scripts",
    display="xquery",
    authors="Malhotra, Ashok and Melton, Jim and Walsh, Norman",
    summary="Specification of XQuery and XPath operators",
    place=W3C,
    link="http://www.w3.org/TR/xquery-operators",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=1890648806796497476&as_sdt=2005&sciodt=0,5&hl=en",
    volume="2",
    cluster_id="1890648806796497476",
    scholar_ok=True,
))

mccamant2006a = DB(WorkUnrelated(
    2006, "Quantitative information-flow tracking for C and related languages",
    due="Excluding TechReport",
    display="mccamant",
    authors="McCamant, Stephen and Ernst, Michael D",
    place=TechReport,
    file="McCamant2006a.pdf",
    number="MIT-CSAIL-TR-2006-076",
    local="MIT, Cambridge, MA, USA",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=6221900586699442464&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6221900586699442464",
    scholar_ok=True,
))

mccullough2006a = DB(WorkUnrelated(
    2006, "Lessons from the JMCB Archive",
    due="Unrelated to scripts. Unrelated to provenance",
    display="mccullough",
    authors="McCullough, Bruce D and McGeary, Kerry Anne and Harrison, Teresa D",
    place=JMCB,
    number="4",
    volume="38",
    month="June",
    pp="1093--1107",
    file="Mccullough2006a.pdf",
    link="http://muse.jhu.edu/article/199430/pdf",
    entrytype="article",
    cluster_id="17907188836997058766",
    publisher="The Ohio State University Press",
    scholar="http://scholar.google.com/scholar?cites=17907188836997058766&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

mcphillips2006a = DB(WorkUnrelated(
    2006, "Collection-oriented scientific workflows for integrating and analyzing biological data",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="kepler",
    authors="McPhillips, Timothy and Bowers, Shawn and Ludäscher, Bertram",
    place=DILS,
    file="McPhillips2006a.pdf",
    pp="248--263",
    proceedings="LNCS 4075",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=14508695785521929726&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="14508695785521929726",
    scholar_ok=True,
    publisher="Springer",
))

miles2006a = DB(WorkUnrelated(
    2006, "Provenance Query Protocol",
    due="excluding tech report",
    display="miles a",
    authors="Miles, Simon and Moreau, Luc and Groth, Paul and Tan, Victor and Munroe, Steve and Jiang, Sheng",
    categories=["query"],
    summary="Defines a protocol for querying provenance", 
    query="Communication of SOAP messages between an actor and the provenance storage",
    place=TechReport,
    file="Miles2006a.pdf",
    local="University of Southampton",
    scholar="https://scholar.google.com/scholar?cites=7362105506912304589&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7362105506912304589",
    scholar_ok="impossible",
))

miles2006b = DB(WorkUnrelated(
    2006, "XPath Profile for the Provenance Query Protocol",
    due="excluding tech report",
    display="miles b",
    authors="Miles, Simon and Moreau, Luc and Groth, Paul and Tan, Victor and Munroe, Steve and Jiang, Sheng",
    categories=["query"],
    summary="Uses XPath to query provenance",
    query="XPath",
    place=TechReport,
    file="Miles2006b.pdf",
    local="University of Southampton",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=5248830785729928423&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="University of Southampton",
    cluster_id="5248830785729928423",
    scholar_ok=True,
))

miller2006a = DB(WorkUnrelated(
    2006, "A Scientists Nightmare: Software Problem Leads to Five Retractions",
    due="Unrelated to provenance",
    display="miller",
    authors="Miller, Greg",
    place=Science,
    volume="314",
    file="Miller2006a.pdf",
    number="5807",
    pp="1856--1857",
    doi="10.1126/science.314.5807.1856",
    month="December",
    link="http://www.ligo-wa.caltech.edu/~michael.landry/calibration/S5/getsignright.pdf",
    entrytype="article",
    cluster_id="4462524159779440254",
    publisher="American Association for the Advancement of Science",
    scholar="http://scholar.google.com/scholar?cites=4462524159779440254&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

miller2006b = DB(WorkUnrelated(
    2006, "Translating keyword commands into executable code",
    due="Unrelated to provenance",
    display="miller",
    authors="Little, Greg and Miller, Robert C",
    place=UIST,
    file="Miller2006b.pdf",
    pp="135--144",
    entrytype="inproceedings",
    cluster_id="16655677906881835967",
    scholar="http://scholar.google.com/scholar?cites=16655677906881835967&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

millman2006a = DB(WorkNoFile(
    2006, "Data and Analysis Management for Functional Magnetic Resonance Imaging Studies",
    display="millman",
    authors="Millman, K Jarrod and D'Esposito, Mark",
    organization="US Education Service",
    place=IADC,
    cluster_id="6214504685831312923",
    ID="millman2006data",
    pp="24--28",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6214504685831312923&as_sdt=2005&sciodt=0,5&hl=en",
    request="done",
    scholar_ok=True,
))

muniswamy2006a = DB(WorkBinarySnowball(
    2006, "Provenance-Aware Storage Systems",
    star="[management][xx] talks about provenance in VCS, presents usages of provenance for detecting system dependencies, intrusion detection, detecting system changes, build debugging. Also discusses where to store provenance (inside a data file, separate, separate with tight coupling)",
    display="pass",
    authors="Muniswamy-Reddy, Kiran-Kumar and Holland, David A and Braun, Uri and Seltzer, Margo I",
    summary="""
        Colects the complete provenance of an item in the storage system.
        Use the storage system because provenance is just metadata and the storage system manage meta-data.
        Also proposes mechanism for managing and querying the provenance
    """,
    define={
        "opaque provenance": "provenance that the system never sees, such as data originated from another system that is not provenance-aware",
    },
    place=ATC,
    local="Boston, USA",
    file="Muniswamy2006a.pdf",
    pp="43--56",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12181619828853480684&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="12181619828853480684",
    scholar_ok=True,
    publisher="USENIX Association",
))

muniswamy2006b = DB(WorkUnrelated(
    2006, "Deciding how to store provenance",
    due="Excluding teck report",
    display="muniswamy",
    authors="Muniswamy-Reddy, Kiran-Kumar",
    summary="Discusses forms of storage of provenance",
    place=TechReport,
    file="Muniswamy2006b.pdf",
    number="TR-03-06",
    local="Harvard University",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11498488119553153438&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11498488119553153438",
    scholar_ok=True,
))

munroe2006a = DB(WorkUnrelated(
    2006, "A SOAP Binding For Process Documentation",
    due="excluding tech report",
    display="munroe",
    authors="Munroe, Steve and Tan, Victor and Groth, Paul and Jiang, Sheng and Miles, Simon and Moreau, Luc",
    categories=["collection"],
    summary="Describes a SOAP binding for process documentation",
    collection="Library",
    place=TechReport,
    file="Munroe2006a.pdf",
    local="University of Southampton",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=5324509248092523530&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="University of Southampton",
    cluster_id="5324509248092523530",
    scholar_ok=True,
))

myers2006a = DB(WorkUnrelated(
    2006, "Invited research overview: end-user programming",
    due="Unrelated to scripts. Unrelated to provenance",
    display="myers",
    authors="Myers, Brad A and Ko, Andrew J and Burnett, Margaret M",
    place=CHI,
    file="Myers2006a.pdf",
    pp="75--80",
    entrytype="inproceedings",
    cluster_id="8915762618223066671",
    scholar="http://scholar.google.com/scholar?cites=8915762618223066671&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

naraynasmy2006a = DB(WorkUnrelated(
    2006, "Recording shared memory dependencies using strata",
    due="Unrelated to provenance",
    display="naraynasmy",
    authors="Narayanasamy, Satish and Pereira, Cristiano and Calder, Brad",
    place=OSR,
    file="Naraynasmy2006a.pdf",
    pp="229--240",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6623228222465390913&as_sdt=2005&sciodt=0,5&hl=en",
    number="5",
    volume="40",
    organization="ACM",
    cluster_id="6623228222465390913",
    scholar_ok=True,
))

nightingale2006a = DB(WorkUnrelated(
    2006, "Rethink the sync",
    due="Unrelated to provenance",
    display="nightingale",
    authors="E. B. Nightingale, K. Veeraragha van, P. M. Chen, and J. Flinn",
    place=OSDI,
    file="Nightingale2006a.pdf",
    pp="1--14",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7851476677702823535&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7851476677702823535",
    scholar_ok="aprox",
))

oinn2006a = DB(WorkUnrelated(
    2006, "Taverna: lessons in creating a workflow environment for the life sciences",
    due="Unrelated to script. Capture provenance from workflow",
    may_be_related_to=["workflow"],
    star="[intro] Presents an e-science life-cycle with 5 steps: discovering, assembling, executing, managing, and sharing",
    display="taverna",
    authors="Oinn, Tom and Greenwood, Mark and Addis, Matthew and Alpdemir, M Nedim and Ferris, Justin and Glover, Kevin and Goble, Carole and Goderis, Antoon and Hull, Duncan and Marvin, Darren and others",
    summary="Discusses the Taverna workflow system with lessons learnt during its development",
    file="Oinn2006a.pdf",
    place=CCPE,
    volume="18",
    number="10",
    pp="1067--1100",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9329563759117495052&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Wiley Online Library",
    cluster_id="9329563759117495052",
    scholar_ok=True,
))

peng2006a = DB(WorkUnrelated(
    2006, "Reproducible Epidemiologic Research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="peng",
    authors="Peng, Roger D and Dominici, Francesca and Zeger, Scott L",
    place=AmJEpidemiol,
    number="9",
    volume="163",
    pp="783--789",
    file="Peng2006a.pdf",
    link="https://academic.oup.com/aje/article/163/9/783/108733/Reproducible-Epidemiologic-Research",
    entrytype="article",
    cluster_id="14166264320675935930",
    publisher="Oxford Univ Press",
    scholar="http://scholar.google.com/scholar?cites=14166264320675935930&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

potti2006a = DB(WorkUnrelated(
    2006, "Genomic signatures to guide the use of chemotherapeutics",
    due="Unrelated to scripts. Unrelated to provenance",
    display="potti",
    authors="Potti, Anil and Dressman, Holly K and Bild, Andrea and Riedel, Richard F and Chan, Gina and Sayer, Robyn and Cragun, Janiel and Cottrill, Hope and Kelley, Michael J and Petersen, Rebecca and others",
    place=NatMed,
    number="11",
    volume="12",
    pp="1294--1300",
    file="Potti2006a.pdf",
    entrytype="article",
    cluster_id="14059756500058606160",
    publisher="Nature Publishing Group",
    scholar="http://scholar.google.com/scholar?cites=14059756500058606160&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

rajbhandari2006a = DB(WorkUnrelated(
    2006, "Incorporating provenance in service oriented architecture",
    due="Unrelated to scripts",
    display="rajbhandari",
    authors="Rajbhandari, Shrija and Walker, David W",
    scholar="http://scholar.google.com/scholar?cites=16254719731257503283&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    pp="33--40",
    place=NWeSP,
    file="Rajbhandari2006a.pdf",
    organization="IEEE",
    cluster_id="16254719731257503283",
    ID="rajbhandari2006incorporating",
    scholar_ok=True,
))

ram2006a = DB(WorkUnrelated(
    2006, "Understanding the semantics of data provenance to support active conceptual modeling",
    alias=(0, "Understanding the Semantics of Provenance to Support Active Conceptual Modeling"),
    due="Unrelated to scripts",
    summary="Investigates semantics of provenance and propose provenance model",
    display="ram",
    authors="Ram, Sudha and Liu, Jun",
    place=ACML,
    file="Ram2006a.pdf",
    scholar="http://scholar.google.com/scholar?cites=11228942558968851196&as_sdt=2005&sciodt=0,5&hl=en",
    ID="ram2006understanding",
    cluster_id="11228942558968851196",
    pp="17--29",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
))

reilly2006a = DB(WorkBinaryOk(
    2006, "Exploring provenance in a distributed job execution system",
    display="Condor",
    authors="Reilly, Christine F and Naughton, Jeffrey F",
    place=IPAW,
    file="Reilly2006a.pdf",
    pp="237--245",
    scholar="http://scholar.google.com/scholar?cites=9887381137947082743&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    organization="Springer",
    cluster_id="9887381137947082743",
    ID="reilly2006exploring",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

sapino2006a = DB(WorkUnrelated(
    2006, "Log-analysis based characterization of multimedia documents for effective delivery of distributed multimedia presentations",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["mining", "evolution"],
    display="sapino",
    authors="Sapino, Maria Luisa and Candan, K Sel{ç}uk and Bertolotti, Paola",
    place=DMS,
    file="Sapino2006a.pdf",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2885848555739073529&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Citeseer",
    cluster_id="2885848555739073529",
    scholar_ok=True,
))

sears2006a = DB(WorkUnrelated(
    2006, "Stasis: flexible transactional storage",
    due="Unrelated to provenance",
    display="sears",
    authors="Sears, Russell and Brewer, Eric",
    place=OSDI,
    file="Sears2006a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=1569192011751736336&as_sdt=2005&sciodt=0,5&hl=en",
    pp="29--44",
    organization="USENIX Association",
    cluster_id="1569192011751736336",
    scholar_ok=True,
))

silva2006a = DB(WorkUnrelated(
    2006, "A Proof Markup Language for Semantic Web Services",
    due="Unrelated to scripts",
    display="silva",
    authors="Da Silva, Paulo Pinheiro and McGuinness, Deborah L and Fikes, Richard",
    place=IS,
    file="Silva2006a.pdf",
    volume="31",
    number="4",
    month="June",
    pp="381--395",
    entrytype="article",
    cluster_id="13307649393104562246",
    publisher="Elsevier",
    scholar="http://scholar.google.com/scholar?cites=13307649393104562246&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

simmhan2006a = DB(WorkUnrelated(
    2006, "A framework for collecting provenance in data-centric scientific workflows",
    due="Unrelated to scripts",
    display="simmhan",
    authors="Simmhan, Yogesh L and Plale, Beth and Gannon, Dennis",
    place=ICWS,
    file="Simmhan2006a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7968490108328754788&as_sdt=2005&sciodt=0,5&hl=en",
    pp="427--436",
    organization="IEEE",
    cluster_id="7968490108328754788",
    scholar_ok=True,
))

simmhan2006b = DB(WorkUnrelated(
    2006, "Performance evaluation of the karma provenance framework for scientific workflows",
    due="Unrelated to scripts",
    display="simmhan",
    authors="Simmhan, Yogesh L and Plale, Beth and Gannon, Dennis and Marru, Suresh",
    place=IPAW,
    file="Simmhan2006b.pdf",
    pp="222--236",
    proceedings="LNCS 4145",
    publisher="Springer",
    entrytype="inproceedings",
    cluster_id="8486960072476628435",
    scholar="http://scholar.google.com/scholar?cites=8486960072476628435&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

steffen2006a = DB(WorkUnrelated(
    2006, "Model-driven development with the jABC",
    due="Unrelated to provenance",
    display="steffen",
    authors="Steffen, Bernhard and Margaria, Tiziana and Nagel, Ralf and Jörges, Sven and Kubczak, Christian",
    place=HVC,
    file="Steffen2006a.pdf",
    proceedings="LNCS 4383",
    pp="92--108",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12956120576344446278&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="12956120576344446278",
    scholar_ok=True,
))

tagger2006a = DB(WorkUnrelated(
    2006, "The EngD Second Year Report",
    due="Unrelated to scripts",
    display="tagger",
    authors="Tagger, Ben",
    place=TechReport,
    ID="tagger2006engd",
    entrytype="article",
    star="[survey]",
    file="Tagger2006a.pdf",
    scholar_ok=True,
))

tuffery2006a = DB(WorkUnrelated(
    2006, "Semantic map of services for structural bioinformatics",
    due="Unrelated to scripts. Unrelated to provenance",
    display="tuffery",
    authors="Tuffery, Pierre and Lacroix, Zoe and Menager, Herve",
    place=SSDBM,
    file="Tuffery2006a.pdf",
    pp="217--224",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=16794895306209542705&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="16794895306209542705",
    scholar_ok=True,
))

vijayakumar2006a = DB(WorkUnrelated(
    2006, "Towards low overhead provenance tracking in near real-time stream filtering",
    due="Unrelated to scripts",
    display="vijayakumar",
    authors="Vijayakumar, Nithya N and Plale, Beth",
    place=IPAW,
    file="Vijayakumar2006a.pdf",
    pp="46--54",
    proceedings="LNCS 4145",
    publisher="Springer",
    entrytype="inproceedings",
    cluster_id="9517314772760801349",
    scholar="http://scholar.google.com/scholar?cites=9517314772760801349&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
    local="Chicago, IL, USA",
))

weijters2006a = DB(WorkUnrelated(
    2006, "Process mining with the heuristics miner-algorithm",
    due="Excluding TechReports",
    display="weijters",
    authors="Weijters, AJMM and van Der Aalst, Wil MP and De Medeiros, AK Alves",
    place=TechReport,
    file="Weijters2006a.pdf",
    number="BETA Working Paper Series, WP 166",
    local="Eindhoven University of Technology, Eindhoven",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2992491406782049829&as_sdt=2005&sciodt=0,5&hl=en",
    volume="166",
    pp="1--34",
    cluster_id="2992491406782049829",
    scholar_ok=True,
))

westlake2006a = DB(WorkUnrelated(
    2006, "Provenance and Reliability: Managing Metadata for Statistical Models",
    alias=(0, "OPUS", "Westlake, Andrew and Krishnan, Rajesh"),
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="westlake",
    authors="Westlake, Andrew",
    place=SSDBM,
    file="Westlake2006a.pdf",
    pp="204--216",
    organization="IEEE",
    cluster_id="9556853695300303307",
    scholar="http://scholar.google.com/scholar?cites=9556853695300303307&as_sdt=2005&sciodt=0,5&hl=en",
    ID="westlake2006provenance",
    entrytype="inproceedings",
    scholar_ok=True,
))

winter2006a = DB(WorkUnrelated(
    2006, "Essential layers, artifacts, and dependencies of enterprise architecture",
    due="Unrelated to provenance",
    display="winter",
    authors="Winter, Robert and Fischer, Ronny",
    place=EDOCW,
    file="Winter2006a.pdf",
    volume="30",
    local="Washington, DC, USA",
    publisher="IEEE Computer Society",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=9396288004051976003&as_sdt=2005&sciodt=0,5&hl=en",
    pp="30--30",
    organization="IEEE",
    cluster_id="9396288004051976003",
    scholar_ok=True,
))

zeldovich2006a = DB(WorkUnrelated(
    2006, "Making information flow explicit in HiStar",
    due="Unrelated to provenance",
    display="zeldovich",
    authors="Zeldovich, Nickolai and Boyd-Wickizer, Silas and Kohler, Eddie and Mazières, David",
    place=OSDI,
    file="Zeldovich2006a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12573004645654120795&as_sdt=2005&sciodt=0,5&hl=en",
    pp="263--278",
    organization="USENIX Association",
    cluster_id="12573004645654120795",
    scholar_ok=True,
))

zhao2006a = DB(WorkUnrelated(
    2006, "Applying the virtual data provenance model",
    star="[collection][x] Coins the terms 'restrospective' and 'prospective'. Provides a bunch of query examples.",
    due="Unrelated to scripts. Language based on workflow graphs",
    display="zhao",
    authors="Zhao, Yong and Wilde, Michael and Foster, Ian",
    summary="Proposes a general model for querying provenance in the Virtual Data System (VDS). Separes the provenance in retrospective and prospective. Provides examples of queries for virtual data relationship, annotation, lineage and combined'",
    query="Supports SQL, XQuery/XPath",
    place=IPAW,
    local="Chicago, Illinois, USA",
    file="Zhao2006a.pdf",
    pp="148--161",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6910118999594202680&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="6910118999594202680",
    scholar_ok=True,
))

zhu2006a = DB(WorkUnrelated(
    2006, "A framework for service-oriented testing of web services",
    due="Unrelated to provenance",
    display="zhu",
    authors="Zhu, Hong",
    place=COMPSAC,
    file="Zhu2006a.pdf",
    volume="2",
    pp="145--150",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6191206370172215508&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="6191206370172215508",
    scholar_ok=True,
))
