# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


abadi2005a = DB(WorkUnrelated(
    2005, "The design of the borealis| stream processing engine",
    due="Unrelated to scripts. Unrelated to provenance",
    display="abadi",
    authors="Abadi, Daniel J and Ahmad, Yanif and Balazinska, Magdalena and Cetintemel, Ugur and Cherniack, Mitch and Hwang, Jeong-Hyon and Lindner, Wolfgang and Maskey, Anurag and Rasin, Alex and Ryvkina, Esther and others",
    place=CIDR,
    pp="277--289",
    file="Abadi2005a.pdf",
    entrytype="inproceedings",
    cluster_id="5871783799147300586",
    scholar="http://scholar.google.com/scholar?cites=5871783799147300586&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

alland2005a = DB(WorkUnrelated(
    2005, "RPBS: a web resource for structural bioinformatics",
    due="Unrelated to provenance. Unrelated to scripts",
    display="alland",
    authors="Alland, Cynthia and Moreews, Francois and Boens, D and Carpentier, Mathilde and Chiusa, S and Lonquety, Mathieu and Renault, N and Wong, Y and Cantalloube, H and Chomilier, Jacques and others",
    place=NARHAD,
    file="Alland2005a.pdf",
    volume="33",
    pp="W44--W49",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9689379700196854481&as_sdt=2005&sciodt=0,5&hl=en",
    number="suppl 2",
    publisher="Oxford Univ Press",
    cluster_id="9689379700196854481",
    scholar_ok=True,
))

alpern2005a = DB(WorkUnrelated(
    2005, "PDS: a virtual execution environment for software deployment",
    due="Unrelated to provenance",
    display="alpern",
    authors="Alpern, Bowen and Auerbach, Joshua and Bala, Vasanth and Frauenhofer, Thomas and Mummert, Todd and Pigott, Michael",
    place=VEE,
    file="Alpern2005a.pdf",
    pp="175--185",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=5202501721949077500&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="5202501721949077500",
    scholar_ok=True,
    local="New York, NY, USA",
    publisher="ACM",
))

arpad2005a = DB(WorkUnrelated(
    2005, "Architecture for Provenance Systems",
    due="Unrelated to scripts",
    display="arpad",
    authors="Arpád, Andics and Biller, Alexis and Branco, Miguel and Chen, Liming and Contes, Arnaud and Dannemann, Frank and Deora, Vikas and Hardman, Neil and Kloos, Guy and Luck, Michael and others",
    place=TechReport,
    file="Arpad2005a.pdf",
    ID="arpad2005architecture",
    entrytype="article",
    scholar_ok=True,
))

barni2005a = DB(WorkUnrelated(
    2005, "Pushing science into signal processing [my turn]",
    due="Unrelated to provenance",
    display="barni",
    authors="Barni, Mauro and Perez-Gonzalez, Fernando",
    place=SPM,
    pp="120--119",
    doi="10.1109/MSP.2005.1458324.",
    number="4",
    volume="22",
    month="July",
    file="Barni2005a.pdf",
    entrytype="article",
    cluster_id="5172942472677826209",
    publisher="IEEE",
    scholar="http://scholar.google.com/scholar?cites=5172942472677826209&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

barrett2005a = DB(WorkUnrelated(
    2005, "SSH, the Secure Shell: the definitive guide",
    due="Unrelated to provenance",
    display="barrett",
    authors="Barrett, Daniel J and Silverman, Richard E",
    place=Book,
    file="Barrett2005a.pdf",
    publisher="O'Reilly Media, Inc.",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=7623751235440943601&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7623751235440943601",
    scholar_ok=True,
))

bavoil2005a = DB(WorkUnrelated(
    2005, "Vistrails: Enabling interactive multiple-view visualizations",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="vistrails",
    authors="Bavoil, Louis and Callahan, Steven P and Crossno, Patricia J and Freire, Juliana and Scheidegger, Carlos E and Silva, Cláudio T and Vo, Huy T",
    summary="Describes the design and implementation of VisTrails",
    place=IEEE_VIS,
    file="Bavoil2005a.pdf",
    pp="135--142",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=994507953310156275&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="994507953310156275",
    scholar_ok=True,
    publisher="IEEE",
))

bellard2005a = DB(WorkUnrelated(
    2005, "QEMU, a fast and portable dynamic translator",
    due="Unrelated to provenance",
    display="bellard",
    authors="Bellard, Fabrice",
    summary="Proposes a system emulator",
    place=ATC,
    file="Bellard2005a.pdf",
    pp="41--46",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11821092615217571483&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11821092615217571483",
    scholar_ok=True,
))

bhagwat2005a = DB(WorkUnrelated(
    2005, "An annotation management system for relational databases",
    due="Unrelated to scripts. Propagates annotations of queries in databases",
    may_be_related_to=["database"],
    display="bhagwat",
    authors="Bhagwat, Deepavali and Chiticariu, Laura and Tan, Wang-Chiew and Vijayvargiya, Gaurav",
    summary="Proposes an annotation management system for relational databases",
    place=VLDB_Journal,
    file="Bhagwat2005a.pdf",
    volume="14",
    number="4",
    pp="373--396",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=1087885940890897665&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Springer",
    cluster_id="1087885940890897665",
    scholar_ok=True,
))

bose2005a = DB(WorkUnrelated(
    2005, "Lineage retrieval for scientific data processing: a survey",
    aliases=[
        (0, "Lineage Retrieval for Scientific Computing and Information Systems: A Survey", "BOSE, RAJENDRA and FREW, JAMES"),
        (0, "Lineage Retrieval for Scientific Data Processing and Information Systems: A Survey", "BOSE, RAJENDRA and FREW, JAMES")
    ],
    due="The only approach that captures provenance from scripts here is ESSW",
    star="[survey]",
    display="bose",
    authors="Bose, Rajendra and Frew, James",
    summary="Surveys provenance in scientific data processing. Describes a metamodel for provenance, distinguishes approches in script based, service based, query-based, wfms-bases and command line based. Relates provenance research to workflow research, version control research and version management research",
    place=CSUR,
    file="Bose2005a.pdf",
    volume="37",
    number="1",
    pp="1--28",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=10437213927688415132&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="10437213927688415132",
    scholar_ok=True,
    month="March",
    doi="10.1145/1057977.1057978",
))

bright2005a = DB(WorkUnrelated(
    2005, "Deriving and Managing Data Products in an Environmental Observation and Forecasting System",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    summary="Models scripts as workflows",
    display="bright",
    authors="Bright, Laura and Maier, David",
    scholar="http://scholar.google.com/scholar?cites=9988066261794732230&as_sdt=2005&sciodt=0,5&hl=en",
    ID="bright2005deriving",
    place=CIDR,
    pp="162--173",
    cluster_id="9988066261794732230",
    file="Bright2005a.pdf",
    entrytype="inproceedings",
    scholar_ok=True,
))

buyya2005a = DB(WorkUnrelated(
    2005, "A taxonomy of workflow management systems for grid computing",
    due="Unrelated to scripts",
    display="buyya",
    authors="Yu, Jia and Buyya, Rajkumar",
    place=JGCOAP,
    number="3--4",
    file="Buyya2005a.pdf",
    volume="3",
    pp="171--200",
    entrytype="article",
    cluster_id="10536470094197216392",
    publisher="Springer",
    scholar="http://scholar.google.com/scholar?cites=10536470094197216392&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

cao2005a = DB(WorkUnrelated(
    2005, "Lineage file system",
    due="Excluding Tech Reports",
    display="LinFS",
    authors="Sar, Can and Cao, Pei",
    summary="According to MuniswamyReddy2006, LinFS is a ﬁle system that automatically tracks provenance at the ﬁle system level, focusing on executables, command lines and input ﬁles as the only source of provenance, ignoring the hardware and software environment in which such processes run. Performs provenance collection at user-level, writing it to an external database",
    place=TechReport,
    file="Cao2005a.ps",
    link="http://crypto.stanford.edu/~cao/lineage.html",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2008945885350536897&as_sdt=2005&sciodt=0,5&hl=en",
    pp="411--414",
    cluster_id="2008945885350536897",
    scholar_ok=True,
))

carroll2005a = DB(WorkUnrelated(
    2005, "Named Graphs, Provenance, and Trust",
    due="Unrelated to scripts",
    display="carroll",
    authors="Carroll, Jeremy J and Bizer, Christian and Hayes, Pat and Stickler, Patrick",
    place=WebSemantics,
    number="4",
    volume="3",
    file="Carroll2005a.pdf",
    entrytype="article",
    cluster_id="2474826138119368542",
    scholar="http://scholar.google.com/scholar?cites=2474826138119368542&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok="aprox",
))

cavalcanti2005a = DB(WorkUnrelated(
    2005, "Managing structural genomic workflows using web services",
    due="Unrelated to provenance. Unrelated to scripts",
    display="cavalcanti",
    authors="Cavalcanti, Maria Cláudia and Targino, Rafael and Baião, Fernanda and Rössle, Shaila C and Bisch, Paulo M and Pires, Paulo F and Campos, Maria Luiza M and Mattoso, Marta",
    place=DKE,
    file="Cavalcanti2005a.pdf",
    publisher="Elsevier",
    volume="53",
    cluster_id="12300305928582775456",
    ID="cavalcanti2005managing",
    scholar="http://scholar.google.com/scholar?cites=12300305928582775456&as_sdt=2005&sciodt=0,5&hl=en",
    number="1",
    entrytype="article",
    pp="45--74",
    scholar_ok=True,
))

chanda2005a = DB(WorkUnrelated(
    2005, "Causeway: Operating System Support for Controlling and Analyzing the Execution of Distributed Programs",
    due="Unrelated to provenance",
    display="chanda",
    authors="Chanda, Anupam and Elmeleegy, Khaled and Cox, Alan L and Zwaenepoel, Willy",
    place=HotOS,
    file="Chanda2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7266287036109289073&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7266287036109289073",
    scholar_ok=True,
))

chiticariu2005a = DB(WorkUnrelated(
    2005, "DBNotes: a post-it system for relational databases based on provenance",
    due="Unrelated to scripts",
    display="chiticariu",
    authors="Chiticariu, Laura and Tan, Wang-Chiew and Vijayvargiya, Gaurav",
    place=SIGMOD,
    pp="942--944",
    publisher="ACM",
    file="Chiticariu2005a.pdf",
    entrytype="inproceedings",
    cluster_id="40128465713350894",
    scholar="http://scholar.google.com/scholar?cites=40128465713350894&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

deelman2005a = DB(WorkUnrelated(
    2005, "Pegasus: A framework for mapping complex scientific workflows onto distributed systems",
    due="Unrelated to scripts",
    display="deelman",
    authors="Deelman, Ewa and Singh, Gurmeet and Su, Mei-Hui and Blythe, James and Gil, Yolanda and Kesselman, Carl and Mehta, Gaurang and Vahi, Karan and Berriman, G Bruce and Good, John and others",
    place=SP,
    number="3",
    file="Deelman2005a.pdf",
    volume="13",
    pp="219--237",
    entrytype="article",
    cluster_id="13947877656654836989",
    publisher="Hindawi Publishing Corporation",
    scholar="http://scholar.google.com/scholar?cites=13947877656654836989&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

dongen2005a = DB(WorkUnrelated(
    2005, "A Meta Model for Process Mining Data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="dongen",
    authors="van Dongen, Boudewijn F and Van der Aalst, Wil MP",
    place=TechReport,
    local="EMOI-INTEROP",
    file="Dongen2005a.pdf",
    number="160",
    entrytype="article",
    cluster_id="6514652211157866063",
    volume="160",
    scholar="http://scholar.google.com/scholar?cites=6514652211157866063&as_sdt=2005&sciodt=0,5&hl=en",
    pp="30",
    scholar_ok="check all versions",
))

dongen2005b = DB(WorkUnrelated(
    2005, "The ProM framework: A new era in process mining tool support",
    due="Unrelated to scripts. Unrelated to provenance",
    display="dongen",
    authors="Van Dongen, Boudewijn F and de Medeiros, Ana Karla A and Verbeek, HMW and Weijters, AJMM and Van Der Aalst, Wil MP",
    place=PETRI_NETS,
    file="Dongen2005b.pdf",
    proceedings="LNCS 3536",
    pp="444--454",
    publisher="Springer",
    entrytype="inproceedings",
    cluster_id="15249448880347627158",
    scholar="http://scholar.google.com/scholar?cites=15249448880347627158&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
))

efstathopoulos2005a = DB(WorkUnrelated(
    2005, "Labels and event processes in the Asbestos operating system",
    due="Unrelated to provenance",
    display="efstathopoulos",
    authors="Efstathopoulos, Petros and Krohn, Maxwell and VanDeBogart, Steve and Frey, Cliff and Ziegler, David and Kohler, Eddie and Mazieres, David and Kaashoek, Frans and Morris, Robert",
    place=SOSP,
    file="Efstathopoulos2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=14937596709625421783&as_sdt=2005&sciodt=0,5&hl=en",
    number="5",
    volume="39",
    pp="17--30",
    cluster_id="14937596709625421783",
    organization="ACM",
    scholar_ok=True,
))

fisher2005a = DB(WorkUnrelated(
    2005, "PADS: a domain-specific language for processing ad hoc data",
    due="Unrelated to provenance. Unrelated to scripts",
    display="fisher",
    authors="Fisher, Kathleen and Gruber, Robert",
    place=PLDI,
    file="Fisher2005a.pdf",
    pp="295--304",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=5254006938752005012&as_sdt=2005&sciodt=0,5&hl=en",
    number="6",
    volume="40",
    organization="ACM",
    cluster_id="5254006938752005012",
    scholar_ok=True,
    publisher="ACM",
))

frigo2005a = DB(WorkUnrelated(
    2005, "The design and implementation of FFTW3",
    due="Unrelated to provenance, unrelated to scripts",
    display="frigo",
    authors="Frigo, Matteo and Johnson, Steven G",
    summary="Presents a flexible and adaptative version of the discrete Fourier transform (DFT) algorithm",
    place=IEEE,
    file="Frigo2005a.pdf",
    volume="93",
    number="2",
    pp="216--231",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=15063750698619285626&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="IEEE",
    cluster_id="15063750698619285626",
    scholar_ok=True,
))

gentleman2005a = DB(WorkUnrelated(
    2005, "Reproducible research: A bioinformatics case study",
    due="Unrelated to provenance. The idea of a 'Compendium' that includes both text and results is more related to literate programming",
    may_be_related_to=["reproducibility"],
    star="[collection][x] Talk about literate programming",
    display="Sweave",
    authors="Gentleman, Robert and others",
    summary="Creates a compendium with code and results that allows users to verify if the same results are being generated",
    place=SAGMB,
    file="Gentleman2005a.pdf",
    volume="4",
    number="1",
    article="2",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=10140988216876365681&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1034",
    cluster_id="10140988216876365681",
    scholar_ok=True,
))

giardine2005a = DB(WorkUnrelated(
    2005, "Galaxy: a platform for interactive large-scale genome analysis",
    due="Unrelated to scripts",
    display="giardine",
    authors="Giardine, Belinda and Riemer, Cathy and Hardison, Ross C and Burhans, Richard and Elnitski, Laura and Shah, Prachi and Zhang, Yi and Blankenberg, Daniel and Albert, Istvan and Taylor, James and others",
    place=GS,
    number="10",
    file="Giardine2005a.pdf",
    volume="15",
    link="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1240089/",
    pp="1451--1455",
    entrytype="article",
    cluster_id="8864384697314093825",
    publisher="Cold Spring Harbor Lab",
    scholar="http://scholar.google.com/scholar?cites=8864384697314093825&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

goel2005a = DB(WorkUnrelated(
    2005, "The taser intrusion recovery system",
    due="Unrelated to provenance",
    display="goel",
    authors="Goel, Ashvin and Po, Kenneth and Farhadi, Kamran and Li, Zheng and De Lara, Eyal",
    place=OSR,
    file="Goel2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=14182340438327277864&as_sdt=2005&sciodt=0,5&hl=en",
    number="5",
    volume="39",
    pp="163--176",
    cluster_id="14182340438327277864",
    organization="ACM",
    scholar_ok=True,
))

groth2005a = DB(WorkUnrelated(
    2005, "Recording and using provenance in a protein compressibility experiment",
    star="[related_work] Provenance from java",
    due="Unrelated to scripts",
    display="groth",
    authors="Groth, Paul and Miles, Simon and Fang, Weijian and Wong, Sylvia C and Zauner, K-P and Moreau, Luc",
    summary="Presents provenance use case, challenges on capturing provenance, and proposes library to store and query provenance in Java programs",
    place=HPDC,
    file="Groth2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=10887936681281616864&as_sdt=2005&sciodt=0,5&hl=en",
    pp="201--208",
    organization="IEEE",
    cluster_id="10887936681281616864",
    scholar_ok=True,
    publisher="IEEE",
))

groth2005b = DB(WorkUnrelated(
    2005, "A mini-thesis submitted for transfer from MPhil to PhD",
    due="Excluding techreport. Unrelated to scripts",
    display="groth",
    authors="Groth, Paul T",
    place=TechReport,
    file="Groth2005b.pdf",
    ID="groth2005mini",
    entrytype="phdthesis",
    local="UNIVERSITY OF SOUTHAMPTON",
    school="University of Southampton",
    scholar_ok=True,
))

groth2005c = DB(WorkUnrelated(
    2005, "A nine month progress report",
    due="Excluding TechReport",
    display="groth",
    authors="Groth, Paul T",
    place=TechReport,
    file="Groth2005c.pdf",
    ID="groth2005nine",
    entrytype="article",
    scholar_ok="impossible",
))

groth2005d = DB(WorkUnrelated(
    2005, "PReServ: Provenance recording for services",
    due="Unrelated to scripts",
    may_be_related_to=["prog", "java"],
    display="groth",
    authors="Groth, Paul and Miles, Simon and Moreau, Luc",
    place=AHM,
    file="Groth2005d.pdf",
    entrytype="inproceedings",
    cluster_id="2202667139049520739",
    volume="2005",
    scholar="http://scholar.google.com/scholar?cites=2202667139049520739&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

halcrow2005a = DB(WorkUnrelated(
    2005, "eCryptfs: An enterprise-class encrypted filesystem for linux",
    due="Unrelated to provenance",
    display="halcrow",
    authors="Halcrow, Michael Austin",
    place=OLS,
    file="Halcrow2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=8678404896533771853&as_sdt=2005&sciodt=0,5&hl=en",
    volume="1",
    pp="201--218",
    cluster_id="8678404896533771853",
    scholar_ok=True,
))

ioannidis2005a = DB(WorkUnrelated(
    2005, "Why most published research findings are false",
    due="Unrelated to provenance, unrelated to scripts",
    star="[repro][x] Presents unreproducible research",
    display="ioannidis",
    authors="Ioannidis, John PA",
    summary="Discusses why most research findings are false based on a definition of bias as the combination of various design, data, analysis, and presentation factors",
    place=PLOSMed,
    file="Ioannidis2005a.pdf",
    volume="2",
    number="8",
    pp="e124",
    doi="10.1371/ journal.pmed.0020124",
    link="http://www.ncbi.nlm.nih.gov/pubmed/16060722",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=15681017780418799273&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Public Library of Science",
    cluster_id="15681017780418799273",
    scholar_ok=True,
))

ioannidis2005b = DB(WorkUnrelated(
    2005, "Contradicted and initially stronger effects in highly cited clinical research",
    due="Unrelated to scripts",
    display="ioannidis",
    authors="Ioannidis, John PA",
    place=JAMA,
    number="2",
    volume="294",
    pp="218--228",
    file="Ioannidis2005b.pdf",
    entrytype="article",
    cluster_id="3141008409154753891",
    publisher="American Medical Association",
    scholar="http://scholar.google.com/scholar?cites=3141008409154753891&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

ives2005a = DB(WorkUnrelated(
    2005, "ORCHESTRA: Rapid, Collaborative Sharing of Dynamic Data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="ives",
    authors="Ives, Zachary G and Khandelwal, Nitin and Kapur, Aneesh and Cakir, Murat",
    place=CIDR,
    file="Ives2005a.pdf",
    pp="107--118",
    entrytype="inproceedings",
    cluster_id="11688008453170340539",
    scholar="http://scholar.google.com/scholar?cites=11688008453170340539&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

jiang2005a = DB(WorkUnrelated(
    2005, "Client side library",
    due="Non paper format",
    display="jiang",
    authors="Jiang, Sheng and Groth, Paul and Miles, Simon and Tan, Victor and Munroe, Steve and Tsasakou, Sofia and Moreau, Luc",
    place=TechReport,
    file="Jiang2005a.pdf",
    local="University of Southampton",
    scholar_ok="impossible",
))

kihlen2005a = DB(WorkUnrelated(
    2005, "Electronic lab notebooks -- do they work in reality?",
    due="Unrelated to provenance",
    display="kihlen",
    authors="Kihlén, Mats",
    place=DDT,
    file="Kihlen2005a.pdf",
    pp="1205--1207",
    number="18",
    volume="10",
    entrytype="article",
    cluster_id="3699817010853572923",
    publisher="Elsevier",
    scholar="http://scholar.google.com/scholar?cites=3699817010853572923&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

king2005a = DB(WorkBinaryOk(
    2005, "Debugging operating systems with time-traveling virtual machines",
    display="king",
    authors="King, Samuel T and Dunlap, George W and Chen, Peter M",
    place=ATC,
    file="King2005a.pdf",
    publisher="USENIX Association",
    entrytype="inproceedings",
    cluster_id="17348178724180937201",
    scholar="http://scholar.google.com/scholar?cites=17348178724180937201&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1--1",
    scholar_ok=True,
))

ko2005a = DB(WorkUnrelated(
    2005, "Design requirements for more flexible structured editors from a study of programmers' text editing",
    due="Unrelated to provenance",
    display="ko",
    authors="Ko, Andrew J and Aung, Htet Htet and Myers, Brad A",
    place=CHI,
    publisher="ACM",
    pp="1557--1560",
    file="Ko2005a.pdf",
    entrytype="inproceedings",
    cluster_id="5424331348769753371",
    scholar="http://scholar.google.com/scholar?cites=5424331348769753371&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

ledlie2005a = DB(WorkUnrelated(
    2005, "Provenance-aware sensor data storage",
    due="Unrelated to scripts",
    display="ledlie",
    authors="Ledlie, Jonathan and Ng, Chaki and Holland, David A",
    place=NetDB,
    file="Ledlie2005a.pdf",
    entrytype="inproceedings",
    cluster_id="3180979165240065884",
    scholar="http://scholar.google.com/scholar?cites=3180979165240065884&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1189--1189",
    organization="IEEE",
    scholar_ok=True,
))

li2005a = DB(WorkUnrelated(
    2005, "Fine-granularity access control in 3-tier laboratory information systems",
    due="Unrelated to provenance",
    display="li",
    authors="Li, Xueli and Naeem, Nomair A and Kemme, Bettina",
    place=IDEAS,
    file="Li2005a.pdf",
    pp="391--397",
    scholar="http://scholar.google.com/scholar?cites=1672813708796570612&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    organization="IEEE",
    cluster_id="1672813708796570612",
    ID="li2005fine",
    scholar_ok=True,
))

luk2005a = DB(WorkUnrelated(
    2005, "Pin: building customized program analysis tools with dynamic instrumentation",
    star="[collection][xx] dynamic instrumentation",
    due="Unrelated to provenance. May me used as a technique to collect provenance though",
    display="luk",
    authors="Luk, Chi-Keung and Cohn, Robert and Muth, Robert and Patil, Harish and Klauser, Artur and Lowney, Geoff and Wallace, Steven and Reddi, Vijay Janapa and Hazelwood, Kim",
    place=PLDI,
    file="Luk2005a.pdf",
    local="Chicago, IL, USA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=15305535231300712107&as_sdt=2005&sciodt=0,5&hl=en",
    number="6",
    volume="40",
    pp="190--200",
    cluster_id="15305535231300712107",
    organization="ACM",
    scholar_ok=True,
))

margaria2005a = DB(WorkUnrelated(
    2005, "Web services-based tool-integration in the ETI platform",
    due="Unrelated to provenance",
    display="margaria",
    authors="Margaria, Tiziana",
    place=SoSyM,
    file="Margaria2005a.pdf",
    volume="4",
    number="2",
    pp="141--156",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=17909528197135623905&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Springer",
    cluster_id="17909528197135623905",
    scholar_ok=True,
))

maritorena2005a = DB(WorkUnrelated(
    2005, "Consistent merging of satellite ocean color data sets using a bio-optical model",
    due="Unrelated to provenance, unrelated to scripts. It was used as an example of scientist reluctant to assume the burdens of operationa data publication on es3",
    star="Example of why automatic tools are necessary",
    display="maritorena",
    authors="Maritorena, Stéphane and Siegel, David A",
    summary="Work about ocean color satellite",
    place=RSE,
    file="Maritorena2005a.pdf",
    volume="94",
    number="4",
    doi="10.1016/j.rse.2004.08.014",
    pp="429--440",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=4283471374743785963&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Elsevier",
    cluster_id="4283471374743785963",
    scholar_ok=True,
))

mcphillips2005a = DB(WorkUnrelated(
    2005, "An approach for pipelining nested collections in scientific workflows",
    due="Unrelated to scripts",
    display="mcphillips",
    authors="McPhillips, Timothy M and Bowers, Shawn",
    place=SIGMOD_REC,
    file="McPhillips2005a.pdf",
    volume="34",
    number="3",
    pp="12--17",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11982077198067106318&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="11982077198067106318",
    scholar_ok=True,
))

medeiros2005a = DB(WorkUnrelated(
    2005, "WOODSS and the Web: annotating and reusing scientific workflows",
    due="Unrelated to scripts",
    may_be_related_to=["workflow", "annotations"],
    display="medeiros",
    authors="Medeiros, Claudia Bauzer and Perez-Alcazar, J and Digiampietri, L and Pastorello Jr, Gilberto Zonta and Santanche, André and Torres, RS and Madeira, E and Bacarin, Evandro",
    place=SIGMOD_REC,
    file="Medeiros2005a.pdf",
    volume="34",
    number="3",
    pp="18--23",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=659912332443406456&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="659912332443406456",
    scholar_ok=True,
))

mernik2005a = DB(WorkUnrelated(
    2005, "When and how to develop domain-specific languages",
    due="Unrelated to provenance",
    display="mernik",
    authors="Mernik, Marjan and Heering, Jan and Sloane, Anthony M",
    place=CSUR,
    file="Mernik2005a.pdf",
    pp="316--344",
    number="4",
    volume="37",
    entrytype="article",
    cluster_id="8598236436890577027",
    publisher="ACM",
    scholar="http://scholar.google.com/scholar?cites=8598236436890577027&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

newsome2005a = DB(WorkUnrelated(
    2005, "Dynamic taint analysis for automatic detection, analysis, and signature generation of exploits on commodity software",
    due="Unrelated to provenance",
    display="newsome",
    authors="Newsome, James and Song, Dawn",
    place=NDSS,
    file="Newsome2005a.pdf",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9428084648194964145&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Internet Society",
    cluster_id="9428084648194964145",
    scholar_ok=True,
))

nielson2005a = DB(WorkUnrelated(
    2005, "Principles of program analysis",
    due="Unrelated to provenance. Some analysis techniques may be useful for capturing provenance",
    display="nielson",
    authors="Nielson, Flemming and Nielson, Hanne R and Hankin, Chris",
    summary="According to the abstract, it talks about compilers, software validation, data representation",
    publisher="Springer",
    edition="Second",
    place=Book,
    link="http://www.imm.dtu.dk/~hrni/PPA/ppasup2004.html",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=9939417718175540516&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="9939417718175540516",
    scholar_ok=True,
))

oliveira2005a = DB(WorkUnrelated(
    2005, "Odyssey-VCS: a flexible version control system for UML model elements",
    due="Unrelated to scripts. Unrelated to provenance",
    display="oliveira",
    authors="Oliveira, Hamilton and Murta, Leonardo and Werner, Cláudia",
    place=SCM,
    pp="1--16",
    publisher="ACM",
    file="Oliveira2005a.pdf",
    local="New York, NY, USA",
    entrytype="inproceedings",
    cluster_id="1927283680367868699",
    scholar="http://scholar.google.com/scholar?cites=1927283680367868699&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

petersen2005a = DB(WorkUnrelated(
    2005, "Ext3cow: a time-shifting file system for regulatory compliance",
    due="Unrelated to provenance",
    display="petersen",
    authors="Peterson, Zachary and Burns, Randal",
    place=TOS,
    file="Petersen2005a.pdf",
    volume="1",
    number="2",
    pp="190--212",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=17740554633112082994&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="17740554633112082994",
    scholar_ok=True,
))

pike2005a = DB(WorkUnrelated(
    2005, "Interpreting the data: Parallel analysis with Sawzall",
    due="Unrelated to provenance",
    display="pike",
    authors="Pike, Rob and Dorward, Sean and Griesemer, Robert and Quinlan, Sean",
    place=SP,
    file="Pike2005a.pdf",
    pp="277--298",
    number="4",
    volume="13",
    entrytype="article",
    cluster_id="15479040744494015743",
    publisher="Hindawi Publishing Corporation",
    scholar="http://scholar.google.com/scholar?cites=15479040744494015743&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

ram2005a = DB(WorkUnrelated(
    2005, "Investigating Data Provenance in the Context of New Product Design and Development",
    due="Non paper format",
    display="ram",
    authors="Ram, Sudha",
    place=DG_O,
    link="https://www.nsf.gov/awardsearch/showAward?AWD_ID=0455993",
    ID="ram2005investigating",
    entrytype="inproceedings",
    cluster_id="17492146654140191216",
    scholar="http://scholar.google.com/scholar?cites=17492146654140191216&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

resnick2005a = DB(WorkUnrelated(
    2005, "Design principles for tools to support creative thinking",
    due="Unrelated to provenance",
    display="resnick",
    authors="Resnick, Mitchel and Myers, Brad and Nakakoji, Kumiyo and Shneiderman, Ben and Pausch, Randy and Selker, Ted and Eisenberg, Mike",
    place=Book,
    file="Resnick2005a.pdf",
    entrytype="article",
    cluster_id="15588037874200835377",
    scholar="http://scholar.google.com/scholar?cites=15588037874200835377&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

robbes2005a = DB(WorkUnrelated(
    2005, "Versioning systems for evolution research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="robbes",
    authors="Robbes, Romain and Lanza, Michele",
    place=IWPSE,
    link="http://portal.acm.org/citation.cfm?id=1107840.1108157",
    pp="155--164",
    publisher="IEEE Computer Society",
    file="Robbes2005a.pdf",
    local="Washington, DC, USA",
    entrytype="inproceedings",
    cluster_id="15819184962120918740",
    scholar="http://scholar.google.com/scholar?cites=15819184962120918740&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    scholar_ok=True,
))

saito2005a = DB(WorkUnrelated(
    2005, "Jockey: a user-space library for record-replay debugging",
    due="Unrelated to scripts. Unrelated to provenance",
    display="saito",
    authors="Saito, Yasushi",
    place=AADEBUG,
    file="Saito2005a.pdf",
    pp="69--76",
    publisher="ACM Press",
    entrytype="inproceedings",
    cluster_id="11275116539554891973",
    scholar="http://scholar.google.com/scholar?cites=11275116539554891973&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

salcianu2005a = DB(WorkUnrelated(
    2005, "Purity and side effect analysis for Java programs",
    due="Unrelated to provenance",
    display="salcianu",
    authors="S{ă}lcianu, Alexandru and Rinard, Martin",
    place=VMCAI,
    file="Salcianu2005a.pdf",
    doi="10.1007/978-3-540-30579-8_14",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=10030715577634329723&as_sdt=2005&sciodt=0,5&hl=en",
    pp="199--215",
    organization="Springer",
    cluster_id="10030715577634329723",
    scholar_ok=True,
    publisher="Springer",
))

scaffidi2005a = DB(WorkUnrelated(
    2005, "Estimating the numbers of end users and end user programmers",
    due="Unrelated to provenance",
    display="scaffidi",
    authors="Scaffidi, Christopher and Shaw, Mary and Myers, Brad",
    place=VLHCC,
    file="Scaffidi2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=4527662216180719638&as_sdt=2005&sciodt=0,5&hl=en",
    pp="207--214",
    organization="IEEE",
    cluster_id="4527662216180719638",
    scholar_ok=True,
    publisher="IEEE",
))

simmhan2005a = DB(WorkUnrelated(
    2005, "A Survey of Data Provenance Techniques",
    due="The only approach that captures provenance from scripts here is ESSW",
    star2="Applications of provenance: data quality, audit trail, replication recipes, attribution, infromational",
    display="simmhan",
    authors="Simmhan, Yogesh L and Plale, Beth and Gannon, Dennis",
    summary="Surveys applications of provenance; subjects of provenance (data, process); granularity of provenance; representation of provenance; storage; overhead",
    place=TechReport,
    entrytype="techreport",
    file="Simmhan2005a.pdf",
    number="IUB-CSTR618",
    institution="Indiana University, Bloomington IN",
    scholar="https://scholar.google.com/scholar?cites=9323991660699596603&as_sdt=2005&sciodt=0,5&hl=en",
    volume="47405",
    cluster_id="9323991660699596603",
    scholar_ok=True,

))

simmhan2005b = DB(WorkUnrelated(
    2005, "A survey of data provenance in e-science",
    alias=(2005, "Gannon (2005) A Survey of Data Provenance in e-Science", "Dennis, Yogesh L Simmhan Beth Plale"),
    due="This is a smaller version of simmhan2005a",
    star="[survey]",
    display="simmhan",
    authors="Simmhan, Yogesh L and Plale, Beth and Gannon, Dennis",
    summary="Surveys provenance in e-science",
    place=SIGMOD_REC,
    file="Simmhan2005b.pdf",
    volume="34",
    number="3",
    pp="31--36",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=5314021666511594224&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="5314021666511594224",
    scholar_ok=True,
    doi="10.1145/1084805.1084812",
))

simmhan2005c = DB(WorkLang(
    2005, "Latar belakang 2.1 Memotivasi domain untuk asalnya",
    display="simmhan",
    authors="Simmhan, Yogesh L and Plale, Beth and Gannon, Dennis and teknis IUB-CS-TR618, Laporan",
    entrytype="article",
    place=Lang,
    file="Simmhan2005c.docx",
    ID="simmhanlatar",
    scholar_ok=True,
))

sorlin2005a = DB(WorkUnrelated(
    2005, "Reactive tabu search for measuring graph similarity",
    due="Unrelated to provenance, unrelated to scripts",
    display="sorlin",
    authors="Sorlin, Sébastien and Solnon, Christine",
    pp="172--182",
    local="Poitiers, France",
    place=IAPR,
    file="Sorlin2005a.pdf",
    publisher="Springer Berlin Heidelberg",
    entrytype="inproceedings",
    cluster_id="18346397727288833679",
    scholar="http://scholar.google.com/scholar?cites=18346397727288833679&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
))

valeur2005a = DB(WorkSnowball(
    2005, "Tracking the lineage of arbitrary processing sequences",
    snowball=datetime(2017, 3, 6),
    display="es3",
    authors="Valeur, Håvar",
    summary="This describes how es3 instrument programs and capture provenance",
    place=Thesis,
    file="Valeur2005a.pdf",
    school="Norwegian University of Science and Technology, Trondheim",
    link="http://urn.ub.uu.se/resolve?urn= urn:nbn:no:ntnu:diva-1341",
    entrytype="phdthesis",
    scholar="http://scholar.google.com/scholar?cites=10082802369182678775&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Institutt for datateknikk og informasjonsvitenskap",
    cluster_id="10082802369182678775",
    scholar_ok=True,
    citation_file="es3_2005",
    tracking="alert",
    pp="91",
))

widom2005a = DB(WorkUnrelated(
    2005, "Trio: A System for Integrated Management of Data, Accuracy, and Lineage",
    due="Unrelated to scripts. The provenance is stored with the data in the database",
    may_be_related_to=["database"],
    display="widom",
    authors="Widom, Jennifer",
    summary="Proposes a database system that manages data and provenance",
    place=CIDR,
    file="Widom2005a.pdf",
    local="Asilomar, CA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=686835090543664143&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="686835090543664143",
    scholar_ok=True,
    pp="262--276",
))

wright2005a = DB(WorkUnrelated(
    2005, "Auto-pilot: A Platform for System Software Benchmarking",
    due="Unrelated to provenance, unrelated to scripts",
    display="wright",
    authors="Wright, Charles P and Joukov, Nikolai and Kulkarni, Devaki and Miretskiy, Yevgeniy and Zadok, Erez",
    summary="Proposes a tool for producing benchmark results",
    place=ATC,
    file="Wright2005a.pdf",
    track="FREENIX",
    pp="175--188",
    local="Anaheim, CA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=751475864691038357&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="751475864691038357",
    scholar_ok=True,
))

zhang2005a = DB(WorkUnrelated(
    2005, "Experimental evaluation of using dynamic slices for fault location",
    due="Unrelated to provenance. It is just an experimental evaluation of program slicing",
    may_be_related_to=["slicing"],
    display="zhang a",
    authors="Zhang, Xiangyu and He, Haifeng and Gupta, Neelam and Gupta, Rajiv",
    summary="Proposes three variants of dynamic slicing: data slicing, full slicing and relevant slicing, based on reduced ordered binary decision diagrams. Performs an experiments that shows that full slices and relevant slices can considerably reduce the subset of program statement that need to be examined to locate faulty statements",
    place=AADEBUG,
    file="Zhang2005a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12994955753271303110&as_sdt=2005&sciodt=0,5&hl=en",
    pp="33--42",
    organization="ACM",
    cluster_id="12994955753271303110",
    scholar_ok=True,
))

zhang2005b = DB(WorkUnrelated(
    2005, "An automated method for the analysis of stable isotope labeling data in proteomics",
    due="Unrelated to provenance, unrelated to scripts",
    display="zhang b",
    authors="Zhang, Xiang and Hines, Wade and Adamec, Jiri and Asara, John M and Naylor, Stephen and Regnier, Fred E",
    summary="Proposes an algorithm for the generation of reliable pptide component peak table from liquid chromatography-mass spectrometry",
    place=JASMS,
    file="Zhang2005b.pdf",
    volume="16",
    pp="1181--1191",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=4195061412236779733&as_sdt=2005&sciodt=0,5&hl=en",
    number="7",
    publisher="Elsevier",
    cluster_id="4195061412236779733",
    scholar_ok=True,
))
