# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


ai2013a = DB(WorkUnrelated(
    2013, "Algebra Operations of Information Resource View in Internet Environment",
    due="Unrelated to scripts",
    display="ai",
    authors="Ai, Yong and Zhang, Xin and Jin, Guo and Ma, Ji and Xie, Yufeng",
    pp="1507--1517",
    place=JOICS,
    file="Ai2013a.pdf",
    number="5",
    ID="ai10algebra",
    entrytype="article",
    volume="10",
    scholar_ok=True,
))

aktas2013a = DB(WorkUnrelated(
    2013, "Unmanaged workflows: Their provenance and use",
    due="Unrelated to scripts",
    display="aktas",
    authors="Aktas, Mehmet S and Plale, Beth and Leake, David and Mukhi, Nirmal K",
    place=DPDM,
    cluster_id="14056054252254300521",
    pp="59--81",
    ID="aktas2013unmanaged",
    entrytype="incollection",
    publisher="Springer",
    scholar="http://scholar.google.com/scholar?cites=14056054252254300521&as_sdt=2005&sciodt=0,5&hl=en",
    file="Aktas2013a.pdf#page=67",
    scholar_ok=True,
))

alper2013a = DB(WorkUnrelated(
    2013, "Small is beautiful: Summarizing scientific workflows using semantic annotations",
    due="Unrelated to scripts",
    may_be_related_to=["workflow", "summarization", "annotations"],
    display="alper",
    authors="Alper, Pinar and Belhajjame, Khalid and Goble, Carole and Karagoz, Pinar",
    summary="Proposes reduction primitives for summarizing workflows, and shows how primitives can be used in conjuction witg annotations to encode different summarizations",
    place=BigData,
    file="Alper2013a.pdf",
    pp="318--325",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11041268390888376644&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="11041268390888376644",
    scholar_ok=True,
))

antolik2013a = DB(WorkUnrelated(
    2013, "Integrated workflows for spiking neuronal network simulations",
    due="Unrelated to scripts, Unrelated to provenance",
    display="antolík",
    authors="Antolík, Ján and Davison, Andrew P",
    place=FNInf,
    file="Antolik2013a.pdf",
    volume="7",
    number="34",
    doi="10.3389/fninf.2013.00034",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9503366805410976742&as_sdt=2005&sciodt=0,5&hl=en",
    pp="34",
    publisher="Frontiers",
    cluster_id="9503366805410976742",
    scholar_ok=True,
))

bahls2013a = DB(WorkUnrelated(
    2013, "A data restore model for reproducibility in computational statistics",
    due="Unrelated to scripts",
    summary="Proposes a ontology for restoring experiments and a R plugin to apply the restoration",
    display="bahls",
    authors="Bahls, Daniel and Zapilko, Benjamin and Tochtermann, Klaus",
    place=ICKMKT,
    scholar="http://scholar.google.com/scholar?cites=565789856681637530&as_sdt=2005&sciodt=0,5&hl=en",
    pp="13",
    cluster_id="565789856681637530",
    file="Bahls2013a.pdf",
    ID="bahls2013data",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

bechhofer2013a = DB(WorkUnrelated(
    2013, "Why linked data is not enough for scientists",
    alias=(0, "Why Linked Data is Not Enough for Scientists", "Owena, David Newmanc and Sufia, Shoaib and Goblea, Carole"),
    due="Unrelated to scripts",
    display="bechhofer",
    authors="Bechhofer, Sean and Buchan, Iain and De Roure, David and Missier, Paolo and Ainsworth, John and Bhagat, Jiten and Couch, Philip and Cruickshank, Don and Delderfield, Mark and Dunlop, Ian and others",
    place=FGCS,
    scholar="http://scholar.google.com/scholar?cites=11174881363409099036&as_sdt=2005&sciodt=0,5&hl=en",
    pp="599--611",
    cluster_id="11174881363409099036",
    number="2",
    file="Bechhofer2013a.pdf",
    publisher="Elsevier",
    ID="bechhofer2013linked",
    entrytype="article",
    volume="29",
    scholar_ok=True,
))

becker2013a = DB(WorkUnrelated(
    2013, "Human Mobility Characterization from Cellular Network Data",
    alias=(0, "The magazine archive includes every article published in Communications of the ACM for over the past 50 years."),
    due="Unrelated to scripts. Unrelated to provenance",
    display="becker",
    authors="Becker, Richard and Cáceres, Ramón and Hanson, Karrie and Isaacman, Sibren and Loh, Ji Meng and Martonosi, Margaret and Rowland, James and Urbanek, Simon and Varshavsky, Alexander and Volinsky, Chris",
    place=CACM,
    pp="74--82",
    number="1",
    file="Becker2013a.pdf",
    ID="becker56magazine",
    entrytype="article",
    volume="56",
    publisher="ACM",
    cluster_id="5889198275888438788",
    scholar="http://scholar.google.com/scholar?cites=5889198275888438788&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

belikov2013a = DB(WorkUnrelated(
    2013, "Information systems playground: the target infrastructure",
    due="Unrelated to provenance",
    display="belikov",
    authors="Belikov, Andrey N and Dijkstra, Fokke and Gankema, Hans and van Hoof, Jeroen BAN and Koopman, Rick",
    place=EA,
    pp="367--389",
    volume="35",
    ID="belikov2013information",
    file="Belikov2013a.pdf",
    publisher="Springer",
    link="http://link.springer.com/article/10.1007/s10686-011-9262-1",
    number="1--2",
    scholar="http://scholar.google.com/scholar?cites=9066245848173982366&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="9066245848173982366",
    entrytype="article",
    scholar_ok=True,
))

bergstra2013a = DB(WorkUnrelated(
    2013, "Hyperopt: A python library for optimizing the hyperparameters of machine learning algorithms",
    due="Unrelated to provenance",
    display="bergstra",
    authors="Bergstra, James and Yamins, Dan and Cox, David D",
    place=SciPy,
    file="Bergstra2013a.pdf",
    pp="13--20",
    entrytype="inproceedings",
    cluster_id="4090146850565226752",
    scholar="http://scholar.google.com/scholar?cites=4090146850565226752&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Citeseer",
    scholar_ok=True,
))

borchert2013a = DB(WorkUnrelated(
    2013, "Generative software-based memory error detection and correction for operating system data structures",
    due="Unrelated to scripts. Unrelated to provenance",
    display="borchert",
    authors="Borchert, Christoph and Schirmeier, Horst and Spinczyk, Olaf",
    place=DSN,
    file="Borchert2013a.pdf",
    doi="10.1109/DSN.2013.6575308",
    local="Budapest, Hungary",
    month="June",
    publisher="IEEE",
    entrytype="inproceedings",
    organization="IEEE",
    pp="1--12",
    cluster_id="4345002860560061468",
    scholar="http://scholar.google.com/scholar?cites=4345002860560061468&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

buddelmeijer2013a = DB(WorkUnrelated(
    2013, "Leveraging data lineage to infer logical relationships between astronomical catalogs",
    due="Unrelated to script collection. Uses Astro-WISE",
    may_be_related_to=["discovery"],
    display="buddelmeijer",
    authors="Buddelmeijer, Hugo and Valentijn, Edwin A",
    place=EA,
    pp="227--244",
    volume="35",
    ID="buddelmeijer2013leveraging",
    file="Buddelmeijer2013a.pdf",
    publisher="Springer",
    link="http://link.springer.com/article/10.1007/s10686-012-9288-z",
    number="1--2",
    scholar="http://scholar.google.com/scholar?cites=3905891591025491750&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="3905891591025491750",
    entrytype="article",
    scholar_ok=True,
))

buddelmeijer2013b = DB(WorkUnrelated(
    2013, "Automatic optimized discovery, creation and processing of astronomical catalogs",
    due="Unrelated to script collection. Uses Astro-WISE",
    may_be_related_to=["discovery"],
    display="buddelmeijer b",
    authors="Buddelmeijer, Hugo and Boxhoorn, Danny and Valentijn, Edwin A",
    place=EA,
    pp="203--225",
    volume="35",
    ID="buddelmeijer2013automatic",
    file="Buddelmeijer2013b.pdf",
    publisher="Springer",
    link="http://link.springer.com/article/10.1007/s10686-011-9272-z",
    number="1--2",
    scholar="http://scholar.google.com/scholar?cites=4118473798759189625&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="4118473798759189625",
    entrytype="article",
    scholar_ok=True,
))

buneman2013a = DB(WorkUnrelated(
    2013, "Annotations are relative",
    due="Unrelated to scripts",
    display="buneman",
    authors="Buneman, Peter and Kostylev, Egor V and Vansummeren, Stijn",
    place=ICDT,
    pp="177--188",
    publisher="ACM",
    file="Buneman2013a.pdf",
    entrytype="inproceedings",
    organization="ACM",
    cluster_id="9196598838632019735",
    scholar="http://scholar.google.com/scholar?cites=9196598838632019735&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

callahan2013a = DB(WorkUnrelated(
    2013, "Bio2RDF release 2: improved coverage, interoperability and provenance of life science linked data",
    due="Unrelated to scripts",
    display="callahan",
    authors="Callahan, Alison and Cruz-Toledo, José and Ansell, Peter and Dumontier, Michel",
    place=ISWC,
    publisher="Springer",
    local="Berlin, Heidelberg",
    file="Callahan2013a.pdf",
    entrytype="inproceedings",
    pp="200--212",
    scholar="http://scholar.google.com/scholar?cites=10599832894208873870&as_sdt=5,33&sciodt=0,33&hl=en",
    cluster_id="10599832894208873870",
    organization="Springer",
    scholar_ok=True,
))

carata2013a = DB(WorkUnrelated(
    2013, "IPAPI: Designing an Improved Provenance API",
    summary="C++ API for provenance collections",
    due="Unrelated to scripts",
    may_be_related_to=["prog", "c++"],
    display="carata",
    authors="Carata, Lucian and Sohan, Ripduman and Rice, Andrew C and Hopper, Andy",
    place=TaPP,
    file="Carata2013a.pdf",
    star="library",
    scholar="http://scholar.google.com/scholar?cites=13018966803401286553&as_sdt=2005&sciodt=0,5&hl=en",
    ID="carata2013ipapi",
    entrytype="inproceedings",
    cluster_id="13018966803401286553",
    scholar_ok=True,
    publisher="USENIX",
    local="Lombard, IL, USA",
))

castleberry2013a = DB(WorkUnrelated(
    2013, "Inkling: An Executable Paper System for Reviewing Scientific Applications",
    due="Unrelated to provenance",
    display="castleberry",
    authors="Castleberry, Dennis G and Brandt, Steven R and Loffler, Frank",
    place=SocialCom,
    pp="917--922",
    file="Castleberry2013a.pdf",
    ID="castleberry2013inkling",
    organization="IEEE",
    entrytype="inproceedings",
    star="literate programming",
    scholar_ok=True,
))

chacko2013a = DB(WorkUnrelated(
    2013, "Generalized Architecture to Capture End to End Provenance in a System",
    due="Unrelated to scripts",
    display="chacko",
    authors="Chacko, Anu Mary and Kumar, Suresh and Pathari, Vinod",
    place=ICITCS,
    pp="1--4",
    file="Chacko2013a.pdf",
    ID="chacko2013generalized",
    organization="IEEE",
    entrytype="inproceedings",
    summary="client server architecture for capturing provenance",
    scholar_ok=True,
))

chebotko2013a = DB(WorkUnrelated(
    2013, "Storing, indexing and querying large provenance data sets as RDF graphs in apache HBase",
    due="Unrelated to scripts",
    surveyhide="1",
    display="chebotko",
    authors="Chebotko, Artem and Abraham, John and Brazier, Pearl and Piazza, Anthony and Kashlev, Andrey and Lu, Shiyong",
    place=SERVICES,
    pp="1--8",
    entrytype="inproceedings",
    organization="IEEE",
    ID="chebotko2013storing",
    file="chebotko2013a.pdf",
    local="Santa Clara, USA",
))

chirigati2013a = DB(WorkBinarySnowball(
    2013, "Reprozip: Using provenance to support computational reproducibility",
    may_be_related_to=["reproducibility"],
    display="ReproZip",
    summary="Proposes using provenance for packaging reproducible environments",
    authors="Chirigati, Fernando and Shasha, Dennis and Freire, Juliana",
    place=TaPP,
    file="Chirigati2013a.pdf",
    pp="977–980",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=9014328969653004577&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="9014328969653004577",
    scholar_ok=True,
    publisher="USENIX",
    local="Lombard, IL, USA",
))

chirigati2013b = DB(WorkBinarySnowball(
    2013, "Packing experiments for sharing and publication",
    display="ReproZip",
    summary="Demonstrates real use cases for ReproZiP",
    authors="Chirigati, Fernando and Shasha, Dennis and Freire, Juliana",
    place=SIGMOD,
    file="Chirigati2013b.pdf",
    pp="977--980",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=14868611822908168&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="14868611822908168",
    scholar_ok=True,
))


ciccarese2013a = DB(WorkUnrelated(
    2013, "PAV ontology: provenance, authoring and versioning",
    due="Unrelated to scripts",
    display="ciccarese",
    authors="Ciccarese, Paolo and Soiland-Reyes, Stian and Belhajjame, Khalid and Gray, Alasdair JG and Goble, Carole and Clark, Tim",
    place=JBIOBL,
    number="1",
    volume="4",
    pp="37",
    file="Ciccarese2013a.pdf",
    entrytype="article",
    publisher="BioMed Central",
    cluster_id="10801316487303443188",
    scholar="http://scholar.google.com/scholar?cites=10801316487303443188&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

conover2013a = DB(WorkUnrelated(
    2013, "Introducing provenance capture into a legacy data system",
    due="Unrelated to scripts",
    display="conover",
    authors="Conover, Helen and Ramachandran, Rahul and Beaumont, Bruce and Kulkarni, Ajinkya and McEniry, Michael and Regner, Kathryn and Graves, Sara",
    place=TGRS,
    number="11",
    pp="5098--5104",
    entrytype="article",
    cluster_id="3847048262140448547",
    publisher="IEEE",
    volume="51",
    scholar="http://scholar.google.com/scholar?cites=3847048262140448547&as_sdt=2005&sciodt=0,5&hl=en",
    file="Conover2013a.pdf",
    ID="conover2013introducing",
    scholar_ok=True,
))

costa2013a = DB(WorkUnrelated(
    2013, "Capturing and querying workflow runtime provenance with PROV: a practical approach",
    due="Unrelated to scripts",
    may_be_related_to=["analysis", "realtime"],
    display="costa",
    authors="Costa, Flavio and Silva, Vítor and De Oliveira, Daniel and Ocaña, Kary and Ogasawara, Eduardo and Dias, Jonas and Mattoso, Marta",
    pp="282--289",
    place=EDBT_ICDT,
    file="Costa2013a.pdf",
    shorttitle="Capturing and querying workflow runtime provenance with {PROV}",
    entrytype="inproceedings",
    local="Genoa, Italy",
    publisher="ACM",
    organization="ACM",
    cluster_id="13770525458905322730",
    scholar="http://scholar.google.com/scholar?cites=13770525458905322730&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))


crook2013a = DB(WorkUnrelated(
    2013, "Learning from the past: approaches for reproducibility in computational neuroscience",
    due="Unrelated to scripts. Unrelated to provenance",
    display="crook",
    authors="Crook, Sharon M and Davison, Andrew P and Plesser, Hans E",
    place=Book,
    file="Crook2013a.pdf#page=87",
    booktitle="20 Years of Computational Neuroscience",
    publisher="Springer",
    pp="73--102",
    entrytype="incollection",
    scholar="http://scholar.google.com/scholar?cites=5806774470143389408&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="5806774470143389408",
    scholar_ok=True,
))

di2013a = DB(WorkUnrelated(
    2013, "Geoscience data provenance: An overview",
    due="Unrelated to scripts",
    star="[survey] geoscience survey",
    display="di",
    authors="Di, Liping and Yue, Peng and Ramapriyan, Hampapuram K and King, Roger L",
    place=TGRS,
    scholar="http://scholar.google.com/scholar?cites=10602032586473601753&as_sdt=2005&sciodt=0,5&hl=en",
    ID="di2013geoscience",
    volume="51",
    file="Di2013a.pdf",
    entrytype="article",
    publisher="IEEE",
    pp="5065--5072",
    cluster_id="10602032586473601753",
    number="11",
    scholar_ok=True,
))

ecma2013a = DB(WorkUnrelated(
    2013, "The JSON Data Interchange Format",
    due="Unrelated to scripts. Unrelated to provenance",
    display="ecma",
    authors="ECMA",
    place=Standard,
    link="http://www.ecma-international.org/flat/publications/files/ECMA-ST/ECMA-404.pdf",
    month="October",
    file="Ecma2013a.pdf",
    scholar_ok="impossible",
))

eddelbuettel2013a = DB(WorkUnrelated(
    2013, "Seamless R and C++ integration with Rcpp",
    due="Unrelated to scripts. Unrelated to provenance",
    display="eddelbuettel",
    authors="Eddelbuettel, Dirk",
    place=Book,
    scholar="http://scholar.google.com/scholar?cites=15162159010703364496&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="15162159010703364496",
    entrytype="book",
    ID="eddelbuettel2013seamless",
    file="Eddelbuettel2013a.pdf",
    publisher="Springer",
    scholar_ok=True,
))

gandrud2013a = DB(WorkUnrelated(
    2013, "Reproducible Research with R and RStudio",
    due="Unrelated to tool-assisted provenance. Propose practices for designing reproducible research",
    may_be_related_to=["reproducibility"],
    display="gandrud",
    authors="Gandrud, Christopher",
    place=Book,
    file="Gandrud2013a.pdf",
    publisher="CRC Press",
    entrytype="book",
    scholar="https://scholar.google.com/scholar?cites=13619821454966708723&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="13619821454966708723",
    scholar_ok=True,
))

garcia2013a = DB(WorkLang(
    2013, "Documentación de modelos y flujos de trabajo: el siguiente reto en el manejo de información ecológica",
    display="bonet garcía",
    authors="Bonet García, Francisco Javier and Pérez Pérez, Ramón and Benito de Pando, Blas M and Pérez Luque, Antonio J and Zamora Rodríguez, Regino",
    place=Lang,
    ID="bonet2013documentacion",
    cluster_id="8752267171589680621",
    publisher="Asociación Española de Ecología Terrestre",
    scholar="http://scholar.google.com/scholar?cites=8752267171589680621&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    file="Garcia2013a.pdf",
    scholar_ok=True,
))

gavish2013a = DB(WorkUnrelated(
    2013, "Dream applications of verifiable computational results",
    due="Unrelated to provenance",
    display="gavish",
    authors="Gavish, Matan and Donoho, David and Onn, Amos",
    place=XRDS,
    pp="58--61",
    number="3",
    file="Gavish2013a.pdf",
    publisher="ACM",
    ID="gavish2013dream",
    entrytype="article",
    volume="19",
    excerpt=" Show a table of effect sizes and p- values in all phase-three clinical trials for Melanoma treatments published after 1994.  Name all image denoising algo- rithms ever used to remove white noise from the famous Barbara image, with citations.  List all of the classifiers applied to the famous ",
    scholar_ok=True,
))

gehani2013a = DB(WorkBinaryOk(
    2013, "Cross-platform provenance",
    display="gehani",
    authors="Gehani, Ashish and Tariq, Dawood",
    place=EDBT_ICDT,
    pp="335--336",
    organization="ACM",
    file="Gehani2013a.pdf",
    ID="gehani2013cross",
    star="Binary",
    entrytype="inproceedings",
    scholar_ok=True,
))

gent2013a = DB(WorkUnrelated(
    2013, "The recomputation manifesto",
    due="Unrelated to provenance",
    display="gent",
    authors="Gent, Ian P",
    place=arXiv,
    cluster_id="13131605543211606696",
    file="Gent2013a.pdf",
    ID="gent2013recomputation",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=13131605543211606696&as_sdt=2005&sciodt=0,5&hl=en",
    excerpt="Abstract: Replication of scientific experiments is critical to the advance of science. Unfortunately, the discipline of Computer Science has never treated replication seriously, even though computers are very good at doing the same thing over and over again. Not only ",
    scholar_ok=True,
))

ghoshal2013a = DB(WorkUnrelated(
    2013, "Static compiler analysis for workflow provenance",
    due="Unrelated to scripts",
    display="ghoshal",
    authors="Ghoshal, Devarshi and Chauhan, Arun and Plale, Beth",
    place=WORKS,
    scholar="http://scholar.google.com/scholar?cites=3495203343121843943&as_sdt=2005&sciodt=0,5&hl=en",
    pp="17--27",
    cluster_id="3495203343121843943",
    file="Ghoshal2013a.pdf",
    ID="ghoshal2013static",
    organization="ACM",
    entrytype="inproceedings",
    star="[collection] C",
    scholar_ok=True,
))

halperin2013a = DB(WorkUnrelated(
    2013, "Real-time collaborative analysis with (almost) pure SQL: a case study in biogeochemical oceanography",
    due="Unrelated to scripts. Unrelated to provenance",
    display="halperin",
    authors="Halperin, Daniel and Ribalet, Francois and Weitz, Konstantin and Saito, Mak A and Howe, Bill and Armbrust, E",
    place=SSDBM,
    file="Halperin2013a.pdf",
    month="July",
    local="Baltimore, MD, USA",
    pp="28",
    entrytype="inproceedings",
    organization="ACM",
    cluster_id="18302033458829838662",
    scholar="http://scholar.google.com/scholar?cites=18302033458829838662&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

heiberg2013a = DB(WorkUnrelated(
    2013, "A Pythonic Workflow for Automated Large-Scale Parameter Scans",
    due="Non Paper Format",
    display="heiberg",
    authors="Heiberg, Thomas and Plesser, Hans Ekkehard",
    place=FNInf,
    entrytype="article",
    ID="heibergpythonic",
    link="http://www.frontiersin.org/10.3389/conf.fninf.2013.09.00027/event_abstract",
    scholar_ok=True,
))

hemalatha2013a = DB(WorkUnrelated(
    2013, "A Study on Data Repertory Acumen Schema to Manage Data Provenance in Geoscience Application",
    alias=(2013, "A STUDY ON DATA REPERTORY ACUMEN SCHEMA TO MANAGE DATA PROVENANCE IN GEOSCIENCE APPLICATION", "HEMALATHA, M and KANNAN, KS"),
    due="Unrelated to scripts",
    display="hemalatha",
    authors="Hemalatha, M and Kannan, KS",
    place=IJCSMC,
    file="Hemalatha2013a.pdf",
    ID="hemalatha2013study",
    entrytype="article",
    scholar_ok=True,
))

hensley2013a = DB(WorkUnrelated(
    2013, "Provenance in sensor data management",
    due="Unrelated to scripts",
    display="hensley",
    authors="Hensley, Zachary and Sanyal, Jibonananda and New, Joshua",
    place=ACMQ,
    scholar="http://scholar.google.com/scholar?cites=17528168873172146956&as_sdt=2005&sciodt=0,5&hl=en",
    pp="50",
    cluster_id="17528168873172146956",
    number="12",
    file="Hensley2013a.pdf",
    publisher="ACM",
    ID="hensley2013provenance",
    entrytype="article",
    volume="11",
    scholar_ok=True,
))

hoffmann2013a = DB(WorkUnrelated(
    2013, "Failure by Design: Influence of the RTOS Interface on Memory Fault Resilience",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hoffmann",
    authors="Hoffmann, Martin and Dietrich, Christian and Lohmann, Daniel",
    place=SOBRES,
    file="Hoffmann2013a.pdf",
    link="http://danceos.org/sobres/2013/papers/SOBRES-550-Hoffmann.pdf",
    local="Koblenz, Germany",
    entrytype="inproceedings",
    pp="2562--2576",
    cluster_id="15619323047936727859",
    scholar="http://scholar.google.com/scholar?cites=15619323047936727859&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

hoffmann2013b = DB(WorkUnrelated(
    2013, "dOSEK: A dependable RTOS for automotive applications",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hoffmann",
    authors="Hoffmann, Martin and Dietrich, Christian and Lohmann, Daniel",
    place=PRDC,
    file="Hoffmann2013b.pdf",
    doi="10.1109/PRDC.2013.22",
    local="Vancouver, British Columbia, Canada",
    month="Dec",
    publisher="IEEE",
    entrytype="inproceedings",
    organization="IEEE",
    pp="120--121",
    cluster_id="15806591315155097001",
    scholar="http://scholar.google.com/scholar?cites=15806591315155097001&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

horta2013a = DB(WorkUnrelated(
    2013, "Provenance traces from chiron parallel workflow engine",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="chiron",
    authors="Horta, Felipe and Silva, Vítor and Costa, Flavio and de Oliveira, Daniel and Ocaña, Kary and Ogasawara, Eduardo and Dias, Jonas and Mattoso, Marta",
    place=EDBT,
    file="Horta2013a.pdf",
    pp="337--338",
    local="New York, NY, USA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=635213049456165235&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="635213049456165235",
    scholar_ok=True,
))

howe2013a = DB(WorkUnrelated(
    2013, "Collaborative science workflows in SQL",
    due="Unrelated to scripts",
    may_be_related_to=["database"],
    display="howe",
    authors="Howe, Bill and Halperin, Daniel and Ribalet, Francois and Chitnis, Sagar and Armbrust, E Virginia",
    summary="Proposes using SQL to perform data analysis instead of scripts",
    place=CiSE,
    file="Howe2013a.pdf",
    volume="15",
    number="3",
    pp="22--31",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=8878916562946359091&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="AIP Publishing",
    cluster_id="8878916562946359091",
    scholar_ok=True,
))

hull2013a = DB(WorkUnrelated(
    2013, "Initiation and maintenance of swimming in hatchling xenopus laevis tadpoles",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hull",
    authors="Hull, Michael James",
    place=Unpublished,
    scholar="http://scholar.google.com/scholar?cites=11165120919899834340&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11165120919899834340",
    file="Hull2013a.pdf",
    publisher="The University of Edinburgh",
    ID="hull2013initiation",
    entrytype="article",
    scholar_ok=True,
))

hunold2013a = DB(WorkUnrelated(
    2013, "On the state and importance of reproducible experimental research in parallel computing",
    due="Unrelated to scripts",
    may_be_related_to=["reproducibility"],
    display="hunold",
    authors="Hunold, Sascha and Träff, Jesper Larsson",
    place=arXiv,
    scholar="http://scholar.google.com/scholar?cites=7768615927185434442&as_sdt=2005&sciodt=0,5&hl=en",
    ID="hunold2013state",
    entrytype="article",
    file="Hunold2013a.pdf",
    cluster_id="7768615927185434442",
    excerpt="Abstract: Computer science is also an experimental science. This is particularly the case for parallel computing, which is in a total state of flux, and where experiments are necessary to substantiate, complement, and challenge theoretical modeling and analysis. Here, ",
    scholar_ok=True,
))

huntzinger2013a = DB(WorkUnrelated(
    2013, "The North American Carbon Program Multi-Scale Synthesis and Terrestrial Model Intercomparison Project|Part 1: Overview and experimental design",
    due="Unrelated to provenance. Unrelated to scripts",
    display="huntzinger",
    authors="Huntzinger, Deborah N and Schwalm, C and Michalak, AM and Schaefer, K and King, AW and Wei, Y and Jacobson, A and Liu, S and Cook, RB and Post, WM and, G. Berthier, D. Hayes, M. Huang, A. Ito, H. Lei, C. Lu, J. Mao, C. Peng, S. Peng, B. Poulter, D. Riccuito, X. Shi, H. Tian, H. Wang, N. Zeng, F. Zhao, and Q. Zhu",
    place=GMD,
    file="Huntzinger2013a.pdf",
    volume="6",
    number="6",
    pp="2121--2133",
    publisher="Copernicus GmnH",
    entrytype="article",
    scholar="https://scholar.google.com/scholar?cites=10097922794334831435&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="10097922794334831435",
    scholar_ok=True,
))

huq2013a = DB(WorkSnowball( # 12
    2013, "ProvenanceCurious: a tool to infer data provenance from scripts",
    snowball=datetime(2017, 3, 6),
    star="[collection][x] difficulty on collecting provenance from scripts",
    display="p.curious",
    authors="Huq, Mohammad Rezwanul and Apers, Peter MG and Wombacher, Andreas",
    summary="Visualizes prospective data provenance of Python script as a graph through AST analysis",
    place=EDBT,
    file="Huq2013a.pdf",
    local="Genoa, Italy",
    pp="765--768",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=3093501048951704768&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="3093501048951704768",
    scholar_ok=True,
    citation_file="provenance_curious2013a",
    tracking="alert",
))

huq2013b = DB(WorkSnowball( # 0 
    2013, "An inference-based framework for managing data provenance",
    snowball=datetime(2017, 3, 6),
    display="huq",
    authors="Huq, Mohammad Rezwanul",
    place=Thesis,
    school="University of Twente",
    ID="huq2013inference",
    file="Huq2013b.pdf",
    entrytype="phdthesis",
    excerpt="Scientists can facilitate data intensive applications to study and understand the behavior of a complex system. In a data intensive application, a scientific model facilitates raw data products, collected from various sources, to produce new data products. Based on the ",
    citation_file="provenance_curious2013b",
    scholar="http://scholar.google.com/scholar?cites=7945919521799577096&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7945919521799577096",
    scholar_ok=True,
    tracking="alert",
))

huq2013c = DB(WorkSnowball( # 7
    2013, "An inference-based framework to manage data provenance in Geoscience Applications",
    snowball=datetime(2017, 3, 6),
    display="huq",
    authors="Huq, Mohammad Rezwanul and Apers, Peter MG and Wombacher, Andreas",
    place=TGRS,
    local="Washington, DC, USA",
    number="11",
    volume="51",
    star="provenance curious",
    ID="huq2013inference",
    cluster_id="9665993040283176869",
    publisher="IEEE",
    pp="5113--5130",
    scholar="http://scholar.google.com/scholar?cites=9665993040283176869&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    file="Huq2013c.pdf",
    citation_file="provenance_curious2013c",
    scholar_ok=True,
    tracking="alert",
))

janga2013a = DB(WorkUnrelated(
    2013, "Schema extraction and integration of heterogeneous XML document collections",
    due="Unrelated to scripts. Unrelated to provenance",
    display="janga",
    authors="Janga, Prudhvi and Davis, Karen C",
    place=MEDI,
    file="Janga2013a.pdf",
    editors="A. Cuz-zocrea and S. Maabout",
    proceedings="LNCS 8216",
    pp="176--187",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11375268606301195029&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="11375268606301195029",
    scholar_ok=True,
))

kay2013a = DB(WorkUnrelated(
    2013, "A two-stage cascade model of BOLD responses in human visual cortex",
    due="Unrelated to scripts. Unrelated to provenance",
    display="kay",
    authors="Kay, Kendrick N and Winawer, Jonathan and Rokem, Ariel and Mezer, Aviv and Wandell, Brian A",
    place=PCBI,
    scholar="http://scholar.google.com/scholar?cites=12539633318036719712&as_sdt=2005&sciodt=0,5&hl=en",
    pp="e1003079",
    cluster_id="12539633318036719712",
    volume="9",
    entrytype="article",
    link="http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003079",
    file="Kay2013a.pdf",
    publisher="Public Library of Science",
    number="5",
    ID="kay2013two",
    scholar_ok=True,
))

kim2013a = DB(WorkUnrelated(
    2013, "Practical and effective sandboxing for non-root users",
    due="Unrelated to provenance",
    display="kim",
    authors="Kim, Taesoo and Zeldovich, Nickolai",
    place=ATC,
    file="Kim2013a.pdf",
    pp="139--144",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11927630412911399648&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11927630412911399648",
    scholar_ok=True,
))

koop2013a = DB(WorkUnrelated(
    2013, "Visual summaries for graph collections",
    due="Unrelated to scripts, unrelated to provenance",
    may_be_related_to=["graph summarization"],
    display="koop",
    authors="Koop, David and Freire, Juliana and Silva, Cláudio T",
    summary="Proposes an algorithm to compute a summary graph that encondes an entire collection of graphs",
    summarization="Finds and joins similar nodes and edges. Uses domain specific functions to join nodes and edges with the purpose of obtaining more compact graphs",
    visualization="Graph visualization allows interaction to join more nodes",
    place=PacificVis,
    file="Koop2013a.pdf",
    pp="57--64",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=6859053078223712902&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="6859053078223712902",
    scholar_ok=True,
))

kudo2013a = DB(WorkUnrelated(
    2013, "Business process discovery by using process skeletonization",
    due="Unrelated to provenance. Unrelated to scripts",
    may_be_related_to=["mining"],
    display="kudo",
    authors="Kudo, Michiharu and Ishida, Ai and Sato, Naoto",
    place=SITIS,
    file="Kudo2013a.pdf",
    pp="976--982",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=13139045892089859894&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="13139045892089859894",
    scholar_ok=True,
))

laine2013a = DB(WorkUnrelated(
    2013, "Closing in on the Truth about recombinant human bone morphogenetic protein-2: Evidence synthesis,data sharing, peer review, and reproducible research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="laine",
    authors="Laine, Christine and Guallar, Eliseo and Mulrow, Cynthia and Taichman, Darren B and Cornell, John E and Cotton, Deborah and Griswold, Michael E and Localio, A Russell and Meibohm, Anne R and Stack, Catharine B and Williams, Sankey V and Goodman, Steven N",
    place=AIM,
    number="12",
    volume="158",
    pp="916--918",
    file="Laine2013a.pdf",
    link="http://annals.org/aim/article/1696651/closing-truth-about-recombinant-human-bone-morphogenetic-protein-2-evidence",
    entrytype="article",
    publisher="Am Coll Physicians",
    cluster_id="12321081721590024612",
    scholar="http://scholar.google.com/scholar?cites=12321081721590024612&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

lebo2013a = DB(WorkUnrelated(
    2013, "Prov-o: The prov ontology",
    due="Unrelated to scripts",
    may_be_related_to=["semantic web"],
    display="lebo",
    authors="Lebo, Timothy and Sahoo, Satya and McGuinness, Deborah and Belhajjame, Khalid and Cheney, James and Corsar, David and Garijo, Daniel and Soiland-Reyes, Stian and Zednik, Stephan and Zhao, Jun",
    place=W3C,
    link="http://www.w3.org/TR/prov-o/",
    entrytype="article",
    scholar="https://scholar.google.com/scholar?cites=10865476685257256134&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="10865476685257256134",
    scholar_ok=True,
))

lee2013a = DB(WorkBinaryOk(
    2013, "LogGC: garbage collecting audit log",
    display="lee",
    authors="Lee, Kyu Hyung and Zhang, Xiangyu and Xu, Dongyan",
    place=CCS,
    scholar="http://scholar.google.com/scholar?cites=16424317230926799065&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1005--1016",
    cluster_id="16424317230926799065",
    file="Lee2013a.pdf",
    ID="lee2013loggc",
    organization="ACM",
    entrytype="inproceedings",
    star="[collection] c++ binary",
    scholar_ok=True,
))

li2013a = DB(WorkUnrelated(
    2013, "A geospatial cyberinfrastructure for urban economic analysis and spatial decision-making",
    due="Unrelated to scripts",
    display="li",
    authors="Li, Wenwen and Li, Linna and Goodchild, Michael F and Anselin, Luc",
    place=ISPRS,
    link="http://www.mdpi.com/2220-9964/2/2/413/htm",
    file="Li2013a.pdf",
    publisher="Multidisciplinary Digital Publishing Institute",
    volume="2",
    cluster_id="11399965948506776773",
    ID="li2013geospatial",
    scholar="http://scholar.google.com/scholar?cites=11399965948506776773&as_sdt=2005&sciodt=0,5&hl=en",
    number="2",
    entrytype="article",
    pp="413--431",
    scholar_ok=True,
))

lim2013a = DB(WorkUnrelated(
    2013, "OPQL: querying scientific workflow provenance at the graph level",
    star="[analysis][x] Query in OPQL",
    due="Unrelated to scripts",
    may_be_related_to=["query"],
    display="lim",
    authors="Lim, Chunhyeok and Lu, Shiyong and Chebotko, Artem and Fotouhi, Farshad and Kashlev, Andrey",
    place=DKE,
    file="Lim2013a.pdf",
    volume="88",
    number="0",
    pp="37--59",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=14870246154996470557&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Elsevier",
    cluster_id="14870246154996470557",
    scholar_ok=True,
))

liu2013a = DB(WorkBinaryOk(
    2013, "Towards semantic comparison of multi-granularity process traces",
    display="liu",
    authors="Liu, Qing and Zhao, Xiang and Taylor, Kerry and Lin, Xuemin and Squire, Geoffrey and Kloppers, Corne and Miller, Richard",
    place=KBS,
    cluster_id="7809050713385255392",
    pp="91--106",
    ID="liu2013towards",
    entrytype="article",
    publisher="Elsevier",
    volume="52",
    scholar="http://scholar.google.com/scholar?cites=7809050713385255392&as_sdt=2005&sciodt=0,5&hl=en",
    file="Liu2013a.pdf",
    scholar_ok=True,
))

maestre2013a = DB(WorkUnrelated(
    2013, "Moses: a metaheuristic optimization software ecosystem. Applications to the automated analysis of software product lines and service-based applications",
    alias=(2013, "MOSES: A METAHEURISTIC OPTIMIZATION SOFTWARE ECOSYSTEM", "MAESTRE, JOSe ANTONIO PAREJO"),
    due="Unrelated to provenance",
    display="maestre",
    authors="Parejo Maestre, José Antonio",
    place=Thesis,
    file="Maestre2013a.pdf",
    publisher="Citeseer",
    entrytype="article",
    ID="maestre2013moses",
    scholar_ok=True,
))

magliacane2013a = DB(WorkUnrelated(
    2013, "Repurposing Benchmark Corpora for Reconstructing Provenance",
    due="Unrelated to scripts",
    display="magliacane",
    authors="Magliacane, Sara and Groth, Paul T",
    place=SePublica,
    scholar="http://scholar.google.com/scholar?cites=15434134129941238102&as_sdt=2005&sciodt=0,5&hl=en",
    ID="magliacane2013repurposing",
    cluster_id="15434134129941238102",
    pp="39--50",
    entrytype="inproceedings",
    file="Magliacane2013a.pdf#page=39",
    scholar_ok=True,
))

malik2013a = DB(WorkBinaryOk(
    2013, "Sketching distributed data provenance",
    display="malik",
    authors="Malik, Tanu and Gehani, Ashish and Tariq, Dawood and Zaffar, Fareed",
    place=DPDM,
    file="Malik2013a.pdf",
    scholar="http://scholar.google.com/scholar?cites=8056666988156035563&as_sdt=2005&sciodt=0,5&hl=en",
    pp="85--107",
    entrytype="incollection",
    publisher="Springer",
    cluster_id="8056666988156035563",
    ID="malik2013sketching",
    star="Binary",
    scholar_ok=True,
))

mattioni2013a = DB(WorkUnrelated(
    2013, "Integration of biochemical and electrical signaling-multiscale model of the medium spiny neuron of the striatum",
    due="Unrelated to scripts. Unrelated to provenance",
    display="mattioni",
    authors="Mattioni, Michele and Le Novère, Nicolas",
    place=PLOSOne,
    scholar="http://scholar.google.com/scholar?cites=11627526673268190850&as_sdt=2005&sciodt=0,5&hl=en",
    pp="e66811",
    cluster_id="11627526673268190850",
    number="7",
    file="Mattioni2013a.pdf",
    publisher="Public Library of Science",
    ID="mattioni2013integration",
    entrytype="article",
    volume="8",
    scholar_ok=True,
))

mcfarland2013a = DB(WorkUnrelated(
    2013, "The Astro-WISE approach to quality control for astronomical data",
    due="Unrelated to provenance. Extends Astro-WISE",
    display="astro wise",
    authors="McFarland, John P and Helmich, Ewout M and Valentijn, Edwin A",
    place=EA,
    pp="79--102",
    volume="35",
    ID="mcfarland2013astro",
    file="Mcfarland2013a.pdf",
    publisher="Springer",
    link="http://link.springer.com/article/10.1007/s10686-012-9296-z/fulltext.html",
    number="1--2",
    scholar="http://scholar.google.com/scholar?cites=2579180800452399081&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="2579180800452399081",
    entrytype="article",
    scholar_ok=True,
))

mcfarland2013b = DB(WorkUnrelated(
    2013, "The astro-wise optical image pipeline",
    due="Unrelated to provenance. Extends Astro-WISE",
    display="astro wise",
    authors="McFarland, John P and Verdoes-Kleijn, Gijs and Sikkema, Gert and Helmich, Ewout M and Boxhoorn, Danny R and Valentijn, Edwin A",
    place=EA,
    pp="45--78",
    volume="35",
    ID="mcfarland2013astro",
    file="Mcfarland2013b.pdf",
    publisher="Springer",
    link="http://link.springer.com/article/10.1007/s10686-011-9266-x",
    number="1--2",
    scholar="http://scholar.google.com/scholar?cites=12093420222269825157&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="12093420222269825157",
    entrytype="article",
    scholar_ok=True,
))

meyerovich2013a = DB(WorkUnrelated(
    2013, "Empirical analysis of programming language adoption",
    due="Unrelated to scripts. Unrelated to provenance",
    display="meyerovich",
    authors="Meyerovich, Leo A and Rabkin, Ariel S",
    place=OOPSLA,
    pp="1--18",
    link="http://sns.cs.princeton.edu/docs/asr-oopsla13.pdf",
    local="Indianapolis, IN",
    file="Meyerovich2013a.pdf",
    entrytype="inproceedings",
    number="10",
    scholar="http://scholar.google.com/scholar?cites=17049053249980410434&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="ACM",
    cluster_id="17049053249980410434",
    volume="48",
    scholar_ok=True,
))

missier2013a = DB(WorkUnrelated(
    2013, "Provenance and data differencing for workflow reproducibility analysis",
    star="[repro][xx] talks about workflow decay and reprodutibility",
    due="Unrelated to scripts",
    may_be_related_to=["diff", "evolution"],
    display="missier a",
    authors="Missier, Paolo and Woodman, Simon and Hiden, Hugo and Watson, Paul",
    summary="Proposes a diff algorithm (PDIFF) for workflow graphs to check reproducibility (repeatability). Defines reprodutibility space",
    place=CCPE,
    file="Missier2013a.pdf",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=16007037149487248339&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Wiley Online Library",
    cluster_id="16007037149487248339",
    scholar_ok=True,
))

missier2013b = DB(WorkUnrelated(
    2013, "D-PROV: Extending the PROV Provenance Model with Workflow Structure",
    due="Unrelated to scripts",
    may_be_related_to=["model"],
    display="missier b",
    authors="Missier, Paolo and Dey, Saumen and Belhajjame, Khalid and Cuevas-Vicenttín, Víctor and Ludäscher, Bertram",
    place=TaPP,
    pp="1--7",
    file="Missier2013b.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=5298657585852421889&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="5298657585852421889",
    scholar_ok=True,
    publisher="USENIX",
    local="Lombard, IL, USA",
))

missier2013c = DB(WorkUnrelated(
    2013, "The W3C PROV family of specifications for modelling provenance metadata",
    due="Unrelated to scripts",
    display="missier",
    authors="Missier, Paolo and Belhajjame, Khalid and Cheney, James",
    place=EDBT,
    local="Genoa, Italy",
    file="Missier2013c.pdf",
    entrytype="inproceedings",
    organization="ACM",
    pp="773--776",
    cluster_id="17983947509500584642",
    scholar="http://scholar.google.com/scholar?cites=17983947509500584642&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

moore2013a = DB(WorkOk(
    2013, "Declaratively Processing Provenance Metadata",
    due="Unrelated to scripts",
    may_be_related_to=["logic"],
    display="moore",
    authors="Moore, Scott and Gehani, Ashish and Shankar, Natarajan",
    place=TaPP,
    scholar="http://scholar.google.com/scholar?cites=16388070822361231394&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="16388070822361231394",
    file="Moore2013a.pdf",
    ID="moore2013declaratively",
    entrytype="inproceedings",
    star="[collection] datalog",
    scholar_ok=True,
    publisher="USENIX",
    local="Lombard, IL, USA",
))

moreau2013a = DB(WorkUnrelated(
    2013, "Prov-dm: The prov data model",
    due="Unrelated to scripts",
    may_be_related_to=["model"],
    display="moreau a",
    authors="Moreau, Luc and Missier, Paolo",
    place=Web,
    link="https://www.w3.org/TR/prov-dm/",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=15080586250320325138&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="World Wide Web Consortium",
    cluster_id="15080586250320325138",
    scholar_ok=True,
))

moreau2013b = DB(WorkUnrelated(
    2013, "Provenance: An introduction to prov",
    due="Unrelated to scripts",
    display="moreau b",
    authors="Moreau, Luc and Groth, Paul",
    place=Book, #SyntLecSemWeb
    link="http://www.provbook.org/",
    volume="3",
    number="4",
    pp="1--129",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11613108553023195018&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Morgan & Claypool Publishers",
    cluster_id="11613108553023195018",
    scholar_ok=True,
))

murphy2013a = DB(WorkUnrelated(
    2013, "Textual Hydraulics: Mining Online Newspapers to Detect Physical, Social, and Institutional Water Management Infrastructure",
    due="Unrelated to provenance. Unrelated to scripts",
    display="murphy",
    authors="Murphy, J., et. al.",
    place=TechReport,
    link="https://web.ci.uchicago.edu/events/detail.php?id=1911",
    local="Argonne National Lab.",
    scholar_ok="impossible",
))

nadi2013a = DB(WorkUnrelated(
    2013, "Linux Variability Anomalies: What Causes Them and How Do They Get Fixed?",
    due="Unrelated to scripts. Unrelated to provenance",
    display="nadi",
    authors="Nadi, Sarah and Dietrich, Christian and Tartler, Reinhard and Holt, Richard C and Lohmann, Daniel",
    place=MSR,
    file="Nadi2013a.pdf",
    doi="10.1109/MSR.2013.6624017",
    pp="111--120",
    isbn="978-1-4799-0345-0",
    month="May",
    publisher="IEEE",
    local="Washington, DC, USA",
    entrytype="inproceedings",
    organization="IEEE Press",
    cluster_id="18144188436629816097",
    scholar="http://scholar.google.com/scholar?cites=18144188436629816097&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

nascimento2013a = DB(WorkLang(
    2013, "RFlow: Uma Abordagem de Reutiliza{ç}ão de Workflows Estatísticos Legados",
    display="nascimento",
    authors="do Nascimento, José Antônio Pires and da Cruz, Sérgio Manuel Serra",
    place=Lang,
    scholar="http://scholar.google.com/scholar?cites=11748453944812798592&as_sdt=2005&sciodt=0,5&hl=en",
    ID="dorflow",
    entrytype="article",
    cluster_id="11748453944812798592",
    file="Nascimento2013a.pdf",
    scholar_ok=True,
))

neves2013a = DB(WorkUnrelated(
    2013, "Implicit provenance gathering through configuration management",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    star="[collection][x] collection of implicit provenance",
    display="neves",
    authors="Neves, Vitor C and Braganholo, Vanessa and Murta, Leonardo",
    summary="Captures provenance of implicit dataflow through configuration management. Limitation: it is integrated to ProvManager, which is a SWfMS based on activities",
    define={"implicit provenance": "data not explicitly referenced by the workflow specification"},
    place=SECSE,
    local="Regensburg, Germany",
    file="Neves2013a.pdf",
    pp="92--95",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7671391451063339041&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE Press",
    cluster_id="7671391451063339041",
    scholar_ok=True,
))

nies2013a = DB(WorkUnrelated(
    2013, "Git2PROV: exposing version control system content as W3C PROV",
    due="Unrelated to scripts",
    may_be_related_to=["evolution"],
    display="nies",
    authors="De Nies, Tom and Magliacane, Sara and Verborgh, Ruben and Coppens, Sam and Groth, Paul and Mannens, Erik and Van de Walle, Rik",
    place=ISWC,
    file="Nies2013a.pdf",
    pp="125--128",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=15211400805348439862&as_sdt=2005&sciodt=0,5&hl=en",
    organization="CEUR-WS. org",
    cluster_id="15211400805348439862",
    scholar_ok=True,
))

nies2013b = DB(WorkUnrelated(
    2013, "Assessing content value for digital publishing through relevance and provenance-based trust",
    due="Unrelated to scripts",
    display="de nies",
    authors="De Nies, Tom",
    place=ISWC,
    scholar="http://scholar.google.com/scholar?cites=16388128328233660802&as_sdt=2005&sciodt=0,5&hl=en",
    ID="de2013assessing",
    cluster_id="16388128328233660802",
    organization="Springer",
    pp="424--431",
    entrytype="inproceedings",
    file="Nies2013a.pdf#page=452",
    scholar_ok=True,
))

ogasawara2013a = DB(WorkUnrelated(
    2013, "Chiron: a parallel engine for algebraic scientific workflows",
    due="Unrelated to scripts",
    display="ogasawara",
    authors="Ogasawara, Eduardo and Dias, Jonas and Silva, Vitor and Chirigati, Fernando and Oliveira, Daniel and Porto, Fabio and Valduriez, Patrick and Mattoso, Marta",
    place=CCPE,
    file="Ogasawara2013a.pdf",
    scholar="http://scholar.google.com/scholar?cites=14367105663095951270&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="14367105663095951270",
    doi="10.1002/cpe.3032",
    pp="2327--2341",
    number="16",
    volume="25",
    entrytype="article",
    publisher="Wiley Online Library",
    scholar_ok=True,
))

oxberry2013a = DB(WorkUnrelated(
    2013, "Establishing global error bounds for model reduction in combustion",
    due="Unrelated to scripts. Unrelated to provenance",
    display="oxberry",
    authors="Oxberry, Geoffrey Malcolm",
    place=Thesis,
    file="Oxberry2013a.pdf",
    entrytype="phdthesis",
    ID="oxberry2013establishing",
    local="Massachusetts Institute of Technology",
    school="Massachusetts Institute of Technology",
    scholar_ok=True,
))

patel2013a = DB(WorkUnrelated(
    2013, "Lowering the barrier to applying machine learning",
    due="Unrelated to scripts. Unrelated to provenance",
    display="patel",
    authors="Patel, Kayur Dushyant",
    place=Thesis,
    ID="patel2013lowering",
    cluster_id="4269341874801068253",
    file="Patel2013a.pdf",
    scholar="http://scholar.google.com/scholar?cites=4269341874801068253&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="phdthesis",
    scholar_ok=True,
))

perry2013a = DB(WorkUnrelated(
    2013, "Inmembrane, a bioinformatic workflow for annotation of bacterial cell-surface proteomes",
    due="Unrelated to scripts. Unrelated to provenance",
    display="perry",
    authors="Perry, Andrew J and Ho, Bosco K",
    place=SCFBM,
    file="Perry2013a.pdf",
    volume="8",
    number="1",
    pp="1",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=3565092552522961912&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="BioMed Central",
    cluster_id="3565092552522961912",
    scholar_ok=True,
))

pham2013a = DB(WorkBinarySnowball(
    2013, "Using provenance for repeatability",
    display="PTU",
    summary="Collects provenance for partial determinisc replay",
    authors="Pham, Quan and Malik, Tanu and Foster, Ian",
    place=TaPP,
    file="Pham2013a.pdf",
    pp="2:1--2:4",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11249993232249424390&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11249993232249424390",
    scholar_ok=True,
    publisher="USENIX",
    local="Lombard, IL, USA",
))

reimann2013a = DB(WorkUnrelated(
    2013, "A biophysically detailed model of neocortical local field potentials predicts the critical role of active membrane currents",
    due="Unrelated to scripts. Unrelated to provenance",
    display="reimann",
    authors="Reimann, Michael W and Anastassiou, Costas A and Perin, Rodrigo and Hill, Sean L and Markram, Henry and Koch, Christof",
    place=Neuron,
    pp="375--390",
    volume="79",
    doi="10.1016/j.neuron.2013.05.023",
    file="Reimann2013a.pdf",
    entrytype="article",
    number="2",
    publisher="Elsevier",
    cluster_id="1317977555228857648",
    scholar="http://scholar.google.com/scholar?cites=1317977555228857648&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

roffel2013a = DB(WorkUnrelated(
    2013, "Linking data in and outside a scientific publishing house",
    due="Non Paper Format",
    display="roffel",
    authors="Roffel, Sweitze",
    place=WWW,
    pp="411--412",
    file="Roffel2013a.pdf",
    ID="roffel2013linking",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

runnalls2013a = DB(WorkUnrelated(
    2013, "CXXR: an extensible R interpreter",
    due="Unrelated to provenance. This paper just cites provenance as an initial motivation for CXXR",
    display="runnalls",
    authors="Runnalls, Andrew",
    place=WIREsCS,
    number="3",
    volume="5",
    scholar="http://scholar.google.com/scholar?cites=14920644770018711070&as_sdt=2005&sciodt=0,5&hl=en",
    ID="runnalls2013cxxr",
    cluster_id="14920644770018711070",
    publisher="Wiley Online Library",
    pp="181--189",
    entrytype="article",
    file="Runnalls2013a.pdf",
    excerpt="The continued growth of CRAN is a testament to the increasing number of developers engaged in R development. But far fewer researchers have experimented with the R interpreter itself. The code of the interpreter, written for the most part in C, is structured in a way that will be foreign ",
    scholar_ok=True,
))

sandve2013a = DB(WorkUnrelated(
    2013, "Ten Simple Rules for Reproducible Computational Research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="sandve",
    authors="Sandve, Geir Kjetil and Nekrutenko, Anton and Taylor, James and Hovig, Eivind",
    place=PCBI,
    pp="e1003285",
    doi="10.1371/journal.pcbi.1003285",
    month="October",
    volume="9",
    file="Sandve2013a.pdf",
    number="10",
    entrytype="article",
    publisher="Public Library of Science",
    cluster_id="5179125613149376889",
    scholar="http://scholar.google.com/scholar?cites=5179125613149376889&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

soares2013a = DB(WorkLang(
    2013, "Estudo Comparativo entre Sistemas de Bancos de Dados de Grafos e Relacionais para a Gerência de Dados de Proveniência em Workflows Científicos",
    display="soares",
    authors="Soares, Ricardo Rocha",
    place=Lang,
    ID="soares2013estudo",
    cluster_id="224238814418231401",
    scholar="http://scholar.google.com/scholar?cites=224238814418231401&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="phdthesis",
    file="Soares2013a.pdf",
    local="Universidade Federal do Rio de Janeiro",
    school="Universidade Federal do Rio de Janeiro",
    scholar_ok=True,
))

souilah2013a = DB(WorkUnrelated(
    2013, "Provenance in distributed systems: a process algebraic study of provenance management and its role in establishing trust in data quality",
    due="Unrelated to scripts",
    display="souilah",
    authors="Souilah, Issam",
    place=Thesis,
    local="University of Southampton",
    ID="souilah2013provenance",
    entrytype="phdthesis",
    file="Souilah2013a.pdf",
    school="University of Southampton",
    scholar_ok=True,
))

spinuso2013a = DB(WorkUnrelated(
    2013, "Provenance for seismological processing pipelines in a distributed streaming workflow",
    due="Unrelated to scripts",
    display="spinuso",
    authors="Spinuso, Alessandro and Cheney, James and Atkinson, Malcolm",
    place=EDBT_ICDT,
    scholar="http://scholar.google.com/scholar?cites=3081247909992278288&as_sdt=2005&sciodt=0,5&hl=en",
    pp="307--312",
    cluster_id="3081247909992278288",
    file="Spinuso2013a.pdf",
    ID="spinuso2013provenance",
    organization="ACM",
    entrytype="inproceedings",
    summary="Use CPL",
    scholar_ok=True,
))

stevens2013a = DB(WorkSnowball( # 10
    2013, "An automated and reproducible workflow for running and analyzing neural simulations using Lancet and IPython Notebook",
    display="stevens",
    summary="Proposes utilities that aim to improve the productivy and collect provenance as a bonus for reproductibility",
    authors="Stevens, Jean-Luc Richard and Elver, Marco and Bednar, James A",
    place=FNInf,
    file="Stevens2013a.pdf",
    volume="7",
    number="44",
    entrytype="article",
    link="http://journal.frontiersin.org/article/10.3389/fninf.2013.00044/full",
    scholar="http://scholar.google.com/scholar?cites=9618273160775972978&as_sdt=2005&sciodt=0,5&hl=en",
    pp="44",
    publisher="Frontiers",
    cluster_id="9618273160775972978",
    scholar_ok=True,
    citation_file="lancet2013",
    tracking="alert",
))

stevens2013b = DB(WorkUnrelated(
    2013, "Mechanisms for stable, robust, and adaptive development of orientation maps in the primary visual cortex",
    snowball=datetime(2017,2,11),
    due="Unrelated to provenance",
    display="stevens",
    authors="Stevens, Jean-Luc R and Law, Judith S and Antolík, Ján and Bednar, James A",
    place=Neuroscience,
    file="Stevens2013b.pdf",
    volume="33",
    pp="15747--15766",
    doi="10.1523/JNEUROSCI.1037-13.2013",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=12724049261407624186&as_sdt=2005&sciodt=0,5&hl=en",
    number="40",
    publisher="Soc Neuroscience",
    cluster_id="12724049261407624186",
    scholar_ok=True,
))

stodden2013a = DB(WorkUnrelated(
    2013, "Toward Reproducible Computational Research: An Empirical Analysis of Data and Code Policy Adoption by Journals",
    due="Unrelated to provenance",
    display="stodden",
    authors="Stodden, Victoria and Guo, Peixuan and Ma, Zhaokun",
    place=PLOSOne,
    number="6",
    volume="8",
    pp="e67111",
    file="Stodden2013a.pdf",
    entrytype="article",
    publisher="Public Library of Science",
    cluster_id="18181284265610198339",
    scholar="http://scholar.google.com/scholar?cites=18181284265610198339&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

sweeney2013a = DB(WorkUnrelated(
    2013, "An Open Science Platform for the Next Generation of Data",
    due="Unrelated to scripts",
    display="sweeney",
    authors="Sweeney, Latanya and Crosas, Merce",
    place=arXiv,
    scholar="http://scholar.google.com/scholar?cites=7149624829381307040&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7149624829381307040",
    file="Sweeney2013a.pdf",
    ID="sweeney2013open",
    entrytype="article",
    scholar_ok=True,
))

tan2013a = DB(WorkUnrelated(
    2013, "Security and data accountability in distributed systems: A provenance survey",
    due="Unrelated to provenance",
    display="tan",
    authors="Tan, Yu Shyang and Ko, Ryan KL and Holmes, Geoff",
    pp="1571--1578",
    place=HPCC_EUC,
    file="Tan2013a.pdf",
    organization="IEEE",
    cluster_id="12502680804087483008",
    ID="tan2013security",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12502680804087483008&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

tsai2013a = DB(WorkUnrelated(
    2013, "AutoDrug: fully automated macromolecular crystallography workflows for fragment-based drug discovery",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="tsai",
    authors="Tsai, Yingssu and McPhillips, Scott E and González, Ana and McPhillips, Timothy M and Zinn, Daniel and Cohen, Aina E and Feese, Michael D and Bushnell, David and Tiefenbrunn, Theresa and Stout, CDavid and others",
    place=IUCr,
    file="Tsai2013a.pdf",
    volume="69",
    number="5",
    pp="796--803",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=13369651427640925537&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="International Union of Crystallography",
    cluster_id="13369651427640925537",
    scholar_ok=True,
))

turuncoglu2013a = DB(WorkUnrelated(
    2013, "Toward self-describing and workflow integrated Earth system models: A coupled atmosphere-ocean modeling system application",
    due="Unrelated to scripts",
    display="turuncoglu",
    authors="Turuncoglu, Ufuk Utku and Dalfes, Nuzhet and Murphy, Sylvia and Deluca, Cecelia",
    place=EMS,
    file="Turuncoglu2013a.pdf",
    scholar="http://scholar.google.com/scholar?cites=16342325428759923996&as_sdt=2005&sciodt=0,5&hl=en",
    pp="247--262",
    entrytype="article",
    publisher="Elsevier",
    cluster_id="16342325428759923996",
    volume="39",
    ID="turuncoglu2013toward",
    scholar_ok=True,
))

venables2013a = DB(WorkUnrelated(
    2013, "S programming",
    due="Unrelated to provenance. Describes S",
    display="venables",
    authors="Venables, William and Ripley, Brian D",
    place=Book,
    file="Venables2013a.pdf",
    cluster_id="1533291969038413514",
    ID="venables2013s",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=1533291969038413514&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Springer Science & Business Media",
    scholar_ok=True,
))

venables2013b = DB(WorkUnrelated(
    2013, "Modern applied statistics with S-PLUS",
    due="Unrelated to provenance",
    display="venables",
    authors="Venables, William N and Ripley, Brian D",
    place=Book,
    file="Venables2013b.pdf",
    cluster_id="203616146465306064",
    ID="venables2013modern",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=203616146465306064&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Springer Science & Business Media",
    scholar_ok=True,
))

vlieg2013a = DB(WorkUnrelated(
    2013, "DataStewardship in the Big Data Era: Taking Care of Data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="vlieg",
    authors="J. de Vlieg, R. van Schaik, P. Aerts, S. Lusher, and F. Sienstra",
    place=TechReport,
    local="Netherlands eSciece Center",
    file="Vlieg2013a.pdf",
    scholar_ok="impossible",
))

vries2013a = DB(WorkUnrelated(
    2013, "A fast approximation of the Weisfeiler-Lehman graph kernel for RDF data",
    due="Unrelated to provenance. Unrelated to scripts",
    may_be_related_to=["semantic web"],
    display="vries",
    authors="de Vries, Gerben KD",
    place=ECML_PKDD,
    file="Vries2013a.pdf",
    proceedings="LNCS 8188",
    pp="606--621",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=18166480655783223020&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="18166480655783223020",
    scholar_ok=True,
))

wallis2013a = DB(WorkUnrelated(
    2013, "If we share data, will anyone use them? Data sharing and reuse in the long tail of science and technology",
    due="Unrelated to provenance",
    display="wallis",
    authors="Wallis, Jillian C and Rolando, Elizabeth and Borgman, Christine L",
    place=PLOSOne,
    file="Wallis2013a.pdf",
    volume="8",
    number="7",
    pp="e67332",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=13323514014408206690&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Public Library of Science",
    cluster_id="13323514014408206690",
    scholar_ok=True,
))

winawer2013a = DB(WorkUnrelated(
    2013, "Asynchronous broadband signals are the principal source of the BOLD response in human visual cortex",
    due="Unrelated to scripts. Unrelated to provenance",
    display="winawer",
    authors="Winawer, Jonathan and Kay, Kendrick N and Foster, Brett L and Rauschecker, Andreas M and Parvizi, Josef and Wandell, Brian A",
    place=CurrBio,
    scholar="http://scholar.google.com/scholar?cites=8631060165398750070&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1145--1153",
    cluster_id="8631060165398750070",
    volume="23",
    entrytype="article",
    link="http://www.sciencedirect.com/science/article/pii/S0960982213005642",
    file="Winawer2013a.pdf",
    publisher="Elsevier",
    number="13",
    ID="winawer2013asynchronous",
    scholar_ok=True,
))

wolstencroft2013a = DB(WorkUnrelated(
    2013, "The Taverna workflow suite: designing and executing workflows of Web Services on the desktop, web or in the cloud",
    due="Unrelated to scripts",
    display="taverna",
    authors="Wolstencroft, Katherine and Haines, Robert and Fellows, Donal and Williams, Alan and Withers, David and Owen, Stuart and Soiland-Reyes, Stian and Dunlop, Ian and Nenadic, Aleksandra and Fisher, Paul and others",
    summary="Presents the Taverna workflow tool suite, highlightin new features and developments in the workbench",
    place=NARHAD,
    file="Wolstencroft2013a.pdf",
    volume="W557",
    number="61",
    publisher="Oxford Univ Press",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9170050118345919794&as_sdt=2005&sciodt=0,5&hl=en",
    pp="gkt328",
    cluster_id="9170050118345919794",
    scholar_ok=True,
))

xavier2013a = DB(WorkUnrelated(
    2013, "Performance evaluation of container-based virtualization for high performance computing environments",
    due="Unrelated to provenance",
    display="xavier",
    authors="Xavier, Miguel G and Neves, Marcelo V and Rossi, Fabio D and Ferreto, Tiago C and Lange, Timoteo and De Rose, Cesar AF",
    place=PDP,
    file="Xavier2013a.pdf",
    pp="233--240",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=10923333840681982605&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="10923333840681982605",
    scholar_ok=True,
))

xie2013a = DB(WorkUnrelated(
    2013, "Dynamic Documents with R and knitr",
    due="Unrelated to provenance",
    display="xie",
    authors="Xie, Yihui",
    summary="Proposes a notebook interactive environmnet for R",
    place=Book,
    publisher="CRC Press",
    file="Xie2013a.pdf",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=1723118227528908006&as_sdt=2005&sciodt=0,5&hl=en",
    volume="29",
    cluster_id="1723118227528908006",
    scholar_ok="aprox",
))

xu2013a = DB(WorkUnrelated(
    2013, "Static Slicing for Python First-Class Objects",
    star="[collection][x] Unpredictability of dynamic languages",
    due="Unrelated to provenance. May be used as a technique",
    may_be_related_to=["slicing"],
    summary="""
        Proposts a static program slicing method that works for first class citizen objects in Python
        Functions, classes, modules creates variables
            When a method is called, instance creates dependence to what comes before the ".".
            Classes create an special construction function
        Presents many non-relevant data to experiments
        Presents static dependency graph
    """,
    display="xu",
    authors="Xu, Zhaogui and Qian, Ju and Chen, Lin and Chen, Zhifei and Xu, Baowen",
    place=QSIC,
    local="Nanjing, China",
    file="Xu2013a.pdf",
    pp="117--124",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=11483327292511516735&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="11483327292511516735",
    scholar_ok=True,
))

yin2013a = DB(WorkUnrelated(
    2013, "A fine-grained, customizable debugger for aspect-oriented programming",
    due="Unrelated to provenance",
    display="yin",
    authors="Yin, Haihan and Bockisch, Christoph and Ak{?}it, Mehmet",
    place=TAOSD,
    file="Yin2013a.pdf",
    pp="1--38",
    proceedings="LNCS 7800",
    publisher="Springer",
    entrytype="article",
    cluster_id="6688341791198299614",
    scholar="http://scholar.google.com/scholar?cites=6688341791198299614&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

zohrevandi2013a = DB(WorkUnrelated(
    2013, "The bounded data reuse problem in scientific workflows",
    due="Unrelated to scripts",
    may_be_related_to=["reuse", "workflow"],
    display="zohrevandi",
    authors="Zohrevandi, Mohsen and Bazzi, Rida A",
    place=IPDPS,
    file="Zohrevandi2013a.pdf",
    pp="1051--1062",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=9149613749766582842&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="9149613749766582842",
    scholar_ok=True,
))
