# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


acuna2015a = DB(WorkSnowball( # 2
    2015, "Instrumentation and Trace Analysis for Ad-Hoc Python Workflows in Cloud Environments",
    snowball=datetime(2017, 3, 6),
    display="wise a",
    authors="Acuña, Ruben and Lacroix, Zoé and Bazzi, Rida A",
    place=CLOUD,
    local="New York, USA",
    summary="Describes the collection process of WISE",
    file="Acuna2015a.pdf",
    pp="114--121",
    scholar="http://scholar.google.com/scholar?cites=16129242340949487527&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="16129242340949487527",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="wise2015a",
    tracking="alert",
))

acuna2015b = DB(WorkSnowball( # 1
    2015, "Understanding Legacy Workflows through Runtime Trace Analysis",
    snowball=datetime(2017, 3, 6),
    display="wise c",
    authors="Acuña, Ruben",
    school="ARIZONA STATE UNIVERSITY",
    summary="Proposes a new analysis method for extracting workflow structure at run-time, avoiding issues with dynamics. Summarizes resulting dataflow to help comprehension",
    place=Thesis,
    file="Acuna2015b.pdf",
    scholar="http://scholar.google.com/scholar?cites=7198120874817197049&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7198120874817197049",
    entrytype="mastersthesis",
    scholar_ok=True,
    citation_file="wise2015b",
    tracking="alert",
))

acuna2015c = DB(WorkSnowball( # 1
    2015, "Managing and Documenting Legacy Scientific Workflows",
    snowball=datetime(2017, 3, 6),
    alias=(0, "Access to the Document"),
    display="wise b",
    summary="Maps summarized dataflows to ProtocolDB (manually?)",
    file="Acuna2015c.pdf",
    authors="Acuña, Ruben and Chomilier, Jacques and Lacroix, Zoé",
    place=JIB,
    entrytype="article",
    cluster_id="14727599833713202964",
    scholar="http://scholar.google.com/scholar?cites=14727599833713202964&as_sdt=2005&sciodt=0,5&hl=en",
    number="3",
    pp="277--277",
    volume="12",
    scholar_ok=True,
    citation_file="wise2015c",
    tracking="alert",
))

amstutz2015a = DB(WorkUnrelated(
    2015, "Common Workflow Language",
    due="Unrelated to general purpose scripts. Define a script language for defining workflows",
    may_be_related_to=["workflow"],
    display="amstutz",
    authors="P. Amstutz et al",
    place=Web,
    link="github.com/common-workflow-language",
    entrytype="misc",
    scholar_ok="impossible",
))

balakrishnan2015a = DB(WorkUnrelated(
    2015, "Recent advances in computer architecture: the opportunities and challenges for provenance",
    due="Unrelated to scripts",
    display="balakrishnan",
    authors="Balakrishnan, Nikilesh and Bytheway, Thomas and Carata, Lucian and Chick, Oliver RA and Snee, James and Akoush, Sherif and Sohan, Ripduman and Seltzer, Margo and Hopper, Andy",
    place=TaPP,
    scholar="http://scholar.google.com/scholar?cites=7793114728860047630&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7793114728860047630",
    file="Balakrishnan2015a.pdf",
    ID="balakrishnan2015recent",
    entrytype="inproceedings",
    star="[motivation]",
    scholar_ok=True,
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

banati2015a = DB(WorkUnrelated(
    2015, "Minimal sufficient information about the scientific workflows to create reproducible experiment",
    due="Unrelated to scripts",
    display="banati",
    authors="Bánáti, Anna and Kacsuk, Péter and Kozlovszky, Miklós",
    place=INES,
    scholar="http://scholar.google.com/scholar?cites=17811312074843256473&as_sdt=2005&sciodt=0,5&hl=en",
    pp="189--194",
    cluster_id="17811312074843256473",
    file="Banati2015a.pdf",
    ID="banati2015minimal",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
))

banati2015b = DB(WorkUnrelated(
    2015, "Four level provenance support to achieve portable reproducibility of scientific workflows",
    due="Unrelated to scripts",
    display="banati",
    authors="Bánáti, Anna and Kacsuk, Péter and Kozlovszky, Miklós",
    place=MIPRO,
    scholar="http://scholar.google.com/scholar?cites=258680817159517711&as_sdt=2005&sciodt=0,5&hl=en",
    pp="241--244",
    cluster_id="258680817159517711",
    file="Banati2015b.pdf",
    ID="banati2015four",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
))

bates2015a = DB(WorkBinaryOk(
    2015, "Trustworthy Whole-System Provenance for the Linux Kernel",
    display="bates",
    authors="Bates, Adam M and Tian, Dave and Butler, Kevin RB and Moyer, Thomas",
    place=Security,
    scholar="http://scholar.google.com/scholar?cites=14633765960424456584&as_sdt=2005&sciodt=0,5&hl=en",
    pp="319--334",
    cluster_id="14633765960424456584",
    file="Bates2015a.pdf",
    ID="bates2015trustworthy",
    entrytype="inproceedings",
    scholar_ok=True,
))

benabdelkader2015a = DB(WorkUnrelated(
    2015, "PROV-man: A PROV-compliant toolkit for provenance management",
    due="Unrelated to scripts",
    display="benabdelkader",
    authors="Benabdelkader, Ammar and van Kampen, Antoine AHC and Olabarriaga, Silvia D",
    place=TechReport,
    file="Benabdelkader2015a.pdf",
    entrytype="techreport",
    scholar="http://scholar.google.com/scholar?cites=9593082553722656741&as_sdt=2005&sciodt=0,5&hl=en",
    ID="benabdelkader2015prov",
    institution="PeerJ PrePrints",
    cluster_id="9593082553722656741",
    scholar_ok=True,
))

bhardwaj2015a = DB(WorkUnrelated(
    2015, "Datahub: Collaborative data science & dataset version management at scale",
    due="Unrelated to scripts. Unrelated to provenance",
    display="bhardwaj",
    authors="Bhardwaj, Anant and Bhattacherjee, Souvik and Chavan, Amit and Deshpande, Amol and Elmore, Aaron J and Madden, Samuel and Parameswaran, Aditya G",
    place=CIDR,
    file="Bhardwaj2015a.pdf",
    entrytype="inproceedings",
    cluster_id="9226944536687783316",
    scholar="http://scholar.google.com/scholar?cites=9226944536687783316&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok="check all versions",
))

bhattacherjee2015a = DB(WorkUnrelated(
    2015, "Principles of Dataset Versioning: Exploring the Recreation/Storage Tradeoff",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["evolution"],
    display="bhattacherjee",
    authors="Bhattacherjee, Souvik and Chavan, Amit and Huang, Silu and Deshpande, Amol and Parameswaran, Aditya",
    place=VLDB,
    file="Bhattacherjee2015a.pdf",
    entrytype="inproceedings",
    pp="1346--1357",
    scholar="http://scholar.google.com/scholar?cites=12290003212391965698&as_sdt=2005&sciodt=0,5&hl=en",
    volume="8",
    number="12",
    cluster_id="12290003212391965698",
    publisher="VLDB Endowment",
    scholar_ok=True,
))

buchert2015a = DB(WorkUnrelated(
    2015, "A survey of general-purpose experiment management tools for distributed systems",
    due="Unrelated to scripts",
    display="buchert",
    authors="Buchert, Tomasz and Ruiz, Cristian and Nussbaum, Lucas and Richard, Olivier",
    place=FGCS,
    scholar="http://scholar.google.com/scholar?cites=18217488538984626859&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1--12",
    cluster_id="18217488538984626859",
    file="Buchert2015a.pdf",
    publisher="Elsevier",
    ID="buchert2015survey",
    entrytype="article",
    volume="45",
    scholar_ok=True,
))

buchert2015b = DB(WorkBinaryOk(
    2015, "Towards Complete Tracking of Provenance in Experimental Distributed Systems Research",
    may_be_related_to=["distributed"],
    display="buchert",
    authors="Buchert, Tomasz and Nussbaum, Lucas and Gustedt, Jens",
    place=EuroPar,
    pp="604--616",
    file="Buchert2015b.pdf",
    ID="buchert2015towards",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
))

burkhart2015a = DB(WorkUnrelated(
    2015, "No more Believe Me: Make Your Informatics Experiments Reproducible?",
    due="Unrelated to scripts. Unrelated to provenance",
    display="burkhart",
    authors="Burkhart, Helmar and Guerrera, Danilo and Maffia, Antonio",
    place=ECCS,
    file="Burkhart2015a.pdf",
    entrytype="article",
    ID="burkhartno",
    star="[motivation]",
    scholar_ok=True,
))

chavan2015a = DB(WorkUnrelated(
    2015, "Towards a unified query language for provenance and versioning",
    due="Unrelated to scripts",
    star="[analysis][x] Cites query languages used for provenance: SQL, Prolog, SPARQL, QLP, PQL, ProQL",
    display="chavan",
    authors="Chavan, Amit and Huang, Silu and Deshpande, Amol and Elmore, Aaron and Madden, Samuel and Parameswaran, Aditya",
    summary="Proposes an unified query language (VQuel) for provenance, versioning and data",
    place=TaPP,
    pp="1--6",
    file="Chavan2015a.pdf",
    cluster_id="6433412011564414762",
    scholar="http://scholar.google.com/scholar?cites=6433412011564414762&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

collberg2015a = DB(WorkUnrelated(
    2015, "Repeatability and Benefaction in Computer Systems Research: A Study and a Modest Proposal",
    due="Excluding TechReport",
    display="collberg",
    authors="Collberg, C and Proebsting, T and Warren, AM",
    place=TechReport,
    file="Collberg2015a.pdf",
    local="University of Arizona",
    entrytype="article",
    cluster_id="11447333951436638242",
    scholar="http://scholar.google.com/scholar?cites=11447333951436638242&as_sdt=2005&sciodt=0,5&hl=en",
    pp="14--04",
    scholar_ok=True,
))

cooper2015a = DB(WorkUnrelated(
    2015, "A call for virtual experiments: accelerating the scientific process",
    due="Unrelated to provenance",
    display="cooper",
    authors="Cooper, Jonathan and Vik, Jon Olav and Waltemath, Dagmar",
    place=PBMB,
    scholar="http://scholar.google.com/scholar?cites=16937342313628537286&as_sdt=2005&sciodt=0,5&hl=en",
    pp="99--106",
    cluster_id="16937342313628537286",
    volume="117",
    entrytype="article",
    ID="cooper2015call",
    file="Cooper2015a.pdf",
    publisher="Elsevier",
    number="1",
    scholar_ok=True,
))

courtes2015a = DB(WorkUnrelated(
    2015, "Reproducible and User-Controlled Software Environments in HPC with Guix",
    due="Unrelated to provenance",
    display="courtes",
    authors="Courtès, Ludovic and Wurmus, Ricardo",
    place=EuroPar,
    scholar="http://scholar.google.com/scholar?cites=1749526951815061735&as_sdt=2005&sciodt=0,5&hl=en",
    pp="579--591",
    cluster_id="1749526951815061735",
    file="Courtes2015a.pdf",
    ID="courtes2015reproducible",
    organization="Springer",
    entrytype="inproceedings",
    summary="Use pure functions to define build dependencies",
    scholar_ok=True,
))

crankshaw2015a = DB(WorkUnrelated(
    2015, "The missing piece in complex analytics: Low latency, scalable model management and serving with velox",
    due="Unrelated to scripts. Unrelated to provenance",
    display="crankshaw",
    authors="Crankshaw, Daniel and Bailis, Peter and Gonzalez, Joseph E and Li, Haoyuan and Zhang, Zhao and Franklin, Michael J and Ghodsi, Ali and Jordan, Michael I",
    place=CIDR,
    file="Crankshaw2015a.pdf",
    entrytype="inproceedings",
    cluster_id="9859638658654014609",
    scholar="http://scholar.google.com/scholar?cites=9859638658654014609&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok="check all versions",
))

cuevas2015a = DB(WorkUnrelated(
    2015, "ProvONE: A PROV Extension Data Model for Scientific Workflow Provenance",
    due="Unrelated to scripts",
    may_be_related_to=["model"],
    display="cuevas",
    authors="Cuevas-Vicenttin, Victor and Ludäscher, Bertram and Missier, Paolo and Belhajjame, Khalid and Chirigati, Fernando and Wei, Yaxing and Dey, Saumen and Kianmajd, Parisa and Koop, David and Bowers, Shawn and Altintas, Ilkay and Jones, Christopher and Jones, Matthew B and Walker, Lauren and Slaughter, Peter and Leinfelder Ben and Cao, Yang",
    place=Web,
    link="https://purl.dataone.org/provone-v1-dev",
    entrytype="misc",
    scholar_ok="impossible",
))

deline2015a = DB(WorkUnrelated(
    2015, "Supporting exploratory data analysis with live programming",
    due="Unrelated to provenance",
    display="deline",
    authors="DeLine, Robert and Fisher, Danyel",
    place=VLHCC,
    publisher="IEEE",
    pp="111--119",
    file="Deline2015a.pdf",
    entrytype="inproceedings",
    cluster_id="18087303585040936066",
    scholar="http://scholar.google.com/scholar?cites=18087303585040936066&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    scholar_ok=True,
))

dey2015a = DB(WorkSnowball( # 5
    2015, "Linking prospective and retrospective provenance in scripts",
    snowball=datetime(2017, 3, 6),
    star2="Majority of scientists still use scripts",
    display="yw*nw",
    authors="Dey, Saumen and Belhajjame, Khalid and Koop, David and Raul, Meghan and Ludäscher, Bertram",
    summary="Proposes YW*NW, but does not implement it",
    place=TaPP,
    pp="1--7",
    file="Dey2015a.pdf",
    cluster_id="15030065999639303489",
    scholar="http://scholar.google.com/scholar?cites=15030065999639303489&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="ywnw2015",
    tracking="alert",
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

dietrich2015a = DB(WorkSnowball( # 6
    2015, "The dataref versuchung: Saving time through better internal repeatability",
    snowball=datetime(2017, 3, 6),
    alias=(0, "The dataref versuchung"),
    display="versuchung",
    authors="Dietrich, Christian and Lohmann, Daniel",
    place=OSR,
    scholar="http://scholar.google.com/scholar?cites=17769532761506572989&as_sdt=2005&sciodt=0,5&hl=en",
    ID="dietrich2015dataref",
    pp="51--60",
    entrytype="article",
    number="1",
    publisher="ACM",
    cluster_id="17769532761506572989",
    acm="http://dl.acm.org/citation.cfm?id=2723880",
    file="Dietrich2015a.pdf",
    volume="49",
    citation_file="versuchung2015",
    scholar_ok=True,
    tracking="alert",
))

donoho2015a = DB(WorkUnrelated(
    2015, "50 years of Data Science",
    due="Unrelated to scripts. Unrelated to provenance",
    display="donoho",
    authors="Donoho, David",
    place=Tukey,
    scholar="http://scholar.google.com/scholar?cites=6949246178251069699&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6949246178251069699",
    file="Donoho2015a.pdf",
    ID="donoho201550",
    entrytype="inproceedings",
    scholar_ok=True,
))

donoho2015b = DB(WorkNoFile(
    2015, "Method and apparatus for certification of facts",
    display="donoho",
    authors="Donoho, David Leigh and Gavish, Matan",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=9243965246472111102&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent App. 14/746,212",
    cluster_id="9243965246472111102",
    month="jun",
    publisher="Google Patents",
    ID="donoho2015method",
    entrytype="misc",
    scholar_ok=True,
))

feitelson2015a = DB(WorkUnrelated(
    2015, "From repeatability to reproducibility and corroboration",
    due="Unrelated to scripts. Unrelated to provenance",
    display="feitelson",
    authors="Feitelson, Dror G",
    place=OSR,
    file="Feitelson2015a.pdf",
    volume="49",
    number="1",
    star="[concepts] describes repretition, replication, reproduction, variation, and corroboration",
    entrytype="article",
    pp="3--11",
    publisher="ACM",
    cluster_id="13471424499605610093",
    scholar="http://scholar.google.com/scholar?cites=13471424499605610093&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

fekete2015a = DB(WorkUnrelated(
    2015, "Managing information for personal goals (vision)",
    due="Unrelated to scripts",
    display="fekete",
    authors="Fekete, Alan and Kay, Judy and Franklin, Michael and Barua, Debjanee and Kummerfeld, Bob",
    place=ICDE,
    scholar="http://scholar.google.com/scholar?cites=3330071269929572162&as_sdt=2005&sciodt=0,5&hl=en",
    pp="30--33",
    cluster_id="3330071269929572162",
    file="Fekete2015a.pdf",
    ID="fekete2015managing",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
))

fisch2015a = DB(WorkUnrelated(
    2015, "Omics Pipe: a community-based framework for reproducible multi-omics data analysis",
    due="Only uses sumatra to collect provenance in predefined workflows",
    display="fisch",
    authors="Fisch, Kathleen M and Meißner, Tobias and Gioia, Louis and Ducom, Jean-Christophe and Carland, Tristan M and Loguercio, Salvatore and Su, Andrew I",
    place=bioinformatics,
    scholar="http://scholar.google.com/scholar?cites=14119327036861800325&as_sdt=2005&sciodt=0,5&hl=en",
    pp="btv061",
    cluster_id="14119327036861800325",
    file="Fisch2015a.pdf",
    publisher="Oxford Univ Press",
    ID="fisch2015omics",
    entrytype="article",
    scholar_ok=True,
))

fomel2015a = DB(WorkUnrelated(
    2015, "Reproducible Research as a Community Effort: Lessons from the Madagascar Project",
    due="Unrelated to provenance collection",
    may_be_related_to=["declarative"],
    display="fomel",
    authors="Fomel, Sergey",
    place=CiSE,
    pp="20--26",
    volume="17",
    file="Fomel2015a.pdf",
    number="1",
    doi="10.1109/MCSE.2014.94",
    month="January",
    entrytype="article",
    publisher="IEEE",
    cluster_id="5377548193496104840",
    scholar="http://scholar.google.com/scholar?cites=5377548193496104840&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

frazer2015a = DB(WorkUnrelated(
    2015, "Workflow Description Language",
    due="Unrelated to general purpose scripts",
    may_be_related_to=["workflow"],
    display="frazer",
    authors="Frazer, Scott and others",
    summary="Proposes a workflow scripting language",
    place=Web,
    link="github.com/broadinstitute/wdl",
    entrytype="misc",
    scholar_ok="impossible",
))

gammack2015a = DB(WorkUnrelated(
    2015, "Provenance tipping point",
    due="Unrelated to scripts",
    display="gammack",
    authors="Gammack, David and Chapman, Adriane",
    place=TaPP,
    scholar="http://scholar.google.com/scholar?cites=15455382438098052247&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="15455382438098052247",
    file="Gammack2015a.pdf",
    ID="gammack2015provenance",
    entrytype="article",
    scholar_ok=True,
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

gligoric2015a = DB(WorkUnrelated(
    2015, "Regression test selection: theory and practice",
    due="Unrelated to provenance",
    display="gligoric",
    authors="Gligoric, Milos Zivko",
    place=Thesis,
    scholar="http://scholar.google.com/scholar?cites=6840883523221754548&as_sdt=2005&sciodt=0,5&hl=en",
    local="University of Illinois at Urbana-Champaign",
    cluster_id="6840883523221754548",
    file="Gligoric2015a.pdf",
    ID="gligoric2015regression",
    entrytype="phdthesis",
    school="University of Illinois at Urbana-Champaign",
    scholar_ok=True,
))

gligoric2015b = DB(WorkUnrelated(
    2015, "Ekstazi: Lightweight test selection",
    due="Unrelated to provenance",
    display="gligoric",
    authors="Gligoric, Milos and Eloussi, Lamyaa and Marinov, Darko",
    place=ICSE,
    scholar="http://scholar.google.com/scholar?cites=12503340320540400580&as_sdt=2005&sciodt=0,5&hl=en",
    pp="713--716",
    cluster_id="12503340320540400580",
    file="Gligoric2015b.pdf",
    ID="gligoric2015ekstazi",
    organization="IEEE Press",
    entrytype="inproceedings",
    scholar_ok=True,
))

gligoric2015c = DB(WorkUnrelated(
    2015, "Practical regression test selection with dynamic file dependencies",
    due="Unrelated to scripts. Unrelated to provenance",
    display="gligoric",
    authors="Gligoric, Milos and Eloussi, Lamyaa and Marinov, Darko",
    place=ISSTA,
    scholar="http://scholar.google.com/scholar?cites=599122233411689449&as_sdt=2005&sciodt=0,5&hl=en",
    pp="211--222",
    cluster_id="599122233411689449",
    file="Gligoric2015c.pdf",
    ID="gligoric2015practical",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

greff2015a = DB(WorkSnowball(
    2015, "Introducing Sacred: A Tool to Facilitate Reproducible Research",
    snowball=datetime(2017, 3, 6),
    display="greff",
    authors="Greff, Klaus and Schmidhuber, Jürgen",
    place=AutoML,
    publisher="International Machine Learning Society",
    file="Greff2015a.pdf",
    pp="1--6",
    local="Lille, France",
    entrytype="inproceedings",
    ID="greffintroducing",
    cluster_id="8959982030194134776",
    scholar="http://scholar.google.com/scholar?cites=8959982030194134776&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
    tracking="alert",
    citation_file="sacred2015",
))

greff2015b = DB(WorkUnrelated(
    2015, "LSTM: A search space odyssey",
    due="Unrelated to provenance",
    display="greff",
    authors="Greff, Klaus and Srivastava, Rupesh K and Koutník, Jan and Steunebrink, Bas R and Schmidhuber, Jürgen",
    place=arXiv,
    number="1503.04069",
    file="Greff2015b.pdf",
    entrytype="article",
    publisher="IEEE",
    cluster_id="15093365660921206170",
    scholar="http://scholar.google.com/scholar?cites=15093365660921206170&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

gu2015a = DB(WorkUnrelated(
    2015, "The Method and System Implementation of Unstructured Data Tracking and Forensics",
    due="Unrelated to scripts",
    may_be_related_to=["security"],
    display="gu",
    authors="Gu, Guangyu and Zhang, Shujuan and Wang, Xuefei and Cai, Xiang and Chen, Sheng",
    place=ATIS,
    file="Gu2015a.pdf",
    pp="359--367",
    organization="Springer",
    ID="gu2015method",
    entrytype="inproceedings",
    scholar_ok=True,
))

hanson2015a = DB(WorkUnrelated(
    2015, "asr-pipeline",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hanson",
    authors="Hanson-Smith, Victor",
    place=Web,
    link="http://github.com/vhsvhs",
    entrytype="misc",
    scholar_ok="impossible",
))

he2015a = DB(WorkUnrelated(
    2015, "Adding geospatial data provenance into SDI: a service-oriented approach",
    due="Unrelated to scripts",
    display="he",
    authors="He, Lianlian and Yue, Peng and Di, Liping and Zhang, Mingda and Hu, Lei",
    place=JSTARS,
    file="He2015a.pdf",
    publisher="IEEE",
    volume="8",
    cluster_id="933493082658222720",
    ID="he2015adding",
    scholar="http://scholar.google.com/scholar?cites=933493082658222720&as_sdt=2005&sciodt=0,5&hl=en",
    number="2",
    entrytype="article",
    pp="926--936",
    scholar_ok=True,
))

hermes2015a = DB(WorkUnrelated(
    2015, "Stimulus dependence of gamma oscillations in human visual cortex",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hermes",
    authors="Hermes, Dora and Miller, KJ and Wandell, BA and Winawer, Jonathan",
    place=CerCor,
    scholar="http://scholar.google.com/scholar?cites=10431854747436392861&as_sdt=2005&sciodt=0,5&hl=en",
    pp="2951--2959",
    cluster_id="10431854747436392861",
    volume="25",
    entrytype="article",
    link="https://academic.oup.com/cercor/article/25/9/2951/2926112/Stimulus-Dependence-of-Gamma-Oscillations-in-Human",
    file="Hermes2015a.pdf",
    publisher="Oxford Univ Press",
    number="9",
    ID="hermes2015stimulus",
    scholar_ok=True,
))

heroux2015a = DB(WorkUnrelated(
    2015, "Editorial: ACM TOMS replicated computational results initiative",
    due="Unrelated to scripts. Unrelated to provenance",
    display="heroux",
    authors="Heroux, Michael A",
    place=TOMS,
    scholar="http://scholar.google.com/scholar?cites=6507369677264660984&as_sdt=2005&sciodt=0,5&hl=en",
    pp="13",
    cluster_id="6507369677264660984",
    number="3",
    file="Heroux2015a.pdf",
    publisher="ACM",
    ID="heroux2015editorial",
    entrytype="article",
    volume="41",
    excerpt="Abstract The scientific community relies on the peer review process for assuring the quality of published material, the goal of which is to build a body of work we can trust. Computational journals such as the ACM Transactions on Mathematical Software (TOMS) ",
    scholar_ok=True,
))

hinsen2015a = DB(WorkUnrelated(
    2015, "ActivePapers: a platform for publishing and archiving computer-aided research",
    due="Unrelated to provenance collection. Requires users to specify package",
    display="hinsen",
    authors="Hinsen, Konrad",
    place=F1000Research,
    doi="10.12688/f1000research.5773.3",
    month="July",
    link="https://f1000research.com/articles/3-289/v3",
    scholar="https://scholar.google.com/scholar?cites=87769194199729552&as_sdt=2005&sciodt=0,5&hl=en",
    volume="3",
    file="Hinsen2015a.pdf",
    number="289",
    entrytype="article",
    scholar_ok=True,
))

hjorth2015a = DB(WorkUnrelated(
    2015, "Quantitative assessment of computational models for retinotopic map formation",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hjorth",
    authors="Hjorth, JJ and Sterratt, David C and Cutts, Catherine S and Willshaw, David J and Eglen, Stephen J",
    place=DevNeurobiol,
    scholar="http://scholar.google.com/scholar?cites=758054442379666089&as_sdt=2005&sciodt=0,5&hl=en",
    pp="641--666",
    cluster_id="758054442379666089",
    number="6",
    file="Hjorth2015a.pdf",
    publisher="Wiley Online Library",
    ID="hjorth2015quantitative",
    entrytype="article",
    link="http://onlinelibrary.wiley.com/doi/10.1002/dneu.22241/full",
    volume="75",
    scholar_ok=True,
))

hoffmann2015a = DB(WorkUnrelated(
    2015, "Experiences with Software-based Soft-Error Mitigation using AN-Codes",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hoffmann",
    authors="Hoffmann, Martin and Ulbrich, Peter and Dietrich, Christian and Schirmeier, Horst and Lohmann, Daniel and Schröder-Preikschat, Wolfgang",
    place=SQJ,
    file="Hoffmann2015a.pdf",
    entrytype="article",
    pp="87--113",
    scholar="http://scholar.google.com/scholar?cites=9600073738821004566&as_sdt=2005&sciodt=0,5&hl=en",
    volume="24",
    number="1",
    cluster_id="9600073738821004566",
    publisher="Springer",
    scholar_ok=True,
))

hutton2015a = DB(WorkUnrelated(
    2015, "Making social media research reproducible",
    due="Unrelated to scripts",
    display="hutton",
    authors="Hutton, Luke and Henderson, Tristan",
    place=ICWSM,
    scholar="http://scholar.google.com/scholar?cites=10133659392578409432&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="10133659392578409432",
    file="Hutton2015a.pdf",
    ID="hutton2015making",
    organization="Association for the Advancement of Artificial Intelligence",
    entrytype="inproceedings",
    star="[motivation]",
    scholar_ok=True,
))

hutton2015b = DB(WorkUnrelated(
    2015, "Applying contextual integrity to the study of social network sites",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hutton",
    authors="Hutton, Luke",
    place=Thesis,
    file="Hutton2015b.pdf",
    entrytype="phdthesis",
    ID="hutton2015applying",
    local="University of St Andrews",
    school="University of St Andrews",
    scholar_ok=True,
))

interlandi2015a = DB(WorkUnrelated(
    2015, "Titian: Data provenance support in spark",
    due="Unrelated to scripts",
    may_be_related_to=["database"],
    display="interlandi",
    authors="Interlandi, Matteo and Shah, Kshitij and Tetali, Sai Deep and Gulzar, Muhammad Ali and Yoo, Seunghyun and Kim, Miryung and Millstein, Todd and Condie, Tyson",
    place=VLDB,
    number="3",
    file="Interlandi2015a.pdf",
    volume="9",
    link="http://www.vldb.org/pvldb/vol9/p216-interlandi.pdf",
    entrytype="inproceedings",
    pp="216--227",
    publisher="VLDB Endowment",
    cluster_id="7502235717765838171",
    scholar="http://scholar.google.com/scholar?cites=7502235717765838171&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

jenness2015a = DB(WorkUnrelated(
    2015, "Learning from 25 years of the extensible N-Dimensional Data Format",
    due="Unrelated to scripts. Unrelated to provenance",
    display="jenness",
    authors="Jenness, Tim and Berry, David S and Currie, Malcolm J and Draper, Peter W and Economou, Frossie and Gray, Norman and McIlwrath, Brian and Shortridge, Keith and Taylor, Mark B and Wallace, Patrick T and others",
    place=AstronComput,
    scholar="http://scholar.google.com/scholar?cites=8025797038648788205&as_sdt=2005&sciodt=0,5&hl=en",
    pp="146--161",
    cluster_id="8025797038648788205",
    file="Jenness2015a.pdf",
    publisher="Elsevier",
    ID="jenness2015learning",
    entrytype="article",
    volume="12",
    scholar_ok=True,
))

jimenez2015a = DB(WorkUnrelated(
    2015, "Tackling the Reproducibility Problem in Systems Research with Declarative Experiment Specifications",
    due="Unrelated to scripts. ",
    display="jimenez",
    authors="Jimenez, Ivo and Maltzahn, Carlos and Lofstead, Jay and Moody, Adam and Mohror, Kathryn and Arpaci-Dusseau, Remzi and Arpaci-Dusseau, Andrea",
    place=TechReport,
    entrytype="techreport",
    institution="Lawrence Livermore National Laboratory (LLNL), Livermore, CA",
    file="Jimenez2015a.pdf",
    ID="jimenez2015tackling",
    summary="Declarative provenance",
    scholar_ok=True,
))

jimenez2015b = DB(WorkUnrelated(
    2015, "Tackling the Reproducibility Problem in Systems Research with Declarative Experiment Specifications",
    due="Unrelated to scripts",
    display="jimenez b",
    authors="Jimenez, Ivo and Maltzahn, Carlos and Lofstead, Jay and Moody, Adam and Mohror, Kathryn and Arpaci-Dusseau, Remzi and Arpaci-Dusseau, Andrea",
    place=PDSW,
    entrytype="inproceedings",
    cluster_id="3618973287580453722",
    ID="jimenez2015tackling",
    pp="25--30",
    file="Jimenez2015b.pdf",
    summary="Declarative provenance",
    scholar="http://scholar.google.com/scholar?cites=3618973287580453722&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

kandogan2015a = DB(WorkUnrelated(
    2015, "LabBook: Metadata-driven social collaborative data analysis",
    due="Unrelated to scripts",
    display="kandogan",
    authors="Kandogan, Eser and Roth, Mary and Schwarz, Peter and Hui, Joshua and Terrizzano, Ignacio and Christodoulakis, Christina and Miller, Renée J",
    place=BigData,
    file="Kandogan2015a.pdf",
    entrytype="inproceedings",
    organization="IEEE",
    pp="431--440",
    cluster_id="6132262594133191688",
    scholar="http://scholar.google.com/scholar?cites=6132262594133191688&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

khan2015a = DB(WorkUnrelated(
    2015, "Lossless graph summarization using dense subgraphs discovery",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["summarization", "visualization"],
    display="khan",
    authors="Khan, Kifayat Ullah and Nawaz, Waqas and Lee, Young-Koo",
    place=IMCOM,
    file="Khan2015a.pdf",
    pp="9",
    entrytype="inproceedings",
    cluster_id="6866862383897173408",
    scholar="http://scholar.google.com/scholar?cites=6866862383897173408&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

kumar2015a = DB(WorkUnrelated(
    2015, "Model selection management systems: The next frontier of advanced analytics",
    due="Unrelated to scripts",
    display="kumar",
    authors="Kumar, Arun and McCann, Robert and Naughton, Jeffrey and Patel, Jignesh M",
    place=SIGMOD_REC,
    file="Kumar2015a.pdf",
    entrytype="article",
    pp="17--22",
    scholar="http://scholar.google.com/scholar?cites=15338197344175892189&as_sdt=2005&sciodt=0,5&hl=en",
    volume="44",
    number="4",
    cluster_id="15338197344175892189",
    publisher="ACM",
    scholar_ok=True,
))

kumar2015b = DB(WorkUnrelated(
    2015, "Learning generalized linear models over normalized data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="kumar",
    authors="Kumar, Arun and Naughton, Jeffrey and Patel, Jignesh M",
    place=SIGMOD,
    file="Kumar2015b.pdf",
    entrytype="inproceedings",
    organization="ACM",
    pp="1969--1984",
    cluster_id="12655618043613959344",
    scholar="http://scholar.google.com/scholar?cites=12655618043613959344&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

lazzarato2015a = DB(WorkUnrelated(
    2015, "Department of Computing and Software",
    due="Unrelated to scripts. Unrelated to provenance",
    display="lazzarato",
    authors="Lazzarato, A and Smith, S and Carette, J",
    place=TechReport,
    file="Lazzarato2015a.pdf",
    entrytype="article",
    ID="lazzarato2015department",
    scholar_ok=True,
))

lefebvre2015a = DB(WorkUnrelated(
    2015, "Reproducible Research and Interactive Data Mining in Bioinformatics",
    due="Unrelated to provenance",
    display="lefebvre",
    authors="Lefebvre, AE",
    place=Thesis,
    entrytype="mastersthesis",
    ID="lefebvre2015reproducible",
    file="Lefebvre2015a.pdf",
    scholar_ok=True,
))

likamwa2015a = DB(WorkUnrelated(
    2015, "Starfish: Efficient concurrency support for computer vision applications",
    due="Unrelated to scripts. Unrelated to provenance",
    display="likamwa",
    authors="LiKamWa, Robert and Zhong, Lin",
    place=MobiSys,
    scholar="http://scholar.google.com/scholar?cites=11787207580199911011&as_sdt=2005&sciodt=0,5&hl=en",
    pp="213--226",
    cluster_id="11787207580199911011",
    file="Likamwa2015a.pdf",
    ID="likamwa2015starfish",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

liu2015a = DB(WorkUnrelated(
    2015, "Using provenance to efficiently improve metadata searching performance in storage systems",
    due="Unrelated to scripts",
    may_be_related_to=["storage"],
    display="liu",
    authors="Liu, Jinjun and Feng, Dan and Hua, Yu and Peng, Bin and Nie, Zhenhua",
    place=FGCS,
    volume="50",
    scholar="http://scholar.google.com/scholar?cites=3025304908464127383&as_sdt=2005&sciodt=0,5&hl=en",
    ID="liu2015using",
    cluster_id="3025304908464127383",
    publisher="Elsevier",
    pp="99--110",
    entrytype="article",
    file="Liu2015a.pdf",
    scholar_ok=True,
))

liu2015b = DB(WorkUnrelated(
    2015, "A Survey of Data-Intensive Scientific Workflow Management",
    due="Unrelated to scripts",
    may_be_related_to=["workflow", "survey"],
    display="liu",
    authors="Liu, Ji and Pacitti, Esther and Valduriez, Patrick and Mattoso, Marta",
    place=JGCOAP,
    volume="13",
    number="4",
    pp="457--493",
    scholar="http://scholar.google.com/scholar?cites=2917160933620656357&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="2917160933620656357",
    publisher="Springer",
    entrytype="article",
    file="Liu2015b.pdf",
    scholar_ok=True,
))


mahadev2015a = DB(WorkUnrelated(
    2015, "One-Click Time Travel",
    due="Unrelated to provenance",
    display="mahadev",
    authors="Mahadev Satyanarayanan, Gloriana St Clair and Gilbert, Benjamin and Abe, Yoshihisa and Harkes, Jan and Ryan, Dan and Linke, Erika and Webster, Keith",
    place=TechReport,
    scholar="http://scholar.google.com/scholar?cites=8748742812910378844&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="8748742812910378844",
    institution="Technical report, Computer Science, Carnegie Mellon University",
    file="Mahadev2015a.pdf",
    ID="mahadev2015one",
    entrytype="techreport",
    summary="Allows remote access to VMs",
    excerpt="Abstract We describe a system called Olive that freezes and precisely reproduces the environment necessary to execute software long after its creation. It uses virtual machine (VM) technology to encapsulate legacy software, complete with all its software ",
    scholar_ok=True,
))

mattoso2015a = DB(WorkUnrelated(
    2015, "Dynamic steering of HPC scientific workflows: A survey",
    due="Unrelated to scripts",
    may_be_related_to=["survey"],
    display="mattoso",
    authors="Mattoso, Marta and Dias, Jonas and Ocaña, Kary ACS and Ogasawara, Eduardo and Costa, Flavio and Horta, Felipe and Silva, Vítor and de Oliveira, Daniel",
    place=FGCS,
    volume="46",
    pp="100--113",
    publisher="Elsevier",
    organization="Elsevier",
    scholar="http://scholar.google.com/scholar?cites=6213305526046399686&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6213305526046399686",
    file="Mattoso2015a.pdf",
    entrytype="article",
    scholar_ok=True,
))


mcdougal2015a = DB(WorkUnrelated(
    2015, "ModelView for ModelDB: online presentation of model structure",
    due="Unrelated to provenance",
    display="mcdougal",
    authors="McDougal, Robert A and Morse, Thomas M and Hines, Michael L and Shepherd, Gordon M",
    place=Neuroinformatics,
    scholar="http://scholar.google.com/scholar?cites=17892731943458853236&as_sdt=2005&sciodt=0,5&hl=en",
    pp="459--470",
    cluster_id="17892731943458853236",
    volume="13",
    entrytype="article",
    link="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4618280/",
    file="Mcdougal2015a.pdf",
    publisher="Springer",
    number="4",
    ID="mcdougal2015modelview",
    scholar_ok=True,
))

mcphillips2015a = DB(WorkSnowball( # 23
    2015, "YesWorkflow: a user-oriented, language-independent tool for recovering workflow information from scripts",
    snowball=datetime(2017, 3, 6),
    display="yesworkflow a",
    authors="McPhillips, Timothy and Song, Tianhong and Kolisnik, Tyler and Aulenbach, Steve and Belhajjame, Khalid and Bocinsky, Kyle and Cao, Yang and Chirigati, Fernando and Dey, Saumen and Freire, Juliana and others",
    summary="Proposes YesWorkflow with prospective collection and 3 visualizations",
    place=IJDC,
    file="McPhillips2015a.pdf",
    file2="mcphillips2015a2.pdf",
    volume="10",
    number="1",
    pp="298--313",
    doi="10.2218/ijdc.v10i1.370",
    arxiv="1502.02403",
    scholar="http://scholar.google.com/scholar?cites=5400517851889940246&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    cluster_id="5400517851889940246",
    scholar_ok=True,
    citation_file="yesworkflow2015a",
    tracking="alert",
))

mcphillips2015b = DB(WorkSnowball( # 8
    2015, "Retrospective provenance without a runtime provenance recorder",
    snowball=datetime(2017, 3, 6),
    display="yesworkflow b",
    authors="McPhillips, Timothy and Bowers, Shawn and Belhajjame, Khalid and Ludäscher, Bertram",
    summary="Proposes retrospective recorder for YesWorkflow. Presents some queries for retrospective queries",
    place=TaPP,
    pp="1--7",
    file="McPhillips2015b.pdf",
    scholar="http://scholar.google.com/scholar?cites=919541654029050469&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="919541654029050469",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="yesworkflow2015b",
    tracking="alert",
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

meera2015a = DB(WorkUnrelated(
    2015, "A provenance auditing framework for cloud computing systems",
    due="Unrelated to scripts",
    display="meera",
    authors="Meera, G and Geethakumari, G",
    place=SPICES,
    ID="meera2015provenance",
    organization="IEEE",
    pp="1--5",
    entrytype="inproceedings",
    file="Meera2015a.pdf",
    scholar_ok=True,
))

metaxas2015a = DB(WorkUnrelated(
    2015, "Sensing magnetic nanoparticles using nano-confined ferromagnetic resonances in a magnonic crystal",
    due="Unrelated to scripts. Unrelated to provenance",
    display="metaxas",
    authors="Metaxas, Peter J and Sushruth, Manu and Begley, Ryan A and Ding, Junjia and Woodward, Robert C and Maksymov, Ivan S and Albert, Maximilian and Wang, Weiwei and Fangohr, Hans and Adeyeye, Adekunle O and others",
    place=APL,
    scholar="http://scholar.google.com/scholar?cites=2723291275324427082&as_sdt=2005&sciodt=0,5&hl=en",
    pp="232406",
    cluster_id="2723291275324427082",
    number="23",
    file="Metaxas2015a.pdf",
    publisher="AIP Publishing",
    ID="metaxas2015sensing",
    entrytype="article",
    volume="106",
    scholar_ok=True,
))

meyer2015a = DB(WorkSnowball( # 0
    2015, "pypet: a python toolkit for simulations and numerical experiments",
    snowball=datetime(2017, 3, 6),
    display="pypet",
    authors="Meyer, Robert and Obermayer, Klaus",
    place=Neuroscience,
    pp="P184",
    number="Suppl 1",
    file="Meyer2015a.pdf",
    publisher="BioMed Central",
    ID="meyer2015pypet",
    entrytype="article",
    volume="16",
    citation_file="pypet2015",
    cluster_id="3407212500934222712",
    scholar="http://scholar.google.com/scholar?cites=3407212500934222712&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
    tracking="alert",
))

michaelis2015a = DB(WorkUnrelated(
    2015, "Explaining Scientific and Technical Emergence Forecasting",
    alias=(0, "Professor Ozyer", "Michaelis, James"),
    pp="177--192",
    due="Unrelated to scripts",
    display="michaelis",
    authors="Michaelis, James R and McGuinness, Deborah L and Chang, Cynthia and Erickson, John and Hunter, Daniel and Babko-Malaya, Olga",
    bookname="Applications of Social Media and Social Network Analysis",
    place=Book,
    ID="michaelisprofessor",
    entrytype="incollection",
    file="Michaelis2015a.pdf",
    publisher="Springer",
    scholar_ok=True,
))

muller2015a = DB(WorkUnrelated(
    2015, "Novel operation modes of accelerated neuromorphic hardware",
    due="Unrelated to provenance",
    display="muller",
    authors="Müller, Eric Christian",
    place=Thesis,
    scholar="http://scholar.google.com/scholar?cites=5179907879958625318&as_sdt=2005&sciodt=0,5&hl=en",
    local="Ruprecht-Karls-Universität Heidelberg",
    cluster_id="5179907879958625318",
    file="Muller2015a.pdf",
    ID="muller2015novel",
    entrytype="phdthesis",
    school="Ruprecht-Karls-Universität Heidelberg",
    scholar_ok=True,
))

muller2015b = DB(WorkUnrelated(
    2015, "Python in neuroscience",
    due="Unrelated to provenance",
    display="muller",
    authors="Muller, Eilif and Bednar, James A and Diesmann, Markus and Gewaltig, Marc-Oliver and Hines, Michael and Davison, Andrew P",
    place=FNInf,
    link="http://journal.frontiersin.org/article/10.3389/fninf.2015.00011/full",
    number="11",
    volume="9",
    doi="10.3389/fninf.2015.00011",
    file="Muller2015b.pdf",
    entrytype="article",
    scholar="https://scholar.google.com/scholar?cites=9352697825788047230&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

nascimento2015a = DB(WorkLang(
    2015, "RFlow: uma arquitetura para execução e coleta de proveniência de workflows estatísticos",
    aliases=[
        (0, "INSTITUTO DE CIÊNCIA EXATAS CURSO DE PÓS-GRADUA{Ç}ÃO EM MODELAGEM MATEMÁTICA E COMPUTACIONAL"),
        (0, "RFlow: uma arquitetura para proveniência de workflows estatísticos", "do Nascimento, José Antônio Pires and da Cruz, Sérgio Manuel Serra"),
    ],
    display="do nascimento",
    authors="do Nascimento, José Antônio Pires",
    entrytype="phdthesis",
    place=Thesis,
    file="Nascimento2015a.pdf",
    scholar="https://scholar.google.com/scholar?cites=10877308601694859670&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

north2015a = DB(WorkUnrelated(
    2015, "Collaborative visual analysis with RCloud",
    due="Unrelated to provenance. Its versioning scheme may be used for provenance, though",
    display="RCloud",
    may_be_related_to=["versioning", "notebook"],
    summary="Creates a new version for each cell execution",
    authors="North, Stephen and Scheidegger, Carlos and Urbanek, Simon and Woodhull, Gordon",
    pp="25--32",
    place=VAST,
    file="North2015a.pdf",
    organization="IEEE",
    ID="north2015collaborative",
    entrytype="inproceedings",
    scholar_ok=True,
))

nowke2015a = DB(WorkUnrelated(
    2015, "Integrating visualizations into modeling NEST simulations",
    due="Unrelated to scripts. Unrelated to provenance",
    display="nowke",
    authors="Nowke, Christian and Zielasko, Daniel and Weyers, Benjamin and Peyser, Alexander and Hentschel, Bernd and Kuhlen, Torsten W",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=15627701232052398180&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="15627701232052398180",
    file="Nowke2015a.pdf",
    publisher="Frontiers Media SA",
    ID="nowke2015integrating",
    entrytype="article",
    volume="9",
    scholar_ok=True,
))

nuzzo2015a = DB(WorkUnrelated(
    2015, "How scientists fool themselves-and how they can stop",
    due="Unrelated to provenance. Unrelated to scripts",
    display="nuzzo",
    authors="Nuzzo, Regina",
    place=Nature,
    file="Nuzzo2015a.pdf",
    volume="526",
    number="7572",
    pp="182--185",
    entrytype="article",
    cluster_id="10078091972837677631",
    scholar="http://scholar.google.com/scholar?cites=10078091972837677631&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

ocana2015a = DB(WorkUnrelated(
    2015, "Data Analytics in Bioinformatics: Data Science in Practice for Genomics Analysis Workflows",
    due="Unrelated to scripts collection",
    display="ocana",
    authors="Ocaña, Kary ACS and Silva, Vítor and De Oliveira, Daniel and Mattoso, Marta",
    place=eSoN,
    file="Ocana2015a.pdf",
    pp="322--331",
    entrytype="inproceedings",
    organization="IEEE",
    scholar_ok=True,
))

oliveira2015a = DB(WorkUnrelated(
    2015, "How much domain data should be in provenance databases?",
    due="Unrelated to scripts",
    display="oliveira",
    authors="De Oliveira, Daniel and Silva, Vítor and Mattoso, Marta",
    place=TaPP,
    scholar="http://scholar.google.com/scholar?cites=17499081021729932862&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="17499081021729932862",
    file="Oliveira2015a.pdf",
    ID="de2015much",
    entrytype="inproceedings",
    scholar_ok=True,
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

padhy2015a = DB(WorkUnrelated(
    2015, "Brown Dog: Leveraging everything towards autocuration",
    due="Unrelated to provenance, Unrelated to scripts",
    display="padhy",
    authors="Padhy, Smruti and Jansen, Greg and Alameda, Jay and Black, Edgar and Diesendruck, Liana and Dietze, Mike and Kumar, Praveen and Kooper, Rob and Lee, Jong and Liu, Rui and others",
    place=BigData,
    scholar="http://scholar.google.com/scholar?cites=2747495228830409874&as_sdt=2005&sciodt=0,5&hl=en",
    pp="493--500",
    cluster_id="2747495228830409874",
    file="Padhy2015a.pdf",
    ID="padhy2015brown",
    organization="IEEE",
    entrytype="inproceedings",
    summary="Extracts metadata from files. For instance, in a image, it extracts the resolution, the color channel, the format, and some statistics",
    scholar_ok=True,
))

pienta2015a = DB(WorkUnrelated(
    2015, "Scalable graph exploration and visualization: Sensemaking challenges and opportunities",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["visualization"],
    display="pienta",
    authors="Pienta, Robert and Abello, James and Kahng, Minsuk and Chau, Duen Horng",
    place=BIGCOMP,
    file="Pienta2015a.pdf",
    local="Jeju, South Korea",
    pp="271--278",
    entrytype="inproceedings",
    cluster_id="16811142111461849691",
    scholar="http://scholar.google.com/scholar?cites=16811142111461849691&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    scholar_ok=True,
))

pimentel2015a = DB(WorkSnowball( # 3
    2015, "Collecting and analyzing provenance on interactive notebooks: when IPython meets noWorkflow",
    snowball=datetime(2017, 3, 6),
    display="noworkflow",
    authors="Pimentel, João Felipe Nicolaci and Braganholo, Vanessa and Murta, Leonardo and Freire, Juliana",
    summary="Proposes provenance collection on IPython Notebooks",
    place=TaPP,
    file="Pimentel2015a.pdf",
    cluster_id="4219830629708722478",
    scholar="http://scholar.google.com/scholar?cites=4219830629708722478&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="noworkflow2015",
    tracking="alert",
    publisher="USENIX",
    local="Edinburgh, Scotland",
    pp="1--6",
))

pinandito2015a = DB(WorkUnrelated(
    2015, "Web-Based Implementation of Travelling Salesperson Problem Using Genetic Algorithm",
    due="Unrelated to scripts. Unrelated to provenance",
    display="pinandito",
    authors="Pinandito, Aryo and Yudistira, Novanto and Pradana, Fajar",
    place=Unpublished,
    ID="pinanditoweb",
    entrytype="article",
    file="Pinandito2015a.pdf",
    scholar_ok=True,
))

poldrack2015a = DB(WorkUnrelated(
    2015, "The publication and reproducibility challenges of shared data",
    due="Unrelated to scripts",
    may_be_related_to=["reproducibility"],
    display="poldrack",
    authors="Poldrack, Russell A and Poline, Jean-Baptiste",
    place=TiCS,
    scholar="http://scholar.google.com/scholar?cites=14377160719581586146&as_sdt=2005&sciodt=0,5&hl=en",
    star="[motivation]",
    ID="poldrack2015publication",
    pp="59--61",
    entrytype="article",
    number="2",
    publisher="Elsevier",
    cluster_id="14377160719581586146",
    file="Poldrack2015a.pdf",
    volume="19",
    scholar_ok=True,
))

proebsting2015a = DB(WorkUnrelated(
    2015, "Repeatability and benefaction in computer systems research",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["reproducibility"],
    display="proebsting",
    authors="Proebsting, Todd and Warren, Alex M",
    place=TechReport,
    scholar="http://scholar.google.com/scholar?cites=8783591446081701738&as_sdt=2005&sciodt=0,5&hl=en",
    institution="Technical report, Univ. of Arizona TR 14-04",
    ID="proebsting2015repeatability",
    entrytype="techreport",
    file="Proebsting2015a.pdf",
    star="[survey]",
    cluster_id="8783591446081701738",
    scholar_ok=True,
))

rossiter2015a = DB(WorkUnrelated(
    2015, "Simulation design: Trans-paradigm best-practice from software engineering",
    due="Unrelated to scripts",
    display="rossiter",
    authors="Rossiter, Stuart",
    place=JArtifSocSoc,
    scholar="http://scholar.google.com/scholar?cites=4445963084157282641&as_sdt=2005&sciodt=0,5&hl=en",
    pp="9",
    cluster_id="4445963084157282641",
    volume="18",
    entrytype="article",
    link="http://jasss.soc.surrey.ac.uk/18/3/9.html",
    file="Rossiter2015a.pdf",
    number="3",
    ID="rossiter2015simulation",
    scholar_ok=True,
))

ruprecht2015a = DB(WorkUnrelated(
    2015, "Lightweight Extraction of Variability Information from Linux Makefiles",
    due="Unrelated to provenance",
    display="ruprecht",
    authors="Ruprecht, Andreas",
    place=Thesis,
    link="https://www4.cs.fau.de/Ausarbeitung/MA-I4-2015-01-Ruprecht.pdf",
    entrytype="phdthesis",
    cluster_id="1485802125326181002",
    ID="ruprecht2015lightweight",
    file="Ruprecht2015a.pdf",
    scholar="http://scholar.google.com/scholar?cites=1485802125326181002&as_sdt=2005&sciodt=0,5&hl=en",
    local="MA thesis. University of Erlangen, Dept. of Computer Science, 2015. URL: https://www4. cs. fau. de/Ausarbeitung/MA-I4-2015-01-Ruprecht. pdf",
    school="University of Erlangen",
    scholar_ok=True,
))

santana2015a = DB(WorkUnrelated(
    2015, "Towards reproducibility in scientific workflows: An infrastructure-based approach",
    due="Unrelated to scripts",
    display="santana",
    authors="Santana-Perez, Idafen and Pérez-Hernández, María S",
    place=SP,
    scholar="http://scholar.google.com/scholar?cites=1327338530625533706&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="1327338530625533706",
    file="Santana2015a.pdf",
    publisher="Hindawi Publishing Corporation",
    ID="santana2015towards",
    entrytype="article",
    star="[collection] users describe architecture",
    volume="2015",
    scholar_ok=True,
))

sarikhani2015a = DB(WorkUnrelated(
    2015, "An Adaptive Provenance Collection Architecture in Scientific Workflow Systems",
    due="Unrelated to scripts",
    display="sarikhani",
    authors="Sarikhani, Mehdi",
    place=Thesis,
    ID="sarikhani2015adaptive",
    entrytype="phdthesis",
    local="The university of Adelaide",
    file="Sarikhani2015a.pdf",
    school="The university of Adelaide",
    scholar_ok=True,
))

simonet2015a = DB(WorkUnrelated(
    2015, "Active Data-Enabling Smart Data Life Cycle Management for Large Distributed Scientific Data Sets",
    due="Unrelated to scripts",
    display="simonet",
    authors="Simonet, Anthony",
    place=Thesis,
    file="Simonet2015a.pdf",
    entrytype="phdthesis",
    ID="simonet2015active",
    local="Ecole normale supérieure de lyon-ENS LYON",
    school="Ecole normale supérieure de lyon-ENS LYON",
    scholar_ok=True,
))

smith2015a = DB(WorkUnrelated(
    2015, "State of Practice for Seismology Software",
    alias=(2004, "Department of Computing and Software", "Smith, S and Chen, CH"),
    due="Unrelated to scripts. Unrelated to provenance",
    display="smith",
    authors="Smith, S and Chen, CH",
    place=TechReport,
    file="Smith2015a.pdf",
    entrytype="article",
    ID="smith2004department",
    scholar_ok="impossible/citation",
))

stamatogiannakis2015a = DB(WorkBinaryOk(
    2015, "Decoupling provenance capture and analysis from execution",
    display="stamatogiannakis",
    authors="Stamatogiannakis, Manolis and Groth, Paul and Bos, Herbert and others",
    place=TaPP,
    scholar="http://scholar.google.com/scholar?cites=13455465902980499401&as_sdt=2005&sciodt=0,5&hl=en",
    star="binary",
    ID="stamatogiannakis2015decoupling",
    entrytype="inproceedings",
    file="Stamatogiannakis2015a.pdf",
    cluster_id="13455465902980499401",
    scholar_ok=True,
    publisher="USENIX",
    local="Edinburgh, Scotland",
))

stockton2015a = DB(WorkBinaryOk(
    2015, "NeuroManager: a workflow analysis based simulation management engine for computational neuroscience",
    may_be_related_to=["jobs"],
    due="Unrelated to scripts. Uses scripts only to manage the execution of jobs. Records simulation outputs, detailed log of activities (machine data, job submission), input parameter vector files, version of NeuroManger, model files",
    display="NeuroManager",
    authors="Stockton, David B and Santamaria, Fidel",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=14001356064675454228&as_sdt=2005&sciodt=0,5&hl=en",
    pp="24",
    cluster_id="14001356064675454228",
    file="Stockton2015a.pdf",
    publisher="Frontiers",
    ID="stockton2015neuromanager",
    entrytype="article",
    link="http://journal.frontiersin.org/article/10.3389/fninf.2015.00024/full",
    volume="9",
    number="24",
    doi="10.3389/fninf.2015.00024",
    scholar_ok=True,
))

stodden2015a = DB(WorkUnrelated(
    2015, "Reproducing statistical results",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["reproducibility"],
    display="stodden",
    authors="Stodden, Victoria",
    place=AnnuRevStatistics,
    scholar="http://scholar.google.com/scholar?cites=18183892928350543025&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1--19",
    cluster_id="18183892928350543025",
    volume="2",
    entrytype="article",
    ID="stodden2015reproducing",
    file="Stodden2015a.pdf",
    publisher="Annual Reviews",
    scholar_ok=True,
))

sultana2015a = DB(WorkNoFile(
    2015, "A distributed system for the management of fine-grained provenance",
    display="sultana",
    authors="Sultana, Salmin and Bertino, Elisa",
    place=JDM,
    number="2",
    volume="26",
    ID="sultana2015distributed",
    cluster_id="1935225820725195397",
    publisher="IGI Global",
    pp="32--47",
    scholar="http://scholar.google.com/scholar?cites=1935225820725195397&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    request="done",
    scholar_ok=True,
))

taddei2015a = DB(WorkBinaryOk(
    2015, "An integrated system for building and running reproducible research",
    display="taddei",
    authors="Taddei, Mario",
    place=Thesis,
    entrytype="phdthesis",
    ID="taddeiintegrated",
    file="Taddei2015a.pdf",
    scholar_ok=True,
))

thain2015a = DB(WorkUnrelated(
    2015, "Techniques for Preserving Scientific Software Executions: Preserve the Mess or Encourage Cleanliness?",
    due="Unrelated to scripts",
    display="thain",
    authors="Thain, Douglas and Ivie, Peter and Meng, Haiyan",
    place=iPRES,
    entrytype="article",
    cluster_id="16142471550918925344",
    ID="thain2015techniques",
    star="[motivation] preservation",
    pp="164",
    file="Thain2015a.pdf",
    scholar="http://scholar.google.com/scholar?cites=16142471550918925344&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

toffola2015a = DB(WorkUnrelated(
    2015, "Performance problems you can fix: A dynamic analysis of memoization opportunities",
    due="Unrelated to scripts",
    may_be_related_to=["memoization"],
    display="toffola",
    authors="Della Toffola, Luca and Pradel, Michael and Gross, Thomas R",
    place=SIGPLAN_NOTICES,
    scholar="http://scholar.google.com/scholar?cites=14703083279276021178&as_sdt=2005&sciodt=0,5&hl=en",
    pp="607--622",
    cluster_id="14703083279276021178",
    number="10",
    file="Toffola2015a.pdf",
    ID="della2015performance",
    organization="ACM",
    entrytype="inproceedings",
    volume="50",
    scholar_ok=True,
))

topalidou2015a = DB(WorkUnrelated(
    2015, "A long journey into reproducible computational neuroscience research",
    due="Unrelated to provenance",
    display="topalidou",
    authors="Topalidou, Meropi and Leblois, Arthur and Boraud, Thomas and Rougier, Nicolas P",
    place=FNCom,
    link="http://journal.frontiersin.org/article/10.3389/fncom.2015.00030/full",
    number="30",
    volume="9",
    doi="10.3389/fncom.2015.00030",
    file="Topalidou2015a.pdf",
    entrytype="article",
    scholar_ok=True,
))

tosta2015a = DB(WorkUnrelated(
    2015, "Improving workflow design by mining reusable tasks",
    may_be_related_to=["workflow", "reuse"],
    due="Unrelated to scripts",
    display="tosta",
    authors="Tosta, Frederico E and Braganholo, Vanessa and Murta, Leonardo and Mattoso, Marta",
    summary="Proposes a workflow recommender that suggsts frequent combinantions of workflow tasks for reuse",
    number="1",
    place=JBCS,
    file="Tosta2015a.pdf",
    pp="1--16",
    publisher="Springer",
    volume="21",
    entrytype="article",
    scholar_ok=True,
))

wang2015a = DB(WorkUnrelated(
    2015, "Big data provenance: Challenges, state of the art and opportunities",
    due="Unrelated to scripts",
    may_be_related_to=["survey"],
    display="wang",
    authors="Wang, Jianwu and Crawl, Daniel and Purawat, Shweta and Nguyen, Mai and Altintas, Ilkay",
    place=BigData,
    publisher="IEEE",
    organization="IEEE",
    pp="2509--2516",
    file="Wang2015a.pdf",
    entrytype="inproceedings",
    cluster_id="16542254766328975406",
    scholar="http://scholar.google.com/scholar?cites=16542254766328975406&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
    local="Santa Clara, USA",
))

yoon2015a = DB(WorkUnrelated(
    2015, "Supporting selective undo in a code editor",
    due="Unrelated to provenance",
    display="yoon",
    authors="Yoon, Young Seok and Myers, Brad A",
    place=ICSE,
    publisher="IEEE Press",
    volume="1",
    pp="223--233",
    file="Yoon2015a.pdf",
    entrytype="inproceedings",
    cluster_id="10427197120085145979",
    scholar="http://scholar.google.com/scholar?cites=10427197120085145979&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE Press",
    scholar_ok=True,
))

yue2015a = DB(WorkUnrelated(
    2015, "Towards intelligent giservices",
    due="Unrelated to scripts",
    display="yue",
    authors="Yue, Peng and Baumann, Peter and Bugbee, Kaylin and Jiang, Liangcun",
    place=ESIN,
    file="Yue2015a.pdf",
    publisher="Springer",
    volume="8",
    cluster_id="1063813904374856064",
    ID="yue2015towards",
    scholar="http://scholar.google.com/scholar?cites=1063813904374856064&as_sdt=2005&sciodt=0,5&hl=en",
    number="3",
    entrytype="article",
    pp="463--481",
    scholar_ok=True,
))

zhu2015a = DB(WorkUnrelated(
    2015, "Integrating spatial data linkage and analysis services in a geoportal for China urban research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="zhu",
    authors="Zhu, Xinyan and She, Bing and Guo, Wei and Bao, Shuming and Chen, Di",
    place=TGIS,
    volume="19",
    ID="zhu2015integrating",
    file="Zhu2015a.pdf",
    scholar="http://scholar.google.com/scholar?cites=10324138724457497467&as_sdt=2005&sciodt=0,5&hl=en",
    number="1",
    publisher="Wiley Online Library",
    pp="107--128",
    entrytype="article",
    cluster_id="10324138724457497467",
    scholar_ok=True,
))

林晨2015a = DB(WorkLang(
    2015, "科学工作流溯源表示和查询技术综述",
    alias=(0, "科学工作流溯源表示和查询技术综述"),
    display="林晨 and 罗万明 and 阎保平",
    authors="林晨 and 罗万明 and 阎保平",
    file="林晨2015a.pdf",
    number="6",
    place=Lang,
    pp="18--32",
    volume="6",
    entrytype="article",
    scholar_ok=True,
))
