# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


allen2014a = DB(WorkUnrelated(
    2014, "Engineering Choices for Open World Provenance",
    due="Unrelated to scripts",
    display="allen",
    authors="Allen, M David and Chapman, Adriane and Blaustein, Barbara",
    place=IPAW,
    local="Cologne, Germany",
    scholar="http://scholar.google.com/scholar?cites=17206134577398191817&as_sdt=2005&sciodt=0,5&hl=en",
    ID="allen2014engineering",
    cluster_id="17206134577398191817",
    organization="Springer",
    pp="242--253",
    entrytype="inproceedings",
    file="Allen2014a.pdf",
    scholar_ok=True,
))

alper2014a = DB(WorkUnrelated(
    2014, "Labelflow: Exploiting workflow provenance to surface scientific data provenance",
    due="Unrelated to scripts",
    may_be_related_to=["annotations", "workflow"],
    display="alper",
    authors="Alper, Pinar and Belhajjame, Khalid and Goble, Carole A and Karagoz, Pinar",
    place=IPAW,
    file="Alper2014a.pdf",
    pp="84--96",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7441599378052610619&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="7441599378052610619",
    scholar_ok=True,
    local="Cologne, Germany",
))

arabas2014a = DB(WorkUnrelated(
    2014, "Case Studies and Challenges in Reproducibility in the Computational Sciences",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["reproducibility"],
    display="arabas",
    authors="Arabas, Sylwester and Bareford, Michael R and de Silva, Lakshitha R and Gent, Ian P and Gorman, Benjamin M and Hajiarabderkani, Masih and Henderson, Tristan and Hutton, Luke and Konovalov, Alexander and Kotthoff, Lars and others",
    place=arXiv,
    scholar="http://scholar.google.com/scholar?cites=11798980431514920984&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11798980431514920984",
    file="Arabas2014a.pdf",
    ID="arabas2014case",
    entrytype="article",
    star="[motivation]",
    scholar_ok=True,
))

baumer2014a = DB(WorkUnrelated(
    2014, "R Markdown: Integrating a reproducible analysis tool into introductory statistics",
    due="Excluding TechReports",
    display="baumer",
    authors="Baumer, Ben and Cetinkaya-Rundel, Mine and Bray, Andrew and Loi, Linda and Horton, Nicholas J",
    place=arXiv,
    file="Baumer2014a.pdf",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=8165264401254668704&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="8165264401254668704",
    scholar_ok=True,
))

bocinsky2014a = DB(WorkUnrelated(
    2014, "A 2,000-year reconstruction of the rain-fed maize agricultural niche in the US Southwest",
    due="Unrelated to provenance. Unrelated to scripts",
    display="bocinsky",
    authors="Bocinsky, R Kyle and Kohler, Timothy A",
    place=Nature,
    file="Bocinsky2014a.pdf",
    volume="5",
    doi="10.1038/ncomms6618",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=12739765745341697529&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Nature Publishing Group",
    cluster_id="12739765745341697529",
    scholar_ok=True,
))

bonet2014a = DB(WorkUnrelated(
    2014, "Documenting, storing, and executing models in Ecology: A conceptual framework and real implementation in a global change monitoring program",
    due="Unrelated to scripts. Unrelated to provenance",
    display="bonet",
    authors="Bonet, Francisco J and Pérez-Pérez, Ramón and Benito, Blas M and De Albuquerque, Fábio Suzart and Zamora, Regino",
    place=EMS,
    volume="52",
    scholar="http://scholar.google.com/scholar?cites=18075879765833681753&as_sdt=2005&sciodt=0,5&hl=en",
    ID="bonet2014documenting",
    cluster_id="18075879765833681753",
    publisher="Elsevier",
    pp="192--199",
    entrytype="article",
    file="Bonet2014a.pdf",
    scholar_ok=True,
))

carata2014a = DB(WorkUnrelated(
    2014, "A primer on provenance",
    due="Unrelated to scripts",
    display="carata",
    authors="Carata, Lucian and Akoush, Sherif and Balakrishnan, Nikilesh and Bytheway, Thomas and Sohan, Ripduman and Seltzer, Margo and Hopper, Andy",
    place=CACM,
    scholar="http://scholar.google.com/scholar?cites=5180840638911745078&as_sdt=2005&sciodt=0,5&hl=en",
    pp="52--60",
    cluster_id="5180840638911745078",
    number="5",
    file="Carata2014a.pdf",
    publisher="ACM",
    ID="carata2014primer",
    entrytype="article",
    star="[motivation][survey]",
    volume="57",
    scholar_ok=True,
))

castilho2014a = DB(WorkUnrelated(
    2014, "Natural language processing: Integration of automatic and manual analysis",
    due="Unrelated to scripts. Unrelated to provenance",
    display="castilho",
    authors="Eckart de Castilho, Richard",
    place=Thesis,
    scholar="http://scholar.google.com/scholar?cites=2128766222279838324&as_sdt=2005&sciodt=0,5&hl=en",
    local="Technische Universität",
    cluster_id="2128766222279838324",
    file="Castilho2014a.pdf",
    ID="eckart2014natural",
    entrytype="phdthesis",
    scholar_ok=True,
))

chen2014a = DB(WorkUnrelated(
    2014, "Dynamic slicing of Python programs",
    due="Unrelated to provenance. Unrelated to scripts",
    may_be_related_to=["slicing"],
    display="chen",
    authors="Chen, Zhifei and Chen, Lin and Zhou, Yuming and Xu, Zhaogui and Chu, William C and Xu, Baowen",
    summary="""
        Performs dynamic slicing over python bytecodes
        Changes CPYthon to extract Bytecode dependencies
        Limitation:
            It is necessary to release a new version when CPython gets updated
    """,
    place=COMPSAC,
    file="Chen2014a.pdf",
    pp="219--228",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=8454838862631529281&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    cluster_id="8454838862631529281",
    scholar_ok=True,
))

chittimalli2014a = DB(WorkUnrelated(
    2014, "Variable provenance in software systems",
    due="Cobol is not a scripting language",
    display="chittimalli",
    authors="Chittimalli, Pavan Kumar and Naik, Ravindra",
    summary="""
        Collects provenance of variables in Cobol to explain them
        Propagates operations and models problem as a data flow analysis problem
        Static analysis
        Presents tooltips indicating the meaning of each variable
    """,
    place=RSSE,
    file="Chittimalli2014a.pdf",
    entrytype="inproceedings",
    organization="ACM",
    pp="9--13",
    scholar_ok=True,
))

claes2014a = DB(WorkUnrelated(
    2014, "Merging event logs for process mining: A rule based merging method and rule suggestion algorithm",
    due="Unrelated to provenance, unrelated to scripts",
    may_be_related_to=["mining"],
    display="claes",
    authors="Claes, Jan and Poels, Geert",
    place=ESA,
    file="Claes2014a.pdf",
    volume="41",
    number="16",
    pp="7291--7306",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=10787569037662136844&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Elsevier",
    cluster_id="10787569037662136844",
    scholar_ok=True,
))

coe2014a = DB(WorkUnrelated(
    2014, "Provenance Datasets Highlighting Capture Disparities",
    due="Unrelated to scripts",
    display="coe",
    authors="Coe, G Blake and Doty, R Christopher and Allen, M David and Chapman, Adriane P",
    place=TechReport,
    star="[survey] capture",
    ID="coe2014provenance",
    cluster_id="5976309133485257293",
    file="Coe2014a.pdf",
    scholar="http://scholar.google.com/scholar?cites=5976309133485257293&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="techreport",
    institution="DTIC Document",
    scholar_ok=True,
))

coe2014b = DB(WorkUnrelated(
    2014, "Provenance Capture Disparities Highlighted through Datasets",
    due="Unrelated to scripts",
    display="coe",
    authors="Coe, G Blake and Doty, R Christopher and Allen, M David and Chapman, Adriane",
    place=TaPP,
    local="Cologne, Germany",
    ID="coe2014provenance",
    cluster_id="3735716868241530079",
    file="Coe2014b.pdf",
    scholar="http://scholar.google.com/scholar?cites=3735716868241530079&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    publisher="USENIX",
))

cohen2014a = DB(WorkUnrelated(
    2014, "Distilling structure in Taverna scientific workflows: a refactoring approach",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="taverna",
    authors="Cohen-Boulakia, Sarah and Chen, Jiuqiang and Missier, Paolo and Goble, Carole and Williams, Alan R and Froidevaux, Christine",
    summary="Proposes an approach to identify anti-patterns on workflows and refactor them",
    place=bioinformatics,
    file="Cohen2014a.pdf",
    volume="15",
    number="1",
    pp="1",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=10357343693383115379&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="BioMed Central",
    cluster_id="10357343693383115379",
    scholar_ok=True,
))

cuevas2014a = DB(WorkUnrelated(
    2014, "The PBase scientific workflow provenance repository",
    star="[management][x] Repository",
    due="Unrelated to scripts",
    may_be_related_to=["repository"],
    display="cuevas",
    authors="Cuevas-Vicenttín, Víctor and Kianmajd, Parisa and Ludäscher, Bertram and Missier, Paolo and Chirigati, Fernando and Wei, Yaxing and Koop, David and Dey, Saumen",
    summary="Proposes a repository (PBase) that implements the ProvONE standard",
    place=IJDC,
    file="Cuevas2014a.pdf",
    volume="9",
    number="2",
    pp="28--38",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=13228339559236567279&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="13228339559236567279",
    scholar_ok=True,
))

davison2014a = DB(WorkUnrelated(
    2014, "Sumatra: a toolkit for reproducible research",
    due="Excluding Books",
    snowball=datetime(2017, 3, 6),
    display="davison",
    authors="Davison, Andrew P and Mattioni, Michele and Samarkanov, Dmitry and Tele{'n}czuk, B",
    scholar="http://scholar.google.com/scholar?cites=5143030166644397322&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="5143030166644397322",
    place=Book,
    bookname="Implementing reproducible research",
    file="Davison2014a.pdf",
    publisher="CRC Press",
    ID="davison2014sumatra",
    entrytype="article",
    volume="57",
    citation_file="sumatra2014",
    scholar_ok=True,
    tracking="alert",
))

devecsery2014a = DB(WorkBinarySnowball(
    2014, "Eidetic systems",
    display="arnold",
    authors="Devecsery, David and Chow, Michael and Dou, Xianzheng and Flinn, Jason and Chen, Peter M",
    summary="Argues that a computer system should recall any past state that existed on the computer and provided the lineage of any byte in a current or past state (eidetic computer system)",
    place=OSDI,
    file="Devecsery2014a.pdf",
    pp="525--540",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=15309827824341304640&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="15309827824341304640",
    scholar_ok=True,
))

dey2014a = DB(WorkUnrelated(
    2014, "UP & DOWN: Improving Provenance Precision by Combining Workflow-and Trace-Level Information",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="dey",
    authors="Dey, Saumen and Belhajjame, Khalid and Koop, David and Song, Tianhong and Missier, Paolo and Ludäscher, Bertram",
    place=TaPP,
    local="Cologne, Germany",
    file="Dey2014a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=4913817154039395340&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="4913817154039395340",
    scholar_ok=True,
    publisher="USENIX",
))

douglas2014a = DB(WorkBinaryOk(
    2014, "Cloudtracker: Using execution provenance to optimize the cost of cloud use",
    display="douglas",
    authors="Douglas, Geoffrey and Drawert, Brian and Krintz, Chandra and Wolski, Rich",
    place=GECON,
    star="job",
    ID="douglas2014cloudtracker",
    cluster_id="12827707890541442867",
    organization="Springer",
    pp="99--113",
    scholar="http://scholar.google.com/scholar?cites=12827707890541442867&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    file="Douglas2014a.pdf",
    scholar_ok=True,
))

driemeier2014a = DB(WorkUnrelated(
    2014, "Data analysis workflow for experiments in sugarcane precision agriculture",
    due="Unrelated to scripts. Unrelated to provenance",
    display="driemeier",
    authors="Driemeier, Calros Eduardo and Ling, Liu Yi and Pontes, Angélica O and Sanches, Guilherme M and Franco, Henrique CJ and Magalhães, Paulo SG and Ferreira, João E",
    place=eSoN,
    pp="163--168",
    volume="1",
    doi="http://doi.org/10.1109/eScience.2014.10",
    file="Driemeier2014a.pdf",
    entrytype="inproceedings",
    organization="IEEE",
    cluster_id="14774955234359823162",
    scholar="http://scholar.google.com/scholar?cites=14774955234359823162&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

eglen2014a = DB(WorkUnrelated(
    2014, "A data repository and analysis framework for spontaneous neural activity recordings in developing retina",
    due="Unrelated to provenance",
    may_be_related_to=["reprository"],
    display="eglen",
    authors="Eglen, Stephen John and Weeks, Michael and Jessop, Mark and Simonotto, Jennifer and Jackson, Tom and Sernagor, Evelyne",
    place=GigaScience,
    scholar="http://scholar.google.com/scholar?cites=11172207127272454970&as_sdt=2005&sciodt=0,5&hl=en",
    pp="3",
    cluster_id="11172207127272454970",
    number="1",
    file="Eglen2014a.pdf",
    publisher="BioMed Central",
    ID="eglen2014data",
    entrytype="article",
    link="https://gigascience.biomedcentral.com/articles/10.1186/2047-217X-3-3",
    volume="3",
    scholar_ok=True,
))

eltabakh2014a = DB(WorkUnrelated(
    2014, "Handson db: Managing data dependencies involving human actions",
    due="Unrelated to scripts",
    display="eltabakh",
    authors="Eltabakh, Mohamed and Aref, Walid and Elmagarmid, Ahmed and Ouzzani, Mourad",
    place=TKDE,
    number="9",
    pp="2193--2206",
    ID="eltabakh2014handson",
    entrytype="article",
    publisher="IEEE",
    cluster_id="4381477576293056951",
    volume="26",
    scholar="http://scholar.google.com/scholar?cites=4381477576293056951&as_sdt=2005&sciodt=0,5&hl=en",
    file="Eltabakh2014a.pdf",
    scholar_ok=True,
))

fat2014a = DB(WorkUnrelated(
    2014, "Error Detection in GPS Sensor Data Flows",
    due="Unrelated to scripts",
    display="fat",
    authors="Ong-A-Fat, Keoma",
    place=Unpublished,
    file="Fat2014a.pdf",
    ID="ong2014error",
    entrytype="article",
    scholar_ok=True,
))

filguiera2014a = DB(WorkUnrelated(
    2014, "Dispel4Py: A Python Framework for Data-intensive Scientific Computing",
    star="[collection][x] Model workflow using python for distributing data-intensive applications",
    due="Unrelated to provenance",
    display="filguiera",
    authors="Filguiera, Rosa and Klampanos, Iraklis and Krause, Amrey and David, Mario and Moreno, Alexander and Atkinson, Malcolm",
    place=DISCS,
    file="Filguiera2014a.pdf",
    pp="9--16",
    publisher="IEEE Press, Piscataway",
    local="NJ, USA",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=16828804799195468321&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="16828804799195468321",
    scholar_ok="aprox",
))

fisch2014a = DB(WorkUnrelated(
    2014, "Omics Pipe: A Computational Framework for Reproducible Multi-Omics Data Analysis",
    alias=(0, "Omics Pipe: A Computational Framework for Reproducible", "Fisch, Kathleen M and Meißner, Tobias and Gioia, Louis and others"),
    due="Only uses sumatra to collect provenance in predefined workflows",
    display="fisch",
    authors="Fisch, Kathleen M and Meißner, Tobias and Gioia, Louis and Ducom, Jean-Christophe and Carland, Tristan and Loguercio, Salvatore and Su, Andrew I",
    place=bioRxiv,
    scholar="http://scholar.google.com/scholar?cites=11164771342483588233&as_sdt=2005&sciodt=0,5&hl=en",
    pp="008383",
    cluster_id="11164771342483588233",
    file="Fisch2014a.pdf",
    publisher="Cold Spring Harbor Labs Journals",
    ID="fisch2014omics",
    entrytype="article",
    scholar_ok=True,
))

freire2014a = DB(WorkUnrelated(
    2014, "Reproducibility using VisTrails",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="freire",
    authors="Freire, Juliana and Koop, David and Chirigati, Fernando Seabra and Silva, Cláudio T",
    place=Book,
    file="Freire2014a.pdf",
    booktitle="Implementing Reproducible Research",
    pp="33",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=2659182693266565915&as_sdt=2005&sciodt=0,5&hl=en",
    volume="33",
    publisher="CRC Press",
    cluster_id="2659182693266565915",
    editors="Victoria Stodden, Friedrich Leisch, and Roger Peng",
    local="Boca Raton, Florida",
    scholar_ok=True,
))

garcia2014a = DB(WorkUnrelated(
    2014, "Automatic annotation of bioinformatics workflows with biomedical ontologies",
    due="Unrelated to scripts",
    may_be_related_to=["annotations"],
    display="garcia",
    authors="García-Jiménez, Beatriz and Wilkinson, Mark D",
    place=ISoLA,
    file="Garcia2014a.pdf",
    editors="T. Margaria and B. Steffen",
    proceedings="LNCS 8803",
    pp="464--478",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=13474573260496733720&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    cluster_id="13474573260496733720",
    scholar_ok=True,
))

garcia2014b = DB(WorkLang(
    2014, "Documentación de modelos y flujos de trabajo: el siguiente reto en el manejo de información ecológica",
    display="garcía",
    authors="García, Francisco Javier Bonet and Pérez-Pérez, Ramón and Benito, Blas M and Pérez-Luque, Antonio J and Zamora, Regino J",
    place=Lang,
    number="3",
    volume="22",
    ID="garcia2014documentacion",
    pp="37--45",
    entrytype="article",
    file="Garcia2014b.pdf",
    scholar_ok=True,
))

gehani2014a = DB(WorkOk(
    2014, "Provenance-only Integration",
    due="Unrelated to scripts",
    display="gehani",
    authors="Gehani, Ashish and Tariq, Dawood",
    place=TaPP,
    local="Cologne, Germany",
    scholar="http://scholar.google.com/scholar?cites=10471370311471183090&as_sdt=2005&sciodt=0,5&hl=en",
    ID="gehani2014provenance",
    cluster_id="10471370311471183090",
    entrytype="inproceedings",
    file="Gehani2014a.pdf",
    scholar_ok=True,
    publisher="USENIX",
))

gewaltig2014a = DB(WorkUnrelated(
    2014, "Current practice in software development for computational neuroscience and how to improve it",
    due="Unrelated to provenance",
    display="gewaltig",
    authors="Gewaltig, Marc-Oliver and Cannon, Robert",
    place=PCBI,
    number="1",
    volume="10",
    doi="10.1371/journal.pcbi.1003376",
    file="Gewaltig2014a.pdf",
    entrytype="article",
    pp="e1003376",
    publisher="Public Library of Science",
    cluster_id="2483652016579188928",
    scholar="http://scholar.google.com/scholar?cites=2483652016579188928&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

gounares2014a = DB(WorkUnrelated(
    2014, "Determination of function purity for memoization",
    due="Non Paper Format",
    display="gounares",
    authors="Gounares, Alexander G and Li, Ying and Garrett, Charles D and Noakes, Michael D",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=12361799197182083766&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent 8,839,204",
    cluster_id="12361799197182083766",
    month="sep~16",
    publisher="Google Patents",
    ID="gounares2014determination",
    entrytype="misc",
    scholar_ok=True,
))

gounares2014b = DB(WorkUnrelated(
    2014, "Memoization from offline analysis",
    due="Non paper format",
    display="gounares",
    authors="Gounares, Alexander G and Li, Ying and Garrett, Charles D",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=5137016839332944761&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent 8,789,030",
    cluster_id="5137016839332944761",
    month="jul~22",
    publisher="Google Patents",
    ID="gounares2014memoization",
    entrytype="misc",
    scholar_ok=True,
))

gounares2014c = DB(WorkUnrelated(
    2014, "Memoization configuration file consumed at runtime",
    due="Non Paper Format",
    display="gounares",
    authors="Gounares, Alexander G and Li, Ying and Garrett, Charles D and Noakes, Michael D",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=7690598158695055402&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent 8,752,034",
    cluster_id="7690598158695055402",
    month="jun~10",
    publisher="Google Patents",
    ID="gounares2014memoization",
    entrytype="misc",
    scholar_ok=True,
))

gounares2014d = DB(WorkUnrelated(
    2014, "Memoization configuration file consumed at compile time",
    due="Non Paper Format",
    display="gounares",
    authors="Gounares, Alexander G and Li, Ying and Garrett, Charles D and Noakes, Michael D",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=3900616918624950595&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent 8,656,378",
    cluster_id="3900616918624950595",
    month="feb~18",
    publisher="Google Patents",
    ID="gounares2014memoization",
    entrytype="misc",
    scholar_ok=True,
))

guerrera2014a = DB(WorkUnrelated(
    2014, "Reproducible experiments in parallel computing: Concepts and stencil compiler benchmark study",
    due="Unrelated to scripts",
    display="guerrera",
    authors="Guerrera, Danilo and Burkhart, Helmar and Maffia, Antonio",
    place=EuroPar,
    scholar="http://scholar.google.com/scholar?cites=899549189947808007&as_sdt=2005&sciodt=0,5&hl=en",
    pp="464--474",
    cluster_id="899549189947808007",
    file="Guerrera2014a.pdf",
    ID="guerrera2014reproducible",
    organization="Springer",
    entrytype="inproceedings",
    star="[collection] c++",
    scholar_ok=True,
))

guo2014a = DB(WorkUnrelated(
    2014, "CDE: Automatically package and reproduce computational experiments",
    due="Excluding Books",
    display="guo",
    authors="Guo, Philip J",
    place=Book,
    booktitle="Implementing Reproducible Research",
    editors="Victoria Stodden, Friedrich Leisch, and Roger Peng",
    local="Boca Raton, Florida",
    file="Guo2014a.pdf",
    publisher="CRC Press",
    pp="79",
    cluster_id="10381354672130584909",
    scholar="http://scholar.google.com/scholar?cites=10381354672130584909&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

hanken2014a = DB(WorkUnrelated(
    2014, "Kurator:  A Provenance-enabled Workflow Platform and Toolkit to Curate Biodiversity Data",
    due="Unrelated to scripts",
    may_be_related_to=["workflow", "curation"],
    display="hanken",
    authors="Hanken, James and Ludäscher, Bertram and Macklin, James A",
    place=Web,
    link="wiki.datakurator.net",
    awards="NSF-DBI Awards #1356438, #1356751",
    entrytype="misc",
    scholar_ok="impossible",
))

hashem2014a = DB(WorkUnrelated(
    2014, "Predicate-based Cloud Computing",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hashem",
    authors="Hashem, Hadi and Ranc, Daniel",
    place=NGMAST,
    cluster_id="6308322684406544480",
    scholar="http://scholar.google.com/scholar?cites=6308322684406544480&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    pp="131--136",
    file="Hashem2014a.pdf",
    ID="hashem2014predicate",
    organization="IEEE",
    scholar_ok=True,
))

hensley2014a = DB(WorkUnrelated(
    2014, "Provenance in sensor data management",
    due="Unrelated to scripts",
    display="hensley",
    authors="Hensley, Zachary and Sanyal, Jibonananda and New, Joshua",
    place=CACM,
    scholar="http://scholar.google.com/scholar?cites=11090116322119996589&as_sdt=2005&sciodt=0,5&hl=en",
    pp="55--62",
    cluster_id="11090116322119996589",
    number="2",
    file="Hensley2014a.pdf",
    publisher="ACM",
    ID="hensley2014provenance",
    entrytype="article",
    summary="Use cpl",
    volume="57",
    scholar_ok=True,
))

hinsen2014a = DB(WorkUnrelated(
    2014, "Computational science: shifting the focus from tools to models",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hinsen",
    authors="Hinsen, Konrad",
    place=F1000Research,
    volume="3",
    file="Hinsen2014a.pdf",
    number="101",
    pp="1--16",
    doi="10.12688/f1000research.3978.2.",
    month="June",
    link="https://f1000research.com/articles/3-101/v1",
    entrytype="article",
    cluster_id="18399565395901473454",
    scholar="http://scholar.google.com/scholar?cites=18399565395901473454&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

hoekstra2014a = DB(WorkUnrelated(
    2014, "PROV-O-Viz-understanding the role of activities in provenance",
    due="Unrelated to scripts",
    may_be_related_to=["visualization"],
    display="hoekstra",
    authors="Hoekstra, Rinke and Groth, Paul",
    place=IPAW,
    file="Hoekstra2014a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=7635425897594535752&as_sdt=2005&sciodt=0,5&hl=en",
    pp="215--220",
    organization="Springer",
    cluster_id="7635425897594535752",
    scholar_ok=True,
    local="Cologne, Germany",
))

hoffmann2014a = DB(WorkUnrelated(
    2014, "A practitioner's guide to software-based soft-error mitigation using AN-codes",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hoffmann",
    authors="Hoffmann, Martin and Ulbrich, Peter and Dietrich, Christian and Schirmeier, Horst and Lohmann, Daniel and Schroder-Preikschat, Wolfgang",
    place=HASE,
    file="Hoffmann2014a.pdf",
    doi="10.1109/HASE.2014.14",
    pp="33--40",
    isbn="978-1-4799-3465-2",
    month="Jan",
    publisher="IEEE",
    local="Miami, Florida, USA",
    entrytype="inproceedings",
    organization="IEEE",
    cluster_id="5978414828379505445",
    scholar="http://scholar.google.com/scholar?cites=5978414828379505445&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

hoffmann2014b = DB(WorkUnrelated(
    2014, "Effectiveness of Fault Detection Mechanisms in Static and Dynamic Operating System Designs",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hoffmann",
    authors="Hoffmann, Martin and Borchert, Christoph and Dietrich, Christian and Schirmeier, Horst and Kapitza, Rüdiger and Spinczyk, Olaf and Lohmann, Daniel",
    place=ISORC,
    file="Hoffmann2014b.pdf",
    doi="10.1109/ISORC.2014.26",
    local="Reno, Nevada, USA",
    publisher="IEEE",
    pp="230--237",
    entrytype="inproceedings",
    organization="IEEE",
    cluster_id="772026520607209595",
    scholar="http://scholar.google.com/scholar?cites=772026520607209595&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

hold2014a = DB(WorkUnrelated(
    2014, "Once you SCOOP, no need to fork",
    due="Unrelated to provenance",
    display="hold",
    authors="Hold-Geoffroy, Yannick and Gagnon, Olivier and Parizeau, Marc",
    place=XSEDE,
    pp="60",
    publisher="ACM",
    file="Hold2014a.pdf",
    entrytype="inproceedings",
    organization="ACM",
    cluster_id="15140654513539498292",
    scholar="http://scholar.google.com/scholar?cites=15140654513539498292&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

howe2014a = DB(WorkUnrelated(
    2014, "Reproducibility, Virtual Appliances, and Cloud Computing",
    due="Unrelated to scripts",
    display="howe",
    authors="Howe, Bill",
    scholar="http://scholar.google.com/scholar?cites=1864881282780273694&as_sdt=2005&sciodt=0,5&hl=en",
    pp="281",
    cluster_id="1864881282780273694",
    place=Book,
    bookname="Implementing Reproducible Research",
    file="Howe2014a.pdf",
    publisher="CRC Press",
    ID="howe2014reproducibility",
    entrytype="article",
    excerpt="Science in every discipline increasingly relies on computational and datadriven methods. Perhaps paradoxically, these in silico experiments are often more difficult to reproduce than traditional laboratory techniques. Software pipelines designed to acquire and process data ",
    scholar_ok=True,
))

hull2014a = DB(WorkUnrelated(
    2014, "Morphforge: a toolbox for simulating small networks of biologically detailed neurons in Python",
    due="Unrelated to provenance",
    display="hull",
    authors="Hull, Michael James and Willshaw, David J",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=6739958897674904822&as_sdt=2005&sciodt=0,5&hl=en",
    pp="47",
    cluster_id="6739958897674904822",
    file="Hull2014a.pdf",
    publisher="Frontiers",
    ID="hull2014morphforge",
    entrytype="article",
    volume="7",
    scholar_ok=True,
))

hutter2014a = DB(WorkUnrelated(
    2014, "An efficient approach for assessing hyperparameter importance",
    due="Unrelated to provenance",
    display="hutter",
    authors="Hoos, Holger and Leyton-Brown, Kevin",
    place=ICML,
    file="Hutter2014a.pdf",
    pp="754--762",
    entrytype="article",
    cluster_id="13085890774974932313",
    scholar="http://scholar.google.com/scholar?cites=13085890774974932313&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

ipaw2014a = DB(WorkUnrelated(
    2014, "Provenance and Annotation of Data and Processes: 5th International Provenance and Annotation Workshop, IPAW 2014, Cologne, Germany, June 9-13, 2014. Revised Selected Papers",
    due="Non paper format",
    display="IPAW",
    authors="Ludäscher, Bertram and Plale, Beth",
    place=IPAW,
    local="Cologne, Germany",
    link="http://provenanceweek.dlr.de/ipaw/call-participation/",
    proceedings="LNCS 8628",
    publisher="Springer",
    entrytype="book",
    scholar="http://scholar.google.com/scholar?cites=2569898852273409401&as_sdt=2005&sciodt=0,5&hl=en",
    volume="8628",
    cluster_id="2569898852273409401",
    scholar_ok=True,
))

janin2014a = DB(WorkBinarySnowball(
    2014, "Care, the comprehensive archiver for reproducible execution",
    display="CARE",
    authors="Janin, Yves and Vincent, Cédric and Duraffort, Rémi",
    summary="Proposes a system that traces the execution and collects dependencies for reproducibility",
    place=TRUST,
    file="Janin2014a.pdf",
    pp="1:1--1:7",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=4341413279013902316&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    cluster_id="4341413279013902316",
    scholar_ok=True,
))

johnson2014a = DB(WorkUnrelated(
    2014, "HybSeqPipeline:FirstDOIRelease",
    due="Unrelated to provenance. Unrelated to scripts",
    display="johnson",
    authors="Johnson, Matt",
    place=Web,
    link="http://dx.doi.org/10.5281/zenodo.11977",
    entrytype="misc",
    scholar_ok="impossible",
))

kandl2014a = DB(WorkNoFile(
    2014, "Trusted information supply chain framework in clinical studies",
    due="Abstract looks unrelated to scripts and provenance",
    display="kandl",
    authors="Kandl, Thomas and Khan, Nawaz",
    pp="103--110",
    place=ASLDAM,
    volume="20",
    ID="kandl2014trusted",
    number="1",
    entrytype="article",
    publisher="American Scientific Publishers",
    request="researchgate",
    scholar_ok=True,
))

kandl2014b = DB(WorkUnrelated(
    2014, "Information integration of drug discovery and clinical studies to support complex queries using an information supply chain framework",
    due="Unrelated to provenance. Unrelated to scripts",
    display="kandl",
    authors="Kandl, Thomas and Khan, Nawaz",
    pp="1348--1357",
    place=JSW,
    file="Kandl2014b.pdf",
    volume="9",
    ID="kandl2014information",
    number="5",
    entrytype="article",
    publisher="Academy Publisher",
    scholar_ok=True,
))

kannan2014a = DB(WorkUnrelated(
    2014, "A Proficient Data Repertory Acumen layout to Supervise Data Provenance in Geo science Application",
    due="Unrelated to scripts",
    display="kannan",
    authors="Kannan, KS and Hemalatha, M",
    place=IJETR,
    file="Kannan2014a.pdf",
    ID="kannanproficient",
    entrytype="article",
    scholar_ok=True,
))

kannan2014b = DB(WorkUnrelated(
    2014, "Management of Data Provenance through Shrewdness Schema in Geosciences Application",
    due="Unrelated to scripts",
    display="kannan b",
    authors="Kannan, KS and Hemalatha, M",
    place=IJAAS,
    number="1",
    entrytype="article",
    link="https://www.ciitresearch.org/dl/index.php/aa/article/view/AA022014005",
    volume="6",
    file="Kannan2014b.pdf",
    ID="kannan2014management",
    scholar_ok=True,
))

kohwalter2014a = DB(WorkUnrelated(
    2014, "Reinforcing software engineering learning through provenance",
    due="Unrelated to scripts",
    authors="Kohwalter, Troy and Clua, Esteban and Murta, Leonardo",
    place=SBES,
    file="Kohwalter2014a.pdf",
    pp="131--140",
    entrytype="inproceedings",
    organization="IEEE",
    cluster_id="3634592804992815974",
    scholar="http://scholar.google.com/scholar?cites=3634592804992815974&as_sdt=2005&sciodt=0,5&hl=en",
    local="Maceió, Brazil",
    scholar_ok=True,
))

kubilius2014a = DB(WorkUnrelated(
    2014, "A framework for streamlining research workflow in neuroscience and psychology",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="kubilius",
    authors="Kubilius, Jonas",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=8731391619874884090&as_sdt=2005&sciodt=0,5&hl=en",
    pp="52",
    cluster_id="8731391619874884090",
    file="Kubilius2014a.pdf",
    publisher="Frontiers",
    ID="kubilius2014framework",
    entrytype="article",
    link="http://journal.frontiersin.org/article/10.3389/fninf.2013.00052/full",
    star="[collection] specific workflow in python",
    volume="7",
    scholar_ok=True,
))

lagoze2014a = DB(WorkUnrelated(
    2014, "Ced 2 ar: The comprehensive extensible data documentation and access repository",
    due="Unrelated to scripts",
    display="lagoze",
    authors="Lagoze, Carl and Vilhuber, Lars and Williams, Jeremy and Perry, Benjamin and Block, William C",
    place=JCDL,
    cluster_id="12707559469000733949",
    pp="267--276",
    ID="lagoze2014ced",
    organization="IEEE",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12707559469000733949&as_sdt=2005&sciodt=0,5&hl=en",
    file="Lagoze2014a.pdf",
    scholar_ok=True,
))

ledet2014a = DB(WorkUnrelated(
    2014, "Toward model-driven engineering principles and practices to support model replicability",
    due="Unrelated to provenance",
    may_be_related_to=["reproducibility"],
    display="ledet",
    authors="Ledet, Joseph and Teran-Somohano, Alejandro and Butcher, Zachary and Yilmaz, Levent and Smith, Alice E and Oğuztüzün, Halit and Dayıbaş, Orçun and Görür, Bilge Kaan",
    place=SummerSim,
    pp="6",
    file="Ledet2014a.pdf",
    ID="ledet2014toward",
    organization="Society for Computer Simulation International",
    entrytype="inproceedings",
    scholar_ok=True,
))

ledet2014b = DB(WorkUnrelated(
    2014, "Toward model-driven engineering principles and practices for model replicability and experiment reproducibility",
    due="Unrelated to provenance",
    display="ledet",
    authors="Ledet, Joseph and Teran-Somohano, Alejandro and Butcher, Zachary and Yilmaz, Levent and Smith, Alice E and Oğuztüzün, Halit and Dayıbaş, Orçun and Görür, Bilge Kaan",
    place=TMS_DEVS,
    scholar="http://scholar.google.com/scholar?cites=3132592872146255494&as_sdt=2005&sciodt=0,5&hl=en",
    pp="27",
    cluster_id="3132592872146255494",
    file="Ledet2014b.pdf",
    ID="ledet2014toward",
    organization="Society for Computer Simulation International",
    entrytype="inproceedings",
    scholar_ok=True,
))

lei2014a = DB(WorkUnrelated(
    2014, "miR-PREFeR: an accurate, fast and easy-to-use plant miRNA prediction tool using small RNA-Seq data",
    due="Unrelated to scripts. Unrelated to provenance",
    display="lei",
    authors="Lei, Jikai and Sun, Yanni",
    place=bioinformatics,
    file="Lei2014a.pdf",
    volume="30",
    number="19",
    pp="btu380",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=11291390205713598307&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Oxford Univ Press",
    cluster_id="11291390205713598307",
    scholar_ok=True,
))

lerner2014a = DB(WorkSnowball( # 12
    2014, "RDataTracker: collecting provenance in an interactive scripting environment",
    snowball=datetime(2017, 3, 6),
    display="RDataTracker",
    summary="Proposes povenance collection on R",
    authors="Lerner, Barbara and Boose, Emery",
    place=TaPP,
    pp="1--4",
    local="Cologne, Germany",
    file="Lerner2014a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=14776414362422361410&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="14776414362422361410",
    scholar_ok=True,
    citation_file="rdatatracker2014a",
    tracking="alert",
    publisher="USENIX",
))

lerner2014b = DB(WorkSnowball(
    2014, "POSTER: RDataTracker and DDG Explorer",
    snowball=datetime(2017, 3, 6),
    display="lerner",
    authors="Lerner, Barbara and Boose, Emery",
    place=IPAW,
    pp="1--3",
    local="Cologne, Germany",
    ID="scriptsposter",
    entrytype="inproceedings",
    file="Lerner2014b.pdf",
    citation_file="rdatatracker2014b",
    scholar_ok=True,
    scholar="http://scholar.google.com/scholar?cites=5630516626867858377&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="5630516626867858377",
    tracking="alert",
    publisher="Springer",
))

leyshock2014a = DB(WorkUnrelated(
    2014, "Optimizing Data Movement in Hybrid Analytic Systems",
    due="Unrelated to scripts. Unrelated to provenance",
    display="leyshock",
    authors="Leyshock, Patrick Michael",
    place=Thesis,
    ID="leyshock2014optimizing",
    entrytype="article",
    file="Leyshock2014a.pdf",
    scholar_ok=True,
))

li2014a = DB(WorkBinaryOk(
    2014, "Scalable state management for scientific applications in the cloud",
    display="li",
    authors="Li, Tonglin and Raicu, Ioan and Ramakrishnan, Lavanya",
    place=BigData,
    file="Li2014a.pdf",
    scholar="http://scholar.google.com/scholar?cites=16437564240725263174&as_sdt=2005&sciodt=0,5&hl=en",
    pp="204--211",
    entrytype="inproceedings",
    cluster_id="16437564240725263174",
    organization="IEEE",
    ID="li2014scalable",
    star="binary",
    scholar_ok=True,
))

li2014b = DB(WorkUnrelated(
    2014, "Input vector analysis for memoization estimation",
    due="Non paper format",
    display="li",
    authors="Li, Ying and Garrett, Charles D and Noakes, Michael D and Gounares, Alexander G",
    place=Patent,
    scholar="http://scholar.google.com/scholar?cites=8374699401653296784&as_sdt=2005&sciodt=0,5&hl=en",
    note="US Patent 8,752,021",
    cluster_id="8374699401653296784",
    month="jun~10",
    publisher="Google Patents",
    ID="li2014input",
    entrytype="misc",
    scholar_ok=True,
))

lucelia2014a = DB(WorkLang(
    2014, "Um modelo de proveniência para extração",
    alias=(2014, "LUCÉLIA DE SOUZA", "EXTRACAO, UM MODELO DE PROVENIÊNCIA PARA"),
    display="Lucelia",
    authors="De Souze, Lucélia",
    place=Thesis,
    file="Lucelia2014a.pdf",
    ID="extracao2014lucelia",
    entrytype="phdthesis",
    local="Universidade Federal do Paraná",
    scholar_ok=True,
))

ma2014a = DB(WorkUnrelated(
    2014, "A graph distance based metric for data oriented workflow retrieval with variable time constraints",
    due="Unrelated to scripts. Unrelated to provenance",
    display="ma",
    authors="Ma, Yinglong and Zhang, Xiaolan and Lu, Ke",
    place=ESA,
    file="Ma2014a.pdf",
    volume="41",
    number="4",
    pp="1377--1388",
    entrytype="article",
    scholar="http://scholar.google.com/scholar?cites=9463843514421911945&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Elsevier",
    cluster_id="9463843514421911945",
    scholar_ok=True,
))

michaelides2014a = DB(WorkUnrelated(
    2014, "PROV-Template: A Template System for PROV Documents",
    due="Unrelated to scripts",
    may_be_related_to=["semantic web", "model"],
    display="michaelides",
    authors="Michaelides, Danius and Huynh, Trung Dong and Moreau, Luc",
    place=Web,
    link="https://provenance.ecs.soton.ac.uk/prov-template/",
    entrytype="misc",
    scholar_ok="impossible",
))

miguez2014a = DB(WorkUnrelated(
    2014, "Best Practices for Computational Science: Software Infrastructure and Environments for Reproducible and Extensible Research",
    due="Unrelated to scripts. Unrelated to provenance",
    display="miguez",
    authors="Stodden, Victoria and Miguez, Sheila",
    place=JORS,
    pp="1--6",
    doi="10.5334/jors.ay",
    month="July",
    volume="2",
    file="Miguez2014a.pdf",
    number="1",
    entrytype="article",
    cluster_id="16642678442674871574",
    scholar="http://scholar.google.com/scholar?cites=16642678442674871574&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

moraila2014a = DB(WorkUnrelated(
    2014, "Measuring Reproducibility in Computer Systems Research",
    due="Unrelated to provenance",
    display="moraila",
    authors="Moraila, Gina and Shankaran, Akash and Shi, Zuoming and Warren, Alex M",
    place=TechReport,
    scholar="http://scholar.google.com/scholar?cites=6099306313468866923&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6099306313468866923",
    institution="Tech Report",
    file="Moraila2014a.pdf",
    ID="moraila2014measuring",
    entrytype="techreport",
    link="http://reproducibility.cs.arizona.edu/tr.pdf",
    month="Mar",
    scholar_ok=True,
))

moreno2014a = DB(WorkUnrelated(
    2014, "Speeding up large-scale financial recomputation with memoization",
    due="Unrelated to scripts",
    display="moreno",
    authors="Moreno, Alexander and Balch, Tucker",
    place=WHPCF,
    star="memoization",
    ID="moreno2014speeding",
    cluster_id="1991539109085149921",
    organization="IEEE Press",
    pp="17--22",
    scholar="http://scholar.google.com/scholar?cites=1991539109085149921&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    file="Moreno2014a.pdf",
    scholar_ok=True,
))

murta2014a = DB(WorkSnowball( # 36
    2014, "noWorkflow: capturing and analyzing provenance of scripts",
    alias=(2015, "noWorkflow: Capturing and Analyzing Provenance of Scripts", "Chirigati, Fernando and Koop, David and Freire, Juliana"),
    snowball=datetime(2017, 3, 6),
    display="noWorkflow",
    authors="Murta, Leonardo and Braganholo, Vanessa and Chirigati, Fernando and Koop, David and Freire, Juliana",
    place=IPAW,
    local="Cologne, Germany",
    file="Murta2014a.pdf",
    scholar="http://scholar.google.com/scholar?cites=5458343950729529273&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_id="ucciVefuv0sJ",
    scholar_id2="FiutAE4j0IgJ",
    summary="Captures provenance from scripts. Supports SQL and Prolog queries. Generates Activation Graphs. Defines deployment, definition, and execution provenance",
    pp="71--83",
    entrytype="inproceedings",
    organization="Springer",
    cluster_id="5458343950729529273",
    scholar_ok=True,
    citation_file="noworkflow2014",
    tracking="alert",
))

neves2014a = DB(WorkUnrelated(
    2014, "Managing Implicit Data Provenance in Scientific Experiments",
    aliases=[
        (2014, "Vitor Carvalho Neves"),
        (2014, "Vitor Carvalho Neves", "Murta, D Sc Vanessa Braganholo"),
    ],
    due="Unrelated to scripts",
    star="[todo] See the related work: ASTRO-WISE, PROB. See also moment of collection",
    may_be_related_to=["workflow", "evolution"],
    display="neves",
    authors="Neves, Vitor C and Murta, Leonardo and Braganholo, Vanessa",
    summary="Captures provenance of implicit dataflow through configuration management. Each execution creates a new version. Limitation: SWfMS based on activities",
    define={"implicit provenance": "data not explicitly referenced by the workflow specification"},
    school="Universidade Federal Fluminense",
    place=Thesis,
    file="Neves2014a.pdf",
    entrytype="phdthesis",
    scholar_ok="impossible",
))

oliveira2014a = DB(WorkLang(
    2014, "Captura e Consulta a Dados de Proveniência Retrospectiva Implícita Intra-Atividade",
    display="oliveira",
    authors="Oliveira, Wellington and Neves, Vitor C and Ocaña, Kary and Murta, Leonardo and de Oliveira, Daniel and Braganholo, Vanessa",
    place=Lang,
    volume="29",
    ID="oliveira2014captura",
    cluster_id="11468787046701553128",
    pp="14--27",
    scholar="http://scholar.google.com/scholar?cites=11468787046701553128&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    file="Oliveira2014a.pdf",
    scholar_ok=True,
))

oxvig2014a = DB(WorkUnrelated(
    2014, "Magni: A Python Package for Compressive Sampling and Reconstruction of Atomic Force Microscopy Images",
    due="Unrelated to provenance. This paper does not describe the provenance aspects of magni",
    display="oxvig",
    authors="Oxvig, Christian and Pedersen, Patrick and Arildsen, Thomas and Østergaard, Jan and Larsen, Torben",
    place=JORS,
    volume="2",
    file="Oxvig2014a.pdf",
    number="1",
    pp="e29",
    doi="10.5334/jors.bk",
    month="October",
    link="http://openresearchsoftware.metajnl.com/articles/10.5334/jors.bk/",
    entrytype="article",
    publisher="Ubiquity Press",
    cluster_id="16132838929000819168",
    scholar="http://scholar.google.com/scholar?cites=16132838929000819168&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

pham2014a = DB(WorkBinaryOk(
    2014, "Auditing and maintaining provenance in software packages",
    display="pham",
    authors="Pham, Quan and Malik, Tanu and Foster, Ian",
    place=IPAW,
    local="Cologne, Germany",
    scholar="http://scholar.google.com/scholar?cites=18018513454169697389&as_sdt=2005&sciodt=0,5&hl=en",
    pp="97--109",
    cluster_id="18018513454169697389",
    file="Pham2014a.pdf",
    ID="pham2014auditing",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
))

potjans2014a = DB(WorkUnrelated(
    2014, "The cell-type specific cortical microcircuit: relating structure and activity in a full-scale spiking network model",
    due="Unrelated to provenance",
    display="potjans",
    authors="Potjans, Tobias C and Diesmann, Markus",
    place=CerCor,
    pp="785--806",
    volume="24",
    doi="10.1093/cercor/bhs358",
    file="Potjans2014a.pdf",
    entrytype="article",
    number="3",
    publisher="Oxford Univ Press",
    cluster_id="13141632265089946520",
    scholar="https://scholar.google.com/scholar?cites=13141632265089946520&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

r2014a = DB(WorkUnrelated(
    2014, "R: A language and environment for statistical computing",
    due="Unrelated to provenance",
    display="r",
    authors="Team, R Core and others",
    place=Web,
    link="http://www.R-project.org",
    local="R Foundation for Statistical Computing, Vienna, Austria",
    entrytype="article",
    cluster_id="13829712525405590461",
    scholar="http://scholar.google.com/scholar?cites=13829712525405590461&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Vienna, Austria",
    scholar_ok="aprox",
))

rangwala2014a = DB(WorkUnrelated(
    2014, "GRADUATE SCHOOL",
    due="Unrelated to scripts",
    display="rangwala",
    authors="Rangwala, Mohammed M",
    place=Thesis,
    file="Rangwala2014a.pdf",
    local="Purdue University",
    ID="rangwala2014graduate",
    entrytype="phdthesis",
    school="Purdue University",
    scholar_ok=True,
))

rossiter2014a = DB(WorkUnrelated(
    2014, "Sensor Data Management, Validation, Correction, and Provenance for Building Technologies",
    due="Unrelated to scripts. Unrelated to provenance",
    display="rossiter",
    authors="Rossiter, Jeffrey and Hensley, Zachary",
    place=ASHRAET,
    scholar="http://scholar.google.com/scholar?cites=56027148260591316&as_sdt=2005&sciodt=0,5&hl=en",
    pp="370",
    cluster_id="56027148260591316",
    file="Rossiter2014a.pdf",
    publisher="American Society of Heating, Refrigeration and Air Conditioning Engineers, Inc.",
    ID="rossiter2014sensor",
    entrytype="article",
    volume="120",
    scholar_ok=True,
))

ruiz2014a = DB(WorkUnrelated(
    2014, "Reproducible software appliances for experimentation",
    due="Unrelated to scripts",
    may_be_related_to=["grid"],
    display="ruiz",
    authors="Ruiz, Cristian and Richard, Olivier and Emeras, Joseph",
    place=ICST,
    file="Ruiz2014a.pdf",
    volume="137",
    pp="33--42",
    entrytype="inproceedings",
    cluster_id="7152970547749651390",
    scholar="http://scholar.google.com/scholar?cites=7152970547749651390&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
))

ruprecht2014a = DB(WorkUnrelated(
    2014, "Automatic Feature Selection in Large-Scale System-Software Product Lines",
    due="Unrelated to scripts. Unrelated to provenance",
    display="ruprecht",
    authors="Heinloth, Andreas Ruprecht Bernhard and Lohmann, Daniel",
    place=GPCE,
    file="Ruprecht2014a.pdf",
    editors="Matthew Flatt",
    pp="39--48",
    isbn="978-1-4503-3161-6",
    month="Sept",
    doi="10.1145/2658761.2658767",
    publisher="ACM",
    local="Västeås, Sweden",
    entrytype="inproceedings",
    scholar_ok=True,
))

saake2014a = DB(WorkUnrelated(
    2014, "Minimal-invasive provenance integration into data-intensive systems",
    due="Unrelated to scripts",
    display="saake",
    authors="Saake, Gunter and Hasselbring, Wilhelm and Schmid, Klaus",
    place=Thesis,
    ID="saakeminimal",
    entrytype="phdthesis",
    file="Saake2014a.pdf",
    scholar_ok=True,
))

sankaranarayanan2014a = DB(WorkUnrelated(
    2014, "SMILE: A Data Sharing Platform for Mobile Apps in the Cloud",
    due="Unrelated to scripts. Unrelated to provenance",
    display="sankaranarayanan",
    authors="Sankaranarayanan, Jagan and Hacigümüs, Hakan and Zhang, Haopeng and Sarwat, Mohamed",
    place=EDBT,
    file="Sankaranarayanan2014a.pdf",
    entrytype="inproceedings",
    pp="688--699",
    cluster_id="15976828697106630831",
    scholar="http://scholar.google.com/scholar?cites=15976828697106630831&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

santana2014a = DB(WorkUnrelated(
    2014, "A Semantic-Based Approach to Attain Reproducibility of Computational Environments in Scientic Work ows: A Case Study",
    alias=(2014, "A Semantic-Based Approach to Attain Reproducibility of Computational Environments in Scientic Work ows: A Case Study", "Santana-Perez, Idafen and Ferreira da Silva, R and Rynge, Mats and Deelman, Ewa and Pérez-Hernández, M and Corcho, Oscar"),
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="santana",
    authors="Santana-Perez, Idafen and Ferreira da Silva, R and Rynge, Mats and Deelman, Ewa and Pérez-Hernández, M and Corcho, Oscar",
    place=EuroPar,
    scholar="http://scholar.google.com/scholar?cites=15711270237381648127&as_sdt=2005&sciodt=0,5&hl=en",
    ID="santana2014semantic",
    organization="Springer",
    pp="452--463",
    entrytype="inproceedings",
    file="Santana2014a.pdf",
    cluster_id="15711270237381648127",
    publisher="Informatica",
    scholar_ok=True,
))

santana2014b = DB(WorkUnrelated(
    2014, "Leveraging semantics to improve reproducibility in scientific workflows",
    due="Unrelated to scripts",
    display="santana",
    authors="Santana-Perez, Idafen and Ferreira da Silva, Rafael and Rynge, Mats and Deelman, Ewa and Pérez-Henández, María S and Corcho, Oscar",
    place=REP_XSEDE,
    scholar="http://scholar.google.com/scholar?cites=6734826511575587472&as_sdt=2005&sciodt=0,5&hl=en",
    ID="santana2014leveraging",
    entrytype="article",
    file="Santana2014b.pdf",
    publisher="Informatica",
    cluster_id="6734826511575587472",
    scholar_ok=True,
))

scott2014a = DB(WorkUnrelated(
    2014, "Managing heterogeneous datasets",
    due="Unrelated to scripts. Unrelated to provenance",
    display="scott",
    authors="Scott, Mark and Boardman, Richard P and Reed, Philippa A and Cox, Simon J",
    place=IS,
    pp="34--53",
    volume="44",
    ID="scott2014managing",
    file="Scott2014a.pdf",
    publisher="Elsevier",
    scholar="https://scholar.google.com/scholar?cites=11670618248317020752&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="11670618248317020752",
    entrytype="article",
    scholar_ok=True,
))

shcherbakov2014a = DB(WorkUnrelated(
    2014, "Lean Data Science Research Life Cycle: A Concept for Data Analysis Software Development",
    due="Unrelated to provenance",
    display="shcherbakov",
    authors="Shcherbakov, Maxim and Shcherbakova, Nataliya and Brebels, Adriaan and Janovsky, Timur and Kamaev, Valery",
    place=JCKBSE,
    cluster_id="10495549827170393671",
    scholar="http://scholar.google.com/scholar?cites=10495549827170393671&as_sdt=2005&sciodt=0,5&hl=en",
    pp="708--716",
    entrytype="inproceedings",
    file="Shcherbakov2014a.pdf#page=722",
    ID="shcherbakov2014lean",
    organization="Springer",
    scholar_ok=True,
))

shen2014a = DB(WorkUnrelated(
    2014, "Interactive notebooks: Sharing the code",
    due="Unrelated to provenance",
    star="[related_work] Motivates the usage of interactive notebooks",
    display="shen",
    authors="Shen, Helen and others",
    place=Nature,
    file="Shen2014a.pdf",
    volume="515",
    number="7525",
    pp="151--152",
    entrytype="article",
    cluster_id="1694138341360758230",
    scholar="http://scholar.google.com/scholar?cites=1694138341360758230&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="Macmillan Publishers Ltd., London, England",
    scholar_ok=True,
))

silles2014a = DB(WorkSnowball( # 0
    2014, "Provenance-aware CXXR",
    snowball=datetime(2017, 3, 6),
    display="cxxr",
    authors="Silles, Christopher Anthony",
    place=Thesis,
    file="Silles2014a.pdf",
    ID="silles2014provenance",
    entrytype="phdthesis",
    local="University of Kent",
    todo="216p/121r cxxr tese",
    excerpt="Abstract A provenance-aware computer system is one that records information about the operations it performs on data to enable it to provide an account of the process that led to a particular item of data. These systems allow users to ask questions of data, such as What ",
    citation_file="cxxr2014",
    school="University of Kent",
    cluster_id="246808414964898615",
    scholar="http://scholar.google.com/scholar?cites=246808414964898615&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
    tracking="alert",
))

smith2014a = DB(WorkUnrelated(
    2014, "An easy to use repository for comparing and improving machine learning algorithm usage",
    due="Unrelated to provenance",
    display="smith",
    authors="Smith, Michael R and White, Andrew and Giraud-Carrier, Christophe and Martinez, Tony",
    place=arXiv,
    number="1405.7292",
    link="http://arxiv.org/abs/1405.7292",
    month="May",
    file="Smith2014a.pdf",
    entrytype="inproceedings",
    cluster_id="16363141421182982545",
    scholar="http://scholar.google.com/scholar?cites=16363141421182982545&as_sdt=2005&sciodt=0,5&hl=en",
    organization="CEUR-WS. org",
    pp="41--48",
    scholar_ok=True,
))

stamatogiannakis2014a = DB(WorkBinarySnowball( # Related
    2014, "Looking inside the black-box: capturing data provenance using dynamic instrumentation",
    display="DataTracker",
    star="[collection][x] Trade-off on collection: In designing a provenance capture system,one must make a trade-off between the fidelity of the captured provenance(i.e. how accurate the provenance is) and the effort on the part of applicationdevelopers and/or users to make a system provenance-aware. Minimum amounts of noise (false-positives) and distortion (misrepresentation of existing relations)",
    authors="Stamatogiannakis, Manolis and Groth, Paul and Bos, Herbert",
    place=IPAW,
    local="Cologne, Germany",
    file="Stamatogiannakis2014a.pdf",
    pp="155--167",
    entrytype="inproceedings",
    cluster_id="13147155178652474070",
    scholar="http://scholar.google.com/scholar?cites=13147155178652474070&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
))

stamatogiannakis2014b = DB(WorkBinaryOk(
    2014, "Facilitating trust on data through provenance",
    display="stamatogiannakis",
    authors="Stamatogiannakis, Manolis and Groth, Paul and Bos, Herbert",
    place=TRUST,
    ID="stamatogiannakis2014facilitating",
    cluster_id="7846299060911576434",
    organization="Springer",
    pp="220--221",
    scholar="http://scholar.google.com/scholar?cites=7846299060911576434&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    file="Stamatogiannakis2014b.pdf",
    scholar_ok=True,
))

starlinger2014a = DB(WorkUnrelated(
    2014, "Similarity search for scientific workflows",
    star="[management][x] Lack of repositories to store provenance. Workflow discovery",
    due="Unrelated to scripts",
    may_be_related_to=["comparison", "search"],
    display="starlinger",
    authors="Starlinger, Johannes and Brancotte, Bryan and Cohen-Boulakia, Sarah and Leser, Ulf",
    place=VLDB,
    file="Starlinger2014a.pdf",
    local="Hangzhou, China",
    #volume="7",
    #number="12",
    pp="1143--1154",
    entrytype="inproceedings",
    cluster_id="8281299848954455402",
    scholar="http://scholar.google.com/scholar?cites=8281299848954455402&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="VLDB Endowment",
    scholar_ok=True,
))

stimberg2014a = DB(WorkUnrelated(
    2014, "Equation-oriented specification of neural models for simulations",
    due="Unrelated to scripts. Unrelated to provenance",
    display="stimberg",
    authors="Stimberg, Marcel and Goodman, Dan FM and Benichoux, Victor and Brette, Romain",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=7576215400515272282&as_sdt=2005&sciodt=0,5&hl=en",
    pp="6",
    cluster_id="7576215400515272282",
    file="Stimberg2014a.pdf",
    publisher="Frontiers",
    ID="stimberg2014equation",
    entrytype="article",
    link="http://journal.frontiersin.org/article/10.3389/fninf.2014.00006/full",
    volume="8",
    number="6",
    doi="10.3389/fninf.2014.00006",
    scholar_ok=True,
))

stodden2014a = DB(WorkUnrelated(
    2014, "Implementing reproducible research",
    due="Unrelated to provenance. Unrelated to scripts",
    may_be_related_to=["reproducibility"],
    display="stodden",
    authors="Stodden, Victoria and Leisch, Friedrich and Peng, Roger D",
    place=Book,
    file="Stodden2014a.pdf",
    publisher="CRC Press",
    entrytype="book",
    cluster_id="745957442458782363",
    scholar="http://scholar.google.com/scholar?cites=745957442458782363&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

sultana2014a = DB(WorkUnrelated(
    2014, "Digital provenance-models, systems, and applications",
    due="Unrelated to scripts",
    display="sultana",
    authors="Sultana, Salmin",
    place=Thesis,
    ID="sultana2014digital",
    entrytype="phdthesis",
    file="Sultana2014a.pdf",
    scholar_ok=True,
))

takase2014a = DB(WorkUnrelated(
    2014, "Capturing User-Generated Metadata",
    due="Unrelated to scripts",
    display="takase",
    authors="Takase, Wataru and Hasan, Adil and Matsumoto, Yoshimi and Sasaki, Takashi",
    place=ISGC,
    file="Takase2014a.pdf",
    ID="takase2014capturing",
    entrytype="inproceedings",
    scholar_ok=True,
))

tartler2014a = DB(WorkUnrelated(
    2014, "Static Analysis of Variability in System Software: The 90,000 #ifdefs Issue",
    due="Unrelated to scripts. Unrelated to provenance",
    display="tartler",
    authors="Tartler, Reinhard and Dietrich, Christian and Sincero, Julio and Schröder-Preikschat, Wolfgang and Lohmann, Daniel",
    place=ATC,
    file="Tartler2014a.pdf",
    isbn="978-1-931971-10-2",
    link="https://www.usenix.org/system/files/conference/atc14/atc14-paper-tartler.pdf",
    month="June",
    local="Philadelphia, PA, USA",
    pp="421--432",
    entrytype="inproceedings",
    cluster_id="11870190399872436523",
    scholar="http://scholar.google.com/scholar?cites=11870190399872436523&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

truskinger2014a = DB(WorkUnrelated(
    2014, "Practical analysis of big acoustic sensor data for environmental monitoring",
    due="Unrelated to scripts. Unrelated to provenance",
    display="truskinger",
    authors="Truskinger, Anthony and Cottman-Fields, Mark and Eichinski, Philip and Towsey, Michael and Roe, Paul",
    place=BdCloud,
    scholar="http://scholar.google.com/scholar?cites=5827323454162536025&as_sdt=2005&sciodt=0,5&hl=en",
    ID="truskinger2014practical",
    cluster_id="5827323454162536025",
    organization="IEEE",
    pp="91--98",
    entrytype="inproceedings",
    file="Truskinger2014a.pdf",
    scholar_ok=True,
))

vanschoren2014a = DB(WorkUnrelated(
    2014, "OpenML: networked science in machine learning",
    due="Unrelated to provenance",
    display="vanschoren",
    authors="Vanschoren, Joaquin and Van Rijn, Jan N and Bischl, Bernd and Torgo, Luis",
    place=SIGKDDExplorations,
    number="2",
    volume="15",
    pp="49--60",
    link="https://arxiv.org/abs/1407.7722",
    file="Vanschoren2014a.pdf",
    entrytype="article",
    publisher="ACM",
    cluster_id="17799286834300265378",
    scholar="http://scholar.google.com/scholar?cites=17799286834300265378&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

wibisono2014a = DB(WorkUnrelated(
    2014, "Generating scientific documentation for computational experiments using provenance",
    star="[analysis][xx] Analysis using Notebooks",
    due="Unrelated to provenance from scripts",
    may_be_related_to=["visualization", "query", "notebook"],
    summary="Creates Notebooks from Provenance extracted from other tools for analysis",
    display="wibisono",
    authors="Wibisono, Adianto and Bloem, Peter and de Vries, Gerben KD and Groth, Paul and Belloum, Adam and Bubak, Marian",
    place=IPAW,
    local="Cologne, Germany",
    file="Wibisono2014a.pdf",
    pp="168--179",
    entrytype="inproceedings",
    cluster_id="9861510789329800870",
    scholar="http://scholar.google.com/scholar?cites=9861510789329800870&as_sdt=2005&sciodt=0,5&hl=en",
    organization="Springer",
    scholar_ok=True,
))

wilson2014a = DB(WorkUnrelated(
    2014, "Best Practices for Scientific Computing",
    due="Unrelated to provenance",
    display="wilson",
    authors="Wilson, Greg and Aruliah, DA and Brown, C Titus and Hong, Neil P Chue and Davis, Matt and Guy, Richard T and Haddock, Steven HD and Huff, Kathryn D and Mitchell, Ian M and Plumbley, Mark D and Waugh, Ben and White, Ethan P and Wilson, Paul",
    place=PBio,
    pp="e1001745",
    doi="10.1371/ journal.pbio.1001745",
    month="January",
    volume="12",
    file="Wilson2014a.pdf",
    number="1",
    entrytype="article",
    publisher="Public Library of Science",
    cluster_id="13145098272845001519",
    scholar="http://scholar.google.com/scholar?cites=13145098272845001519&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

wohlin2014a = DB(WorkUnrelated(
    2014, "Guidelines for snowballing in systematic literature studies and a replication in software engineering",
    due="Unrelated to provenance",
    display="wohlin",
    authors="Wohlin, Claes",
    place=EASE,
    isbn="978-1-4503-2476-2",
    local="London, England, United Kingdom",
    pp="38",
    number="38",
    url="http://doi.acm.org/10.1145/2601248.2601268",
    doi="10.1145/2601248.2601268",
    publisher="ACM",
    file="Wohlin2014a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=8727281463705144333&as_sdt=5,33&sciodt=0,33&hl=en",
    cluster_id="8727281463705144333",
    organization="ACM",
    scholar_ok=True,
))

xie2014a = DB(WorkUnrelated(
    2014, "knitr: a comprehensive tool for reproducible research in R",
    due="Unrelated to provenance",
    display="xie",
    authors="Xie, Yihui",
    place=Book,
    booktitle="Implementing Reproducible Research",
    editors="Victoria Stodden, Friedrich Leisch, and Roger Peng",
    local="Boca Raton, Florida",
    file="Xie2014a.pdf",
    publisher="CRC Press/Taylor and Francis",
    scholar="http://scholar.google.com/scholar?cites=7354661509381038318&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="7354661509381038318",
    scholar_ok="aprox",
))

yoon2014a = DB(WorkUnrelated(
    2014, "A longitudinal study of programmers' backtracking",
    due="Unrelated to provenance",
    display="yoon",
    authors="Yoon, Young Seok and Myers, Brad A",
    place=VLHCC,
    publisher="IEEE",
    pp="101--108",
    file="Yoon2014a.pdf",
    entrytype="inproceedings",
    cluster_id="12656249408452560862",
    scholar="http://scholar.google.com/scholar?cites=12656249408452560862&as_sdt=2005&sciodt=0,5&hl=en",
    organization="IEEE",
    scholar_ok=True,
))

yue2014a = DB(WorkUnrelated(
    2014, "Granularity of geospatial data provenance",
    due="Unrelated to scripts",
    display="yue",
    authors="Yue, Peng and Zhang, Mingda and Guo, Xia and Tan, Zhenyu",
    place=IGARSS,
    ID="yue2014granularity",
    organization="IEEE",
    pp="4492--4495",
    entrytype="inproceedings",
    file="Yue2014a.pdf",
    cluster_id="7615627129004535671",
    scholar="http://scholar.google.com/scholar?cites=7615627129004535671&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

zhou2014a = DB(WorkBinaryOk(
    2014, "Towards a Data-centric Approach to Attribution in the Cloud",
    display="STAP",
    authors="Zhou, Wenchao",
    place=SecureCloud,
    pp="271--301",
    entrytype="incollection",
    ID="zhou2014towards",
    file="Zhou2014a.pdf#page=280",
    publisher="Springer",
    scholar_ok=True,
))
