# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *


acuna2016a = DB(WorkSnowball( # 0
    2016, "Extracting Semantics from Legacy Scientific Workflows",
    snowball=datetime(2017, 3, 6),
    display="wise",
    authors="Acuña, Ruben and Lacroix, Zoé",
    summary="Describes the summarization process of WISE",
    organization="IEEE",
    local="Laguna Hills, California, USA",
    place=ICSC,
    file="Acuna2016a.pdf",
    pp="9--16",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="wise2016",
    cluster_id="10756718796315871052",
    scholar="http://scholar.google.com/scholar?cites=10756718796315871052&as_sdt=2005&sciodt=0,5&hl=en",
    tracking="alert",
))

albert2016a = DB(WorkUnrelated(
    2016, "Frequency-based nanoparticle sensing over large field ranges using the ferromagnetic resonances of a magnetic nanodisc",
    due="Unrelated to scripts. Unrelated to provenance",
    display="albert",
    authors="Albert, Maximilian and Beg, Marijan and Chernyshenko, Dmitri and Bisotti, Marc-Antonio and Carey, Rebecca L and Fangohr, Hans and Metaxas, Peter J",
    place=Nanotechnology,
    pp="455--502",
    number="45",
    file="Albert2016a.pdf",
    publisher="IOP Publishing",
    ID="albert2016frequency",
    entrytype="article",
    volume="27",
    scholar_ok=True,
))

appelbaum2016a = DB(WorkUnrelated(
    2016, "Securing Big Data Provenance for Auditors: The Big Data Provenance Black Box as Reliable Evidence",
    due="Unrelated to scripts",
    display="appelbaum",
    authors="Appelbaum, Deniz",
    place=JETA,
    number="1",
    volume="13",
    scholar="http://scholar.google.com/scholar?cites=15756559099626168960&as_sdt=2005&sciodt=0,5&hl=en",
    ID="appelbaum2016securing",
    cluster_id="15756559099626168960",
    publisher="American Accounting Association",
    pp="17--36",
    entrytype="article",
    file="Appelbaum2016a.pdf",
    scholar_ok="aprox",
))

assis2016a = DB(WorkLang(
    2016, "PROVDOOP: CAPTURA, ARMAZENAMENTO E DISPONIBILIZAÇÃO DE DADOS DE PROVENIÊNCIA EM TEMPO DE EXECUÇÃO DE SISTEMAS SOBRE HADOOP",
    display="Assis",
    authors="de Assis, Vanessa Marques",
    school="Universidade Federal do Rio de Janeiro",
    place=Thesis,
    file="Assis2016a.pdf",
    entrytype="phdthesis",
    scholar_ok=True,
))

bajaber2016a = DB(WorkUnrelated(
    2016, "A Cloud-Based Platform for Democratizing and Socializing the Benchmarking Process",
    due="Unrelated to scripts. Unrelated to provenance",
    display="bajaber",
    authors="Bajaber, Fuad and Shafaat, Amin and Batarfi, Omar and Elshawi, Radwa and Altalhi, Abdulrahman and Barnawi, Ahmed and Sakr, Sherif",
    place=IJACSA,
    entrytype="article",
    number="2",
    volume="7",
    publisher="SCIENCE & INFORMATION SAI ORGANIZATION LTD 183-02 HILL SIDE AVE, JAMAICA, NY 11423 USA",
    pp="519--530",
    ID="bajaber2016cloud",
    file="Bajaber2016a.pdf",
    scholar_ok=True,
))

banati2016a = DB(WorkUnrelated(
    2016, "Reproducibility analysis of scientific workflows",
    due="Unrelated to scripts",
    display="banati",
    authors="Bánáti, Anna and Kacsuk, Péter and Kozlovszky, M",
    place=Thesis,
    scholar="http://scholar.google.com/scholar?cites=6912563327710992641&as_sdt=2005&sciodt=0,5&hl=en",
    local="Acta Politechnica Hungarica",
    cluster_id="6912563327710992641",
    file="Banati2016a.pdf",
    ID="banatireproducibility",
    entrytype="phdthesis",
    scholar_ok=True,
))

banati2016b = DB(WorkUnrelated(
    2016, "Evaluating the average reproducibility cost of the scientific workflows",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="banati",
    authors="Bánáti, Anna and Kárász, Péter and Kacsuk, Péter and Kozlovszky, Miklós",
    place=SISY,
    scholar="http://scholar.google.com/scholar?cites=6480427747464932229&as_sdt=2005&sciodt=0,5&hl=en",
    pp="79--84",
    cluster_id="6480427747464932229",
    file="Banati2016b.pdf",
    ID="banati2016evaluating",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
))

banati2016c = DB(WorkUnrelated(
    2016, "Classification of scientific workflows based on reproducibility analysis",
    due="Unrelated to scripts",
    display="banati",
    authors="Bánáti, A and Kacsuk, P and Kozlovszky, M",
    place=MIPRO,
    pp="327--331",
    file="Banati2016c.pdf",
    ID="banati2016classification",
    organization="IEEE",
    entrytype="inproceedings",
    scholar_ok=True,
))

bates2016a = DB(WorkUnrelated(
    2016, "Secure and Trustworthy Provenance Collection for Digital Forensics",
    due="Does not collect provenance. Deals with provenance security",
    summary="Compares provenance security between Hi-Fi and LPM/LSM",
    may_be_related_to=["security"],
    display="bates",
    authors="Bates, Adam and Pohly, Devin J and Butler, Kevin RB",
    place=DF,
    pp="141--176",
    publisher="Springer",
    ID="bates2016secure",
    entrytype="incollection",
    file="Bates2016a.pdf#page=147",
    scholar_ok=True,
))

bates2016b = DB(WorkUnrelated(
    2016, "Retrofitting Applications with Provenance-Based Security Monitoring",
    due="Unrelated to scripts",
    may_be_related_to=["database", "web"],
    display="bates",
    authors="Bates, Adam and Butler, Kevin and Dobra, Alin and Reaves, Brad and Cable, Patrick and Moyer, Thomas and Schear, Nabil",
    place=arXiv,
    scholar="http://scholar.google.com/scholar?cites=148265842025290423&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="148265842025290423",
    file="Bates2016b.pdf",
    ID="bates2016retrofitting",
    entrytype="article",
    scholar_ok=True,
))

bechberger2016a = DB(WorkLang(
    2016, "Besser Benchmarken",
    display="bechberger",
    authors="Bechberger, Johannes",
    place=Thesis,
    entrytype="article",
    file="Bechberger2016a.pdf",
    ID="bechbergerbesser",
    scholar_ok=True,
))

beebe2016a = DB(WorkUnrelated(
    2016, "A Complete Bibliography of Publications in SIAM Journal on Scientific and Statistical Computing",
    due="Unrelated to provenance, unrelated to scripts",
    display="beebe",
    authors="Beebe, Nelson HF",
    place=SIAMJSciStatComput,
    file="Beebe2016a.pdf",
    ID="beebe2016complete",
    entrytype="article",
    scholar_ok="aprox",
))

bennett2016a = DB(WorkUnrelated(
    2016, "Data Analytics as Data: A Semantic Workflow Approach",
    due="Non paper format",
    display="bennett",
    authors="Bennett, Kristin P and Erickson, John S and de Los Santos, Hannah and Norris, Spencer and Patton, Evan and Sheehan, John and McGuinness, Deborah L",
    place=NIPS,
    file="Bennett2016a.pdf",
    entrytype="article",
    ID="bennettdata",
    scholar_ok=True,
))

bezaire2016a = DB(WorkUnrelated(
    2016, "SimTracker tool and code template to design, manage and analyze neural network model simulations in parallel NEURON",
    due="Unrelated to scripts",
    may_be_related_to=["prog"],
    display="SimTracker",
    authors="Bezaire, Marianne and Raikov, Ivan and Burk, Kelly and Armstrong, Caren and Soltesz, Ivan",
    place=bioRxiv,
    file="Bezaire2016a.pdf",
    publisher="Cold Spring Harbor Labs Journals",
    pp="081927",
    ID="bezaire2016simtracker",
    entrytype="article",
    summary="Manage provenance from Neuron programming language",
    scholar_ok=True,
))

bortolameotti2016a = DB(WorkUnrelated(
    2016, "Reliably determining data leakage in the presence of strong attackers",
    due="Unrelated to scripts",
    may_be_related_to=["security"],
    display="bortolameotti",
    authors="Bortolameotti, Riccardo and Peter, Andreas and Everts, Maarten H and Jonker, Willem and Hartel, Pieter",
    place=ACSAC,
    pp="484--495",
    file="Bortolameotti2016a.pdf",
    ID="bortolameotti2016reliably",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

cao2016a = DB(WorkUnrelated(
    2016, "Revealing the Detailed History of Script Outputs with Hybrid Provenance Queries",
    due="Non paper format",
    display="cao",
    authors="Cao, Yang and Vu, Qiwen Wang and Zhang, Qian and Thavasimani, Priyaa",
    place=Unpublished,
    file="Cao2016a.pdf",
    entrytype="article",
    ID="caorevealing",
    scholar_ok=True,
))

cao2016b = DB(WorkUnrelated(
    2016, "ProvONE: extending PROV to support the DataONE scientific community",
    due="Unrelated to scripts collection",
    display="cao",
    authors="Cao, Yang and Jones, Christopher and Cuevas-Vicentt?n, V?ctor and Jones, Matthew B and Ludäscher, Bertram and McPhillips, Timothy and Missier, Paolo and Schwalm, Christopher and Slaughter, Peter and Vieglais, Dave and others",
    place=Unpublished,
    file="Cao2016b.pdf",
    entrytype="article",
    ID="caoprovone",
    scholar_ok=True,
))

carvalho2016a = DB(WorkUnrelated(
    2016, "Converting Scripts into Reproducible Workflow Research Objects",
    due="Does not collect provenance from scripts. Only uses YesWorkflow",
    summary="Describes a methodoly for transforming scripts into workflows. Uses yesworkflow to comprehend the script, then asks a curator to reimplement it in a SWfMS",
    display="carvalho",
    authors="Carvalho, LAMC and Belhajjame, Khalid and Medeiros, Claudia Bauzer",
    place=eSoN,
    file="Carvalho2016a.pdf",
    cluster_id="7559686675623634215",
    scholar="http://scholar.google.com/scholar?cites=7559686675623634215&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
))

carver2016a = DB(WorkUnrelated(
    2016, "Software Engineering for Science",
    due="Unrelated to provenance",
    display="carver",
    authors="Carver, Jeffrey C and Chue Hong, Neil P and Thiruvathukal, George K",
    place=Book,
    file="Carver2016a.pdf",
    publisher="CRC Press",
    entrytype="book",
    ID="carver2016software",
    excerpt="[1] JC Carver. First International Workshop on Software Engineering for Computational Science and Engineering. Computing in Science Engi- neering, 11(2):711, March 2009.   ... [2] JC Carver. Report: The Second International Workshop on Software Engineering for CSE. Computing ",
    scholar_ok=True,
))

chirigati2016a = DB(WorkBinarySnowball(
    2016, "ReproZip: computational reproducibility with ease",
    due="Unrelated to provenance. May be seem as prospective provenance, though",
    may_be_related_to=["vm"],
    display="reprozip",
    authors="Chirigati, Fernando and Rampin, Rémi and Shasha, Dennis and Freire, Juliana",
    summary="Demonstrates ReproZip with non-trivial examples packed in a linux machine and reproduced in different machines and OS",
    place=SIGMOD,
    file="Chirigati2016a.pdf",
    volume="16",
    cluster_id="3434488747211084140",
    scholar="http://scholar.google.com/scholar?cites=3434488747211084140&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
))

correndo2016a = DB(WorkUnrelated(
    2016, "Knowledge Base Service architecture Specification v1",
    due="Unrelated to scripts",
    surveyhide="1",
    display="correndo",
    authors="Correndo, Gianluca and Zigna, Jean-Michel and Haugommard, Anne",
    place=TechReport,
    entrytype="article",
    publisher="EO4wildlife Consortium",
    ID="correndo2016knowledge",
    file="correndo2016a.pdf",
))

costa2016a = DB(WorkUnrelated(
    2016, "SPPV: Visualizing Software Process Provenance Data",
    due="Unrelated to scripts",
    may_be_related_to=["visualization"],
    display="costa",
    authors="Costa, Gabriella CB and Schots, Marcelo and Oliveira, Weiner EB and LO, Humberto and Dalpra, Cláudia ML and Braga, Regina and David, José Maria N and Marcos, A and Miguel, Victor Ströele and Campos, Fernanda",
    place=VEM,
    file="Costa2016a.pdf#page=56",
    pp="49",
    ID="costa2016sppv",
    entrytype="article",
    scholar_ok=True,
))

cruz2016a = DB(WorkSnowball( # 0
    2016, "SisGExp: Rethinking Long-Tail Agronomic Experiments",
    snowball=datetime(2017, 3, 6),
    display="SisGExp",
    authors="da Cruz, Sergio Manuel Serra and do Nascimento, José Antonio Pires",
    place=IPAW,
    file="Cruz2016a.pdf#page=219",
    pp="214--217",
    ID="da2016sisgexp",
    organization="Springer",
    entrytype="inproceedings",
    citation_file="sisgexp2016",
    scholar="http://scholar.google.com/scholar?cites=1405858849165435135&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="1405858849165435135",
    scholar_ok=True,
    tracking="alert",
    local="McLean, VA, USA",
))

curcin2016a = DB(WorkUnrelated(
    2016, "Data provenance as a method of supporting reproducibility in the learning health system",
    due="Unrelated to scripts collection",
    display="curcin",
    authors="Curcin, Vasa",
    place=LHS,
    file="Curcin2016a.pdf",
    publisher="Wiley Online Library",
    ID="curcin2016data",
    entrytype="article",
    link="http://onlinelibrary.wiley.com/doi/10.1002/lrh2.10019/full",
    summary="Suggest using provenance",
    scholar_ok=True,
))

eglen2016a = DB(WorkUnrelated(
    2016, "Towards standard practices for sharing computer code and programs in neuroscience",
    due="Does not propose mechanism for provenance collection",
    display="eglen",
    authors="Eglen, Stephen and Marwick, Ben and Halchenko, Yaroslav and Hanke, Michael and Sufi, Shoaib and Gleeson, Padraig and Silver, R Angus and Davison, Andrew and Lanyon, Linda and Abrams, Mathew and others",
    place=bioRxiv,
    pp="045104",
    file="Eglen2016a.pdf",
    publisher="Cold Spring Harbor Labs Journals",
    ID="eglen2016towards",
    entrytype="article",
    scholar_ok=True,
))

eichinski2016a = DB(WorkSnowball( # 0
    2016, "Datatrack: An R package for managing data in a multi-stage experimental workflow",
    snowball=datetime(2017, 3, 6),
    display="eichinski",
    authors="Eichinski, Philip and Roe, Paul",
    place=eScience,
    publisher="IEEE",
    local="Baltimore, Maryland, USA",
    pp="1--8",
    file="Eichinski2016a.pdf",
    entrytype="inproceedings",
    ID="eichinski2016datatrack",
    citation_file="datatrack2016",
    scholar="http://scholar.google.com/scholar?cites=6970310266072085334&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="6970310266072085334",
    scholar_ok=True,
    tracking="alert",
))

elsethagen2016a = DB(WorkUnrelated(
    2016, "Data provenance hybridization supporting extreme-scale scientific workflow applications",
    due="Unrelated to scripts",
    display="elsethagen",
    authors="Elsethagen, Todd and Stephan, Eric and Raju, Bibi and Schram, Malachi and MacDuff, Matt and Kerbyson, Darrern and van Dam, Kerstin Kleese and Singh, Alok and Altintas, Ilkay",
    place=NYSDS,
    scholar="http://scholar.google.com/scholar?cites=17922112009012803396&as_sdt=2005&sciodt=0,5&hl=en",
    pp="1--10",
    cluster_id="17922112009012803396",
    file="Elsethagen2016a.pdf",
    ID="elsethagen2016data",
    organization="IEEE",
    entrytype="inproceedings",
    star="[collection] non-script language: java",
    scholar_ok=True,
))

erickson2016a = DB(WorkUnrelated(
    2016, "Addressing Scientific Rigor in Data Analytics Using Semantic Workflows",
    due="Cites noWorkflow as an way to facilitate provenance collection on scripts, but don't provide an alternative",
    display="erickson",
    authors="Erickson, John S and Sheehan, John and Bennett, Kristin P and McGuinness, Deborah L",
    summary="Shows that semantic workflows can improve scientific rigor in data analysis",
    place=IPAW,
    file="Erickson2016a.pdf",
    pp="187--190",
    volume="9672",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
    local="McLean, VA, USA",
))

gammack2016a = DB(WorkUnrelated(
    2016, "Modelling Provenance Collection Points and Their Impact on Provenance Graphs",
    due="Unrelated to scripts. Just cites approaches that capture provenance",
    display="gammack",
    authors="Gammack, David and Scott, Steve and Chapman, Adriane P",
    place=IPAW,
    pp="146--157",
    file="Gammack2016a.pdf#page=154",
    ID="gammack2016modelling",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
    local="McLean, VA, USA",
))

gehani2016a = DB(WorkOk(
    2016, "Scaling spade to “big provenance”",
    surveyhide="1",
    due="Unrelated to scripts",
    display="gehani",
    authors="Gehani, Ashish and Kazmi, Hasanat and Irshad, Hassaan",
    place=TaPP,
    pp="26--33",
    entrytype="inproceedings",
    organization="USENIX Association",
    ID="gehani2016scaling",
    file="gehani2016a.pdf",
))

geit2016a = DB(WorkUnrelated(
    2016, "BluePyOpt: Leveraging open source software and cloud infrastructure to optimise model parameters in neuroscience",
    due="Unrelated to provenance",
    display="geit",
    authors="Van Geit, Werner and Gevaert, Michael and Chindemi, Giuseppe and Rössert, Christian and Courcol, Jean-Denis and Muller, Eilif B and Schürmann, Felix and Segev, Idan and Markram, Henry",
    place=FNInf,
    link="http://journal.frontiersin.org/article/10.3389/fninf.2016.00017/full",
    number="17",
    volume="10",
    doi="10.3389/fninf.2016.00017",
    file="Geit2016a.pdf",
    entrytype="article",
    publisher="Frontiers Media SA",
    cluster_id="2575937958400918238",
    scholar="http://scholar.google.com/scholar?cites=2575937958400918238&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

giesler2016a = DB(WorkUnrelated(
    2016, "UniProv: A Flexible Provenance Tracking System for UNICORE",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="giesler",
    authors="Giesler, André and Czekala, Myriam and Hagemeier, Björn and Grunzke, Richard",
    place=JARA_HPC,
    organization="Springer",
    entrytype="inproceedings",
    ID="giesler2016uniprov",
    pp="233--242",
    file="Giesler2016a.pdf",
    scholar_ok=True,
))

gil2016a = DB(WorkUnrelated(
    2016, "Toward the Geoscience Paper of the Future: Best practices for documenting and sharing research from data to software to provenance",
    due="Unrelated to script collection. Only describes requirements",
    display="gil",
    authors="Gil, Yolanda and David, Cédric H and Demir, Ibrahim and Essawy, Bakinam T and Fulweiler, Robinson W and Goodall, Jonathan L and Karlstrom, Leif and Lee, Huikyo and Mills, Heath J and Oh, Ji-Hyun and others",
    place=ESSci,
    scholar="http://scholar.google.com/scholar?cites=5073979399526982017&as_sdt=2005&sciodt=0,5&hl=en",
    ID="gil2016toward",
    pp="388--415",
    entrytype="article",
    number="10",
    publisher="Wiley Online Library",
    link="http://onlinelibrary.wiley.com/doi/10.1002/2015EA000136/full",
    cluster_id="5073979399526982017",
    file="Gil2016a.pdf",
    volume="3",
    scholar_ok=True,
))

goehring2016a = DB(WorkUnrelated(
    2016, "Decibel: transactional branched versioning for relational data systems",
    due="Unrelated to scripts",
    display="goehring",
    authors="Goehring, David",
    place=Thesis,
    file="Goehring2016a.pdf",
    entrytype="phdthesis",
    ID="goehring2016decibel",
    local="Massachusetts Institute of Technology",
    school="Massachusetts Institute of Technology",
    scholar_ok=True,
))

gounares2016a = DB(WorkUnrelated(
    2016, "Purity Analysis Using White List/Black List Analysis",
    alias=(2016, "Purity analysis using white list/black list analysis", "Gounares, Alexander G and Li, Ying and Garrett, Charles D and Noakes, Michael D"),
    due="Non paper format",
    display="gounares",
    authors="Gounares, Alexander G and Li, Ying and Garrett, Charles D and Noakes, Michael D",
    place=Patent,
    note="US Patent App. 15/005,643",
    month="jan",
    publisher="Google Patents",
    ID="gounares2016purity",
    entrytype="misc",
    scholar_ok=True,
))

halevy2016a = DB(WorkUnrelated(
    2016, "Goods: Organizing googles datasets",
    due="Unrelated to scripts",
    display="halevy",
    authors="Halevy, Alon and Korn, Flip and Noy, Natalya F and Olston, Christopher and Polyzotis, Neoklis and Roy, Sudip and Whang, Steven Euijong",
    place=SIGMOD,
    file="Halevy2016a.pdf",
    entrytype="inproceedings",
    scholar_ok=True,
))

hammer2016a = DB(WorkUnrelated(
    2016, "A vision for online verification-validation",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hammer",
    authors="Hammer, Matthew A and Chang, Bor-Yuh Evan and Van Horn, David",
    place=GPCE,
    pp="190--201",
    file="Hammer2016a.pdf",
    ID="hammer2016vision",
    organization="ACM",
    entrytype="inproceedings",
    scholar_ok=True,
))

hammer2016b = DB(WorkUnrelated(
    2016, "Typed Adapton: Refinement types for nominal memoization",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hammer",
    authors="Hammer, Matthew A and Dunfield, Joshua",
    place=arXiv,
    file="Hammer2016b.pdf",
    entrytype="article",
    ID="hammer2016typed",
    scholar_ok=True,
))

hashem2016a = DB(WorkLang(
    2016, "Modélisation intégratrice du traitement BigData",
    display="hashem",
    authors="Hashem, Hadi",
    place=Thesis,
    file="Hashem2016a.pdf",
    local="Université Paris-Saclay",
    ID="hashem2016modelisation",
    entrytype="phdthesis",
    school="Université Paris-Saclay",
    scholar_ok=True,
))

hill2016a = DB(WorkUnrelated(
    2016, "Trials and tribulations of developers of intelligent systems: A field study",
    due="Unrelated to scripts. Unrelated to provenance",
    display="hill",
    authors="Hill, Charles and Bellamy, Rachel and Erickson, Thomas and Burnett, Margaret",
    place=VLHCC,
    cluster_id="711104377809841471",
    scholar="http://scholar.google.com/scholar?cites=711104377809841471&as_sdt=2005&sciodt=0,5&hl=en",
    pp="162--170",
    entrytype="inproceedings",
    file="Hill2016a.pdf",
    ID="hill2016trials",
    organization="IEEE",
    scholar_ok=True,
))

ioannidis2016a = DB(WorkUnrelated(
    2016, "Anticipating consequences of sharing raw data and code and of awarding badges for sharing",
    due="Unrelated to scripts. Unrelated to provenance",
    may_be_related_to=["reproducibility"],
    display="ioannidis",
    authors="Ioannidis, John PA",
    place=JCE,
    scholar="http://scholar.google.com/scholar?cites=1254890077425144712&as_sdt=2005&sciodt=0,5&hl=en",
    pp="258",
    cluster_id="1254890077425144712",
    file="Ioannidis2016a.pdf",
    publisher="Elsevier Science Ltd.",
    ID="ioannidis2016anticipating",
    entrytype="article",
    star="[motivation]",
    volume="70",
    scholar_ok=True,
))

ivie2016a = DB(WorkUnrelated(
    2016, "PRUNE: A Preserving Run Environment for Reproducible Scientific Computing",
    due="Unrelated to scripts",
    may_be_related_to=["evolution", " repository"],
    display="ivie",
    authors="Ivie, Peter and Thain, Douglas",
    place=eScience,
    entrytype="article",
    file="Ivie2016a.pdf",
    ID="ivieprune",
    summary="Repository that allows users to declare relationships between experiment files, data, and envoriment",
    scholar_ok=True,
))

ji2016a = DB(WorkBinaryOk(
    2016, "RecProv: Towards Provenance-Aware User Space Record and Replay",
    display="RecProv",
    authors="Ji, Yang and Lee, Sangho and Lee, Wenke",
    place=IPAW,
    pp="3--15",
    file="Ji2016a.pdf#page=13",
    ID="ji2016recprov",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
    local="McLean, VA, USA",
))

jones2016a = DB(WorkUnrelated(
    2016, "DataONE: A Data Federation with Provenance Support",
    due="Unrelated to scripts",
    display="jones",
    authors="Jones, Matthew B and Ludäscher, Bertram and McPhillips, Timothy and Missier, Paolo and Schwalm, Christopher and Slaughter, Peter and Vieglais, Dave and Walker, Lauren and Wei, Yaxing",
    place=IPAW,
    pp="230",
    file="Jones2016a.pdf#page=235",
    ID="jones2016dataone",
    organization="Springer",
    entrytype="inproceedings",
    summary="Use yesworkflow",
    volume="9672",
    scholar_ok=True,
    local="McLean, VA, USA",
))

karsai2016a = DB(WorkUnrelated(
    2016, "Clustering Provenance",
    due="Unrelated to scripts",
    may_be_related_to=["visualization", "clustering"],
    display="karsai",
    authors="Karsai, Linus",
    place=Thesis,
    file="Karsai2016a.pdf",
    entrytype="phdthesis",
    ID="karsai2016clustering",
    local="University of Sydney",
    scholar_ok="aprox",
))

kohwalter2016a = DB(WorkUnrelated(
    2016, "Prov Viewer: a graph-based visualization tool for interactive exploration of provenance data",
    due="Unrelated to scripts",
    may_be_related_to=["visualization"],
    display="Prov Viewer",
    authors="Kohwalter, Troy and Oliveira, Thiago and Freire, Juliana and Clua, Esteban and Murta, Leonardo",
    place=IPAW,
    file="Kohwalter2016a.pdf",
    pp="71--82",
    entrytype="inproceedings",
    organization="Springer",
    cluster_id="13425560469830335",
    scholar="http://scholar.google.com/scholar?cites=13425560469830335&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
    local="McLean, VA, USA",
))

kuklin2016a = DB(WorkUnrelated(
    2016, "Automatic Launch and Tracking the Computational Simulations with LiFlow and Sumatra",
    due="Unrelated to script collection",
    may_be_related_to=["workflow"],
    summary="Uses Sumatra to collect provenance from scripts defined in the LiFlow workflow system",
    display="kuklin",
    authors="Kuklin, Evgeniy and Ushenin, Konstantin",
    place=URAL_PDC,
    entrytype="article",
    ID="kuklinautomatic",
    file="Kuklin2016a.pdf",
    scholar_ok=True,
))

ledet2016a = DB(WorkUnrelated(
    2016, "A Model-Driven Engineering Framework for Computational Replicability and Reproducibility",
    due="Unrelated to scripts",
    display="ledet",
    authors="Ledet, Joseph",
    place=Thesis,
    file="Ledet2016a.pdf",
    entrytype="phdthesis",
    ID="ledet2016model",
    local="Middle East Technical University, Ankara, Turkey",
    school="Middle East Technical University, Ankara, Turkey",
    scholar_ok=True,
))

lemieux2016a = DB(WorkUnrelated(
    2016, "Provenance: Past, Present and Future in Interdisciplinary and Multidisciplinary Perspective",
    due="Unrelated to scripts",
    display="lemieux",
    authors="Lemieux, Victoria L and others",
    pp="3--45",
    place=Book,
    bookname="Building Trust in Information",
    file="Lemieux2016a.pdf#page=20",
    publisher="Springer",
    ID="lemieux2016provenance",
    entrytype="incollection",
    star="[motivation] use-cases",
    scholar_ok=True,
))

ludascher2016a = DB(WorkUnrelated(
    2016, "A Brief Tour through Provenance in Scientific Workflows and Databases",
    due="Unrelated to scripts. It only surveys provenance in database and cites noWorkflow as a way to open grey boxes and collect fine-grained provenance",
    display="ludäscher",
    authors="Ludäscher, Bertram",
    summary="Surveys provenance in databases",
    place=TechReport,
    file="Ludascher2016a.pdf",
    entrytype="article",
    scholar_ok=True,
))

ma2016a = DB(WorkUnrelated(
    2016, "Documenting provenance for reproducible marine ecosystem assessment in open science",
    due="Unrelated to scripts",
    display="ma",
    authors="Fox, Xiaogang Ma Peter and Beaulieu, Stace E and Fu, Linyun and Di Stefano, Massimo and West, Patrick",
    scholar="http://scholar.google.com/scholar?cites=5145835200313997412&as_sdt=2005&sciodt=0,5&hl=en",
    publisher="IGI Global",
    pp="100",
    ID="fox2016documenting",
    cluster_id="5145835200313997412",
    entrytype="article",
    place=Book,
    link="http://www.igi-global.com/chapter/documenting-provenance-for-reproducible-marine-ecosystem-assessment-in-open-science/166838",
    bookname="Oceanographic and Marine Cross-Domain Data Management for Sustainable Development",
    scholar_ok=True,
))

mcdougal2016a = DB(WorkUnrelated(
    2016, "Reproducibility in computational neuroscience models and simulations",
    due="Unrelated to scripts",
    display="mcdougal",
    authors="McDougal, Robert A and Bulanova, Anna S and Lytton, William W",
    place=TBME,
    scholar="http://scholar.google.com/scholar?cites=12334454133982714182&as_sdt=2005&sciodt=0,5&hl=en",
    pp="2021--2035",
    cluster_id="12334454133982714182",
    number="10",
    file="Mcdougal2016a.pdf",
    publisher="IEEE",
    ID="mcdougal2016reproducibility",
    entrytype="article",
    volume="63",
    excerpt="Abstract: Objective: Like all scientific research, computational neuroscience research must be reproducible. Big data science, including simulation research, cannot depend exclusively on journal articles as the method to provide the sharing and transparency required for ",
    scholar_ok=True,
))

meyer2016a = DB(WorkSnowball( # 0
    2016, "pypet: A Python Toolkit for Data Management of Parameter Explorations",
    snowball=datetime(2017, 3, 6),
    display="pypet",
    authors="Meyer, Robert and Obermayer, Klaus",
    place=FNInf,
    file="Meyer2016a.pdf",
    publisher="Frontiers Media SA",
    ID="meyer2016pypet",
    entrytype="article",
    link="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4996826/",
    volume="10",
    pp="1--16",
    citation_file="pypet2016",
    scholar_ok=True,
    cluster_id="10634720128698949546",
    scholar="http://scholar.google.com/scholar?cites=10634720128698949546&as_sdt=2005&sciodt=0,5&hl=en",
    tracking="alert",
))

miao2016a = DB(WorkUnrelated( # 2
    2016, "ProvDB: A System for Lifecycle Management of Collaborative Analysis Workflows",
    due="Excluding Technical Report",
    snowball=datetime(2017, 3, 6),
    display="ProvDB",
    authors="Miao, Hui and Chavan, Amit and Deshpande, Amol",
    place=arXiv,
    file="Miao2016a.pdf",
    cluster_id="11363542574280705057",
    scholar="http://scholar.google.com/scholar?cites=11363542574280705057&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="article",
    citation_file="provdb2016",
    scholar_ok=True,
    tracking="alert",
))

michaelides2016a = DB(WorkSnowball( # 0
    2016, "Intermediate Notation for Provenance and Workflow Reproducibility",
    snowball=datetime(2017, 3, 6),
    display="michaelides",
    authors="Michaelides, Danius T and Parker, Richard and Charlton, Chris and Browne, William J and Moreau, Luc",
    summary="Collects provenance of Blockly visual programming system in INPWR format and exports to PROV or back to Blockly programs",
    place=IPAW,
    file="Michaelides2016a.pdf",
    organization="Springer",
    pp="83--94",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="michaelides2016",
    cluster_id="14853632123069176016",
    scholar="http://scholar.google.com/scholar?cites=14853632123069176016&as_sdt=2005&sciodt=0,5&hl=en",
    tracking="alert",
    local="McLean, VA, USA",
))

michielon2016a = DB(WorkLang(
    2016, "Stima non distorta in mediana del modello di Rash",
    display="michielon",
    authors="Michielon, Edoardo",
    place=Thesis,
    entrytype="article",
    ID="michielon2016stima",
    file="Michielon2016a.pdf",
    scholar_ok=True,
))

miksa2016a = DB(WorkUnrelated(
    2016, "Identifying impact of software dependencies on replicability of biomedical workflows",
    due="Unrelated to scripts",
    may_be_related_to=["workflow"],
    display="miksa",
    authors="Miksa, Tomasz and Rauber, Andreas and Mina, Eleni",
    place=JBIOBL,
    pp="232--254",
    file="Miksa2016a.pdf",
    publisher="Elsevier",
    ID="miksa2016identifying",
    entrytype="article",
    volume="64",
    scholar_ok=True,
))

missier2016a = DB(WorkUnrelated( # Survey
    2016, "The lifecycle of provenance metadata and its associated challenges and opportunities",
    due="Unrelated to script collection",
    display="missier",
    authors="Missier, Paolo",
    summary="Presents the history of PROV, challenges and approaches that capture provenance",
    place=Book,
    bookname="Building Trust in Information",
    file="Missier2016a.pdf",
    number="1605.01229",
    entrytype="article",
    scholar_ok=True,
))

moehrke2016a = DB(WorkUnrelated(
    2016, "Extending the FHIR standard to handle provenance",
    due="Unrelated to scripts",
    display="moehrke",
    authors="Moehrke, John and Rosenthal, Arnon and Chapman, Adriane",
    place=ProvWeek,
    file="Moehrke2016a.pdf",
    entrytype="article",
    ID="moehrke2016extending",
    scholar_ok=True,
))

moreno2016a = DB(WorkUnrelated(
    2016, "Improving financial computation speed with full and subproblem memoization",
    due="Unrelated to scripts. Specific use-case",
    display="moreno",
    authors="Moreno, Alexander and Balch, Tucker",
    place=CCPE,
    number="3",
    volume="28",
    scholar="http://scholar.google.com/scholar?cites=6449399811966162101&as_sdt=2005&sciodt=0,5&hl=en",
    ID="moreno2016improving",
    cluster_id="6449399811966162101",
    publisher="Wiley Online Library",
    pp="905--915",
    entrytype="article",
    file="Moreno2016a.pdf",
    scholar_ok=True,
))

moyer2016a = DB(WorkUnrelated(
    2016, "Leveraging Data Provenance to Enhance Cyber Resilience",
    due="Unrelated to scripts. Just cites approaches that collect provenance from scripts",
    display="moyer",
    authors="Moyer, Thomas and Chadha, Karishma and Cunningham, Robert and Schear, Nabil and Smith, Warren and Bates, Adam and Butler, Kevin and Capobianco, Frank and Jaeger, Trent and Cable, Patrick",
    place=SECDEV,
    volume="26",
    ID="moyer2016leveraging",
    star="[security] provenance usage for security",
    pp="28",
    entrytype="article",
    file="Moyer2016a.pdf",
    scholar_ok=True,
))

niu2016a = DB(WorkUnrelated(
    2016, "Provenance-aware versioned dataworkspaces",
    due="Unrealted to scripts",
    may_be_related_to=["workflow", "evolution"],
    display="niu",
    authors="Niu, Xing and Arab, B and Gawlick, Dieter and Liu, O Kennedy ZH and Krishnaswamy, Vasudha and Glavic, B",
    place=TaPP,
    file="Niu2016a.pdf",
    entrytype="inproceedings",
    scholar="http://scholar.google.com/scholar?cites=12525180657703236586&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="12525180657703236586",
    publisher="TaPP",
    scholar_ok=True,
    local="McLean, VA, USA",
))

oliveira2016a = DB(WorkUnrelated(
    2016, "Analyzing Provenance Across Heterogeneous Provenance Graphs",
    due="Unrelated to scripts",
    display="oliveira",
    authors="Oliveira, Wellington and Missier, Paolo and Ocaña, Kary and de Oliveira, Daniel and Braganholo, Vanessa",
    summary="Links provenance from heterogeuous sources",
    place=IPAW,
    file="Oliveira2016a.pdf",
    organization="Springer",
    pp="57--70",
    entrytype="inproceedings",
    scholar_ok=True,
    local="McLean, VA, USA",
))

oxvig2016a = DB(WorkSnowball( # 1
    2016, "Storing Reproducible Results from Computational Experiments using Scientific Python Packages",
    snowball=datetime(2017, 3, 6),
    display="oxvig",
    authors="Oxvig, Christian Schou and Arildsen, Thomas and Larsen, Torben",
    place=SciPy,
    local="Austin, TX, USA",
    publisher="SciPy",
    scholar="http://scholar.google.com/scholar?cites=11450193917748753420&as_sdt=2005&sciodt=0,5&hl=en",
    pp="45--50",
    cluster_id="11450193917748753420",
    file="Oxvig2016a.pdf",
    ID="oxvig2016storing",
    entrytype="inproceedings",
    citation_file="magni2016",
    scholar_ok=True,
    tracking="alert",
))

packer2016a = DB(WorkUnrelated(
    2016, "A methodology to take account of diversity in collective adaptive system",
    due="Unrelated to scripts",
    display="packer",
    authors="Packer, Heather and Moreau, Luc",
    place=TechReport,
    ID="packer2016methodology",
    entrytype="article",
    file="Packer2016a.pdf",
    scholar_ok=True,
))

perez2016a = DB(WorkUnrelated(
    2016, "Conservation of Computational Scientific Execution Environments for Workflow-based Experiments Using Ontologies",
    due="Unrelated to scripts",
    display="perez",
    authors="Santana Pérez, Idafen",
    place=Thesis,
    file="Perez2016a.pdf",
    entrytype="phdthesis",
    ID="santana2016conservation",
    local="ETSI_Informatica",
    school="ETSI_Informatica",
    scholar_ok=True,
))

pimentel2016a = DB(WorkSnowball( # 1
    2016, "Tracking and analyzing the evolution of provenance from scripts",
    snowball=datetime(2017, 3, 6),
    display="noworkflow a",
    authors="Pimentel, João Felipe and Freire, Juliana and Braganholo, Vanessa and Murta, Leonardo",
    summary="Proposes tracking provenance evolution history",
    place=IPAW,
    file="Pimentel2016a.pdf",
    organization="Springer",
    pp="16--28",
    cluster_id="3783364081347190151",
    scholar="http://scholar.google.com/scholar?cites=3783364081347190151&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="noworkflow2016a",
    tracking="alert",
    local="McLean, VA, USA",
))

pimentel2016b = DB(WorkSnowball( # 3
    2016, "Fine-grained provenance collection over scripts through program slicing",
    snowball=datetime(2017, 3, 6),
    display="noworkflow b",
    authors="Pimentel, João Felipe and Freire, Juliana and Murta, Leonardo and Braganholo, Vanessa",
    summary="Proposes fine-grained provenance collection for noWorkflow",
    place=IPAW,
    file="Pimentel2016b.pdf",
    organization="Springer",
    pp="199--203",
    cluster_id="16620110626892658977",
    scholar="http://scholar.google.com/scholar?cites=16620110626892658977&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="noworkflow2016b",
    tracking="alert",
    local="McLean, VA, USA",
))

pimentel2016c = DB(WorkSnowball( # 2
    2016, "Yin & Yang: demonstrating complementary provenance from noWorkflow & YesWorkflow",
    snowball=datetime(2017, 3, 6),
    display="yw*nw a",
    authors="Pimentel, João Felipe and Dey, Saumen and McPhillips, Timothy and Belhajjame, Khalid and Koop, David and Murta, Leonardo and Braganholo, Vanessa and Ludäscher, Bertram",
    place=IPAW,
    file="Pimentel2016c.pdf",
    organization="Springer",
    pp="161--165",
    cluster_id="5514086202045212339",
    scholar="http://scholar.google.com/scholar?cites=5514086202045212339&as_sdt=2005&sciodt=0,5&hl=en",
    entrytype="inproceedings",
    scholar_ok=True,
    citation_file="ywnw2016",
    tracking="alert",
    local="McLean, VA, USA",
))

pimentel2016d = DB(WorkUnrelated(
    2016, "Yin & Yang Demo GitHub",
    due="Excluding TechReport",
    display="yw*nw b",
    authors="Pimentel, João Felipe and Dey, Saumen and McPhillips, Timothy and Belhajjame, Khalid and Koop, David and Murta, Leonardo and Braganholo, Vanessa and Ludäscher, Bertram",
    place=TechReport,
    link="github.com/gems-uff/yin-yang-demo",
    entrytype="techreport",
    scholar_ok="impossible",
))

pimentel2016e = DB(WorkUnrelated(
    2016, "NOWORKFLOW",
    due="Excluding non-paper format",
    summary="Chirigati's presentation. Scholar attributted the wrong author",
    display="pimentel",
    authors="Pimentel, João Felipe and Murta, Leonardo and Braganholo, Vanessa and Chirigab, Fernando and Koop, David and Freire, Juliana",
    entrytype="article",
    place=Unpublished,
    file="Pimentel2016e.pdf",
    ID="pimentelnoworkflow",
    scholar_ok=True,
))

qin2016a = DB(WorkUnrelated(
    2016, "Metadata and Reproducibility: A Case Study of Gravitational Wave Research Data Management",
    due="Unrelated to scripts",
    display="qin",
    authors="Qin, Jian and Dobreski, Brian and Brown, Duncan",
    place=IJDC,
    pp="218--231",
    volume="11",
    entrytype="article",
    ID="qin2016metadata",
    file="Qin2016a.pdf",
    number="1",
    scholar_ok=True,
))

ragan2016a = DB(WorkUnrelated(
    2016, "Characterizing provenance in visualization and data analysis: an organizational framework of provenance types and purposes",
    due="Unrelated to scripts",
    may_be_related_to=["visualization"],
    display="ragan",
    authors="Ragan, Eric D and Endert, Alex and Sanyal, Jibonananda and Chen, Jian",
    place=TVCG,
    scholar="http://scholar.google.com/scholar?cites=8555921255023069817&as_sdt=2005&sciodt=0,5&hl=en",
    pp="31--40",
    cluster_id="8555921255023069817",
    number="1",
    file="Ragan2016a.pdf",
    publisher="IEEE",
    ID="ragan2016characterizing",
    entrytype="article",
    star="[survey]",
    volume="22",
    scholar_ok=True,
))

ragavan2016a = DB(WorkUnrelated(
    2016, "Foraging Among an Overabundance of Similar Variants",
    due="Unrelated to provenance",
    display="ragavan",
    authors="Srinivasa Ragavan, Sruti and Kuttal, Sandeep Kaur and Hill, Charles and Sarma, Anita and Piorkowski, David and Burnett, Margaret",
    place=CHI,
    publisher="ACM",
    pp="3509--3521",
    file="Ragavan2016a.pdf",
    entrytype="inproceedings",
    cluster_id="13916331246583843944",
    scholar="http://scholar.google.com/scholar?cites=13916331246583843944&as_sdt=2005&sciodt=0,5&hl=en",
    organization="ACM",
    scholar_ok=True,
))

ray2016a = DB(WorkUnrelated(
    2016, "NSDF: Neuroscience simulation data format",
    due="Unrelated to provenance",
    display="ray",
    authors="Ray, Subhasis and Chintaluri, Chaitanya and Bhalla, Upinder S and Wójcik, Daniel K",
    place=Neuroinformatics,
    scholar="http://scholar.google.com/scholar?cites=16146696496093454436&as_sdt=2005&sciodt=0,5&hl=en",
    pp="147--167",
    cluster_id="16146696496093454436",
    volume="14",
    entrytype="article",
    ID="ray2016nsdf",
    file="Ray2016a.pdf",
    publisher="Springer",
    number="2",
    scholar_ok=True,
))

scaffidi2016a = DB(WorkUnrelated(
    2016, "LondonTube: Overcoming Hidden Dependencies in Cloud-Mobile-Web Programming",
    due="Unrelated to provenance",
    display="scaffidi",
    authors="Scaffidi, Christopher and Dove, Andrew and Nabi, Tahmid",
    place=CHI,
    scholar="http://scholar.google.com/scholar?cites=5754868581428668925&as_sdt=2005&sciodt=0,5&hl=en",
    ID="scaffidi2016londontube",
    cluster_id="5754868581428668925",
    organization="ACM",
    pp="3498--3508",
    entrytype="inproceedings",
    file="Scaffidi2016a.pdf",
    scholar_ok=True,
))

schone2016a = DB(WorkUnrelated(
    2016, "Incremental Runtime-generation of Optimisation Problems using RAG-controlled Rewriting",
    due="Unrelated to scripts. Unrelated to provenance",
    display="schöne",
    authors="Schöne, René and Götz, Sebastian and Aßmann, Uwe and Bürger, Christoff",
    place=MODELS,
    ID="schoneincremental",
    entrytype="article",
    file="Schone2016a.pdf",
    scholar_ok=True,
))

schreiber2016a = DB(WorkUnrelated(
    2016, "Towards Provenance Capturing of Quantified Self Data",
    due="Only uses provenance collected by other tools to produce a Quantified Self provenance graph",
    star="[todo] Gives examples of tools that can be used for capturing provenance: Bachmann2011, Stamatogiannakis2014, noWorkflow, yesWorkflow",
    display="schreiber",
    authors="Schreiber, Andreas and Seider, Doreen",
    summary="Presents concepts for tracking provenance in typical Quantified Self Workflows",
    place=IPAW,
    file="Schreiber2016a.pdf",
    pp="218--221",
    organization="Springer",
    entrytype="inproceedings",
    scholar_ok=True,
    local="McLean, VA, USA",
))

schubert2016a = DB(WorkUnrelated(
    2016, "Panel 6: Data Integration and Visualization Friday, October 28, 2015 at 1: 45 pm",
    due="Non Paper Format",
    display="schubert",
    authors="Schubert, Aurel and Deshpande, Amol and Sarlin, Peter",
    place=Unpublished,
    ID="schubertpanel",
    file="Schubert2016a.pdf",
    entrytype="article",
    scholar_ok=True,
))

schulz2016a = DB(WorkUnrelated(
    2016, "A systematic view on data descriptors for the visual analysis of tabular data",
    due="Unrelated to scripts",
    display="schulz",
    authors="Schulz, Hans-Jörg and Nocke, Thomas and Heitzler, Magnus and Schumann, Heidrun",
    place=InfVis,
    pp="1473871616667767",
    file="Schulz2016a.pdf",
    publisher="SAGE Publications",
    ID="schulz2016systematic",
    entrytype="article",
    scholar_ok=True,
))

smith2016a = DB(WorkUnrelated(
    2016, "A document-driven method for certifying scientific computing software for use in nuclear safety analysis",
    due="Unrelated to provenance",
    display="smith",
    authors="Smith, W Spencer and Koothoor, Nirmitha",
    place=NET,
    scholar="http://scholar.google.com/scholar?cites=6925345017670512805&as_sdt=2005&sciodt=0,5&hl=en",
    pp="404--418",
    cluster_id="6925345017670512805",
    number="2",
    file="Smith2016a.pdf",
    publisher="Elsevier",
    ID="smith2016document",
    entrytype="article",
    link="http://www.sciencedirect.com/science/article/pii/S1738573315002582",
    volume="48",
    scholar_ok=True,
))

smith2016b = DB(WorkUnrelated(
    2016, "State of the practice for mesh generation and mesh processing software",
    due="Unrelated to scripts. Unrelated to provenance",
    display="smith",
    authors="Smith, W Spencer and Lazzarato, D Adam and Carette, Jacques",
    place=AES,
    pp="53--71",
    file="Smith2016b.pdf",
    publisher="Elsevier",
    ID="smith2016state",
    entrytype="article",
    volume="100",
    scholar_ok=True,
))

stamatogiannakis2016a = DB(WorkUnrelated(
    2016, "Trade-Offs in Automatic Provenance Capture",
    due="Compares overheads of SPADEv2 (with strace), tariq2012a (LLVM compiler), and DataTracker (dynamic instrumentation)",
    display="vermeulen",
    star="[survey]",
    authors="Stamatogiannakis, Manolis and Kazmi, Hasanat and Sharif, Hasim and Vermeulen, Remco and Gehani, Ashish and Bos, Herbert and Groth, Paul",
    place=IPAW,
    file="Stamatogiannakis2016a.pdf",
    volume="9672",
    ID="vermeulen2016trade",
    entrytype="inproceedings",
    organization="Springer",
    pp="29",
    scholar_ok=True,
    local="McLean, VA, USA",
))

sun2016a = DB(WorkUnrelated(
    2016, "A Provenance-aware Access Control Framework with Typed Provenance",
    due="Unrelated to scripts",
    display="sun",
    authors="Sun, Lianshan and Park, Jaehong and Nguyen, Dang and Sandhu, Ravi",
    place=TDSC,
    number="4",
    volume="13",
    scholar="http://scholar.google.com/scholar?cites=8303522899695853498&as_sdt=2005&sciodt=0,5&hl=en",
    ID="sun2016provenance",
    cluster_id="8303522899695853498",
    publisher="IEEE",
    pp="411--423",
    entrytype="article",
    file="Sun2016a.pdf",
    scholar_ok=True,
))

thanos2016a = DB(WorkUnrelated(
    2016, "White Paper on Research Data Service Discoverability",
    due="Unrelated to provenance",
    display="thanos",
    authors="Thanos, Costantino and Klan, Friederike and Kritikos, Kyriakos and Candela, Leonardo",
    place=Publications,
    pp="1",
    number="1",
    file="Thanos2016a.pdf",
    publisher="Multidisciplinary Digital Publishing Institute",
    ID="thanos2016white",
    entrytype="article",
    link="http://www.mdpi.com/2304-6775/5/1/1/htm",
    summary="Recommends YesWorkflow",
    volume="5",
    scholar_ok=True,
))

thavasimani2016a = DB(WorkUnrelated(
    2016, "Facilitating reproducible research by investigating computational metadata",
    due="Unrelated to scripts collection",
    display="thavasimani",
    authors="Thavasimani, Priyaa and Missier, Paolo",
    place=BigData,
    pp="3045--3051",
    file="Thavasimani2016a.pdf",
    ID="thavasimani2016facilitating",
    organization="IEEE",
    entrytype="inproceedings",
    summary="Analyse difference on provenance between noWorkflow and YesWorkflow",
    scholar_ok=True,
))

vartak2016a = DB(WorkUnrelated(
    2016, "Modeldb: a system for machine learning model management",
    due="Unrelated to scripts. Unrelated to provenance",
    display="vartak",
    authors="Vartak, Manasi and Subramanyam, Harihar and Lee, Wei-En and Viswanathan, Srinidhi and Husnoo, Saadiyah and Madden, Samuel and Zaharia, Matei",
    place=HILDA,
    file="Vartak2016a.pdf",
    publisher="ACM",
    pp="14",
    entrytype="inproceedings",
    organization="ACM",
    cluster_id="8689969351249692702",
    scholar="http://scholar.google.com/scholar?cites=8689969351249692702&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))

zawoad2016a = DB(WorkUnrelated(
    2016, "SECAP: Towards Securing Application Provenance in the Cloud",
    due="Unrelated to scripts",
    display="zawoad",
    authors="Zawoad, Shams and Hasan, Ragib",
    place=CLOUD,
    file="Zawoad2016a.pdf",
    entrytype="article",
    ID="zawoadsecap",
    scholar_ok=True,
))

zehl2016a = DB(WorkUnrelated(
    2016, "Handling metadata in a neurophysiology laboratory",
    due="Unrelated to provenance",
    display="zehl",
    authors="Zehl, Lyuba and Jaillet, Florent and Stoewer, Adrian and Grewe, Jan and Sobolev, Andrey and Wachtler, Thomas and Brochier, Thomas G and Riehle, Alexa and Denker, Michael and Grün, Sonja",
    place=FNInf,
    scholar="http://scholar.google.com/scholar?cites=4184293495185910297&as_sdt=2005&sciodt=0,5&hl=en",
    cluster_id="4184293495185910297",
    volume="10",
    entrytype="article",
    link="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4949266/",
    file="Zehl2016a.pdf",
    publisher="Frontiers Media SA",
    ID="zehl2016handling",
    scholar_ok=True,
))

zhang2016a = DB(WorkUnrelated(
    2016, "Materialization optimizations for feature selection workloads",
    due="Unrelated to scripts. Unrelated to provenance",
    display="zhang",
    authors="Zhang, Ce and Kumar, Arun and Ré, Christopher",
    place=TODS,
    number="1",
    file="Zhang2016a.pdf",
    volume="41",
    pp="2",
    entrytype="article",
    publisher="ACM",
    cluster_id="15698333884675952211",
    scholar="http://scholar.google.com/scholar?cites=15698333884675952211&as_sdt=2005&sciodt=0,5&hl=en",
    scholar_ok=True,
))
